### ISSUE TITLE
Duplicated tray icon

### ISSUE THREAD

**Issue by ericvilla** [Noovolari/leapp#10]
**Bug description**
When a Session Card is clicked, new tray icons appear in the top bar.

**To Reproduce**
1. Launch the application;
2. From the Quick List, click on a Session Card.

**Expected behavior**
Only one tray icon is expected to be shown in the top bar.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version: 18.04

**Comment by urz9999** [comment]
Fixed in commit ac70d94
