### ISSUE TITLE
Visual Bug in Options -> SAML Auth

### ISSUE THREAD

**Issue by Gavin89** [Noovolari/leapp#100]
**Describe the bug**
SAML Auth button does not highlight when selected, and hamburger options is blank

**Leapp Version**
v0.4.7

**To Reproduce**
1. Go to 'Options'
2. Click on 'SAML Auth'
3. You see that the tab has not been highlighted
4. Click on 'Hamburger Option'
5. You see that options are blank

**Expected behavior**
I'd expect the tab to be highlighted, and hamburger option display options

**Screenshots**
<img width="521" alt="Screenshot 2021-04-07 at 10 35 50" src="https://user-images.githubusercontent.com/5630403/113845664-a9ce8900-978d-11eb-8fa3-89eaf88d16a4.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - OS Version 10.14.6
 - Leapp Version 0.4.7

**Additional context**

**Comment by andreacavagna01** [comment]
Solved in v0.4.7
