### ISSUE TITLE
Filter applied only the first time

### ISSUE THREAD

**Issue by pontili** [Noovolari/leapp#101]
If I use a filter to select my aws accounts it filters the result. Coming back to leapp a couple of minutes later, I still see the filter but I have the full list of aws accounts

![leap](https://user-images.githubusercontent.com/12407596/113871358-1a3bd100-97b3-11eb-9601-6f4250425152.png)

**Comment by andreacavagna01** [comment]
after a refresh of the credentials probably the filter is lost. Clearly a bug, thanks for reporting it!

**Comment by andreacavagna01** [comment]
Fixed in version v0.5.0, let me know if it works now
