### ISSUE TITLE
Can't go back from "Choose provider" screen

### ISSUE THREAD

**Issue by bboure** [Noovolari/leapp#103]
**Describe the bug**
After clocking the `+` button to create a new account, I can't go back

**Leapp Version**
0.4.6

**To Reproduce**
1. Click the `+` button to create a new account
2. Try to go back to the home screen.

Workaround: Choose a provider and strategy and there will be a `BACK` button

**Expected behavior**
There should be a `<` button.

**Screenshots**
![image](https://user-images.githubusercontent.com/7089997/114506568-47b0d080-9c32-11eb-9478-f110a0dae069.png)

**Comment by andreacavagna01** [comment]
Thanks for reporting, I think this is easy to implement but also needs a redefinition with a new UX/UI for this session creation form in future

I think it's a good issue for first contributor also

**Comment by andreacavagna01** [comment]
The back button has been added in v0.5.0, closing the issue
