### ISSUE TITLE
Opening in default browser made Leapp unusable when alternative credentials required

### ISSUE THREAD

**Issue by AMMullan** [Noovolari/leapp#104]
**Describe the bug**
Since 0.4.7, with the introduction of using the default browser, I am unable to use Leapp (and nobody in my team will be either now) as we use different credentials to authenticate to SSO than what we login to our computers with but the default browser uses our logged in credentials. The Leapp interface is incredibly slow presumably because of this.

**Leapp Version**
0.4.7

**Expected behavior**
There should be the option of either using an alternative browser, or at least have the option of how Leapp used to work with it's own built-in browser that didn't use logged in credentials.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version 10
 - Leapp Version 0.4.7

**Comment by AMMullan** [comment]
![image](https://user-images.githubusercontent.com/9948612/114734581-41a71680-9d3c-11eb-9c96-866cfd1486b5.png)

Tried clearing my Leapp config (in %USERPROFILE%\.Leapp) and then re-setup Leapp to see if it fixed the performance issue but get the above - can't see any log files actually written...

**Comment by andreacavagna01** [comment]
Working right now on this fix! we will solve it today and push a new version with this fix ASAP. 
I'm really sorry about this

**Comment by AMMullan** [comment]
No probs - I appreciate it's hard to account for every possible scenario that the software will be used in :)

**Comment by andreacavagna01** [comment]
The bug in Session provisioning has been fixed, now the AWS Single Sign-On flow works again. 
Closing the issue

**Comment by AMMullan** [comment]
I don't understand how this is fixed? It's still forcing it to open my default browser and thus not giving me an opportunity to sign on with different credentials thus rendering it still unusable...

**Comment by andreacavagna01** [comment]
the typeError showed is fixed with the current Sign-in method has been fixed, Default opening in the browser window, for now, give us the opportunity to sign with all the AWS Single Sign-on.

An option to open the browser from a web view still isn't enabled, we will work on that opportunity for the next releases. 
Until now, AWS Single sign-on flow has started working.

I'm reopening the issue, if I can help you with your problem, please contact me in [Slack](https://join.slack.com/t/noovolari/shared_invite/zt-opn8q98k-HDZfpJ2_2U3RdTnN~u_B~Q)

**Comment by zmarouf** [comment]
Could we get a setting for browser of choice? Say webview vs default browser?
I was actually pleasantly surprised when Leapp switched
My experience has been that opening in a webview is annoying as I have to login multiple times to my provider in one case versus leaving it to the browser to decide in another case.

**Comment by AMMullan** [comment]
> Could we get a setting for browser of choice? Say webview vs default browser?
> I was actually pleasantly surprised when Leapp switched
> My experience has been that opening in a webview is annoying as I have to login multiple times to my provider in one case versus leaving it to the browser to decide in another case.

That was always the ask - I think for the most part using the browser is much better, but for some of us we have to enter different credentials and the workarounds are not workable.

**Comment by andreacavagna01** [comment]
Going back to the in-app login of AWS, the Default Browser login of Leapp will be re introduced as a preference in the next feature.
