### ISSUE TITLE
Internal loop or something similar

### ISSUE THREAD

**Issue by ivan-sirosh** [Noovolari/leapp#106]
**Describe the bug**
After deleting the folder `~/.aws` Leapp becomes unusable. App restart does not help. It looks like it has an infinity internal loop, also the app can not be closed, only a kill command helps.

**Leapp Version**
0.4.7

**To Reproduce**
1. Run App
2. Exit App
3. Delete `~/.aws` folder
4. Run App

**Expected behavior**
Should not stuck

**Screenshots**
<img width="811" alt="Screenshot 2021-04-15 at 09 56 56" src="https://user-images.githubusercontent.com/36622326/114834628-060a5c00-9dd1-11eb-9adb-e69cdc3d8cfe.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3 (20D91)
 - Darwin 20.3.0
 - Leapp Version 0.4.7

**Comment by andreacavagna01** [comment]
please restore the `.aws` folder to restore the correct functionalities of Leapp.

This folder is a default folder for the credentials management in AWS and is the one used by Leapp to manage your credentials, at this time Leapp is unable to regenerate this folder by itself.

If you need any help, I'm happy to help you with [slack](https://join.slack.com/t/noovolari/shared_invite/zt-opn8q98k-HDZfpJ2_2U3RdTnN~u_B~Q) for a better troubleshooting:

**Comment by andreacavagna01** [comment]
We are supporting the default credentials file path at the moment, following the [AWS docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)

**Comment by ivan-sirosh** [comment]
Ok, folder was recreated and Leapp became usable again. But it is not obvious - for example I use scripts to do the same sso login by default profile as Leapp does by using CI/Deploy pipelines.

**Comment by andreacavagna01** [comment]
We will add a patch for this inconvenience in the next release
