### ISSUE TITLE
No [default] in ~/.aws/credentials

### ISSUE THREAD

**Issue by m-radzikowski** [Noovolari/leapp#109]
**Describe the bug**

I logged in to an account with plain access with MFA. When I try to run AWS CLI, I get `Unable to parse config file: /Users/mradzikowski/.aws/credentials`. Looking into the credentials file, it's missing the `[default]` in the first line, it starts with `aws_access_key` from the top.

When I copied the credentials file content, turned off Leapp, pasted the content back, and added a line with `[default]` at the top, AWS CLI works.

I do not use the new AWS profiles feature for any account, all of them are named "default" in Leapp.

**To Reproduce**

Not sure, yesterday that account worked ok, on the same Leapp version.

**Desktop (please complete the following information):**

OS: macOS
OS Version: 10.15.6
Leapp Version: 0.4.7

**Comment by andreacavagna01** [comment]
Now a change of profile will affect the credential file.

Closing the issue
