### ISSUE TITLE
Cross Account Truster Doesn't Work Anymore

### ISSUE THREAD

**Issue by jamroks** [Noovolari/leapp#110]
**Describe the bug**
Corss Account Access from a plain user (account) to a Truster Account doesn't work anymore since upgrade 

**Leapp Version**
Leapp :  0.4.7

**To Reproduce**
1. create a  Leapp plain user from an gateway account
2. create a truster with a role to assume to target account
3. use named profile 
4. try to connect to target account , it never succeed 

**Expected behavior**
It used to work , 2 days ago . then it just stop working for no apparent reason . 

The source account can connect  but the assume role to connect to the target account don't succeed

**Comment by andreacavagna01** [comment]
Thanks for reporting, this issue is connected to #107 and #109 we are fixing this bug and releasing a new bundle soon!

**Comment by andreacavagna01** [comment]
Cross account roles, "truster sessions" will now work with the fix of #107 and #109 in version v0.5.0.

Closing the issue

**Comment by jamroks** [comment]
Thank You
