### ISSUE TITLE
Current Truster account not marked top bar dropdown list

### ISSUE THREAD

**Issue by m-radzikowski** [Noovolari/leapp#112]
**Describe the bug**

After selecting an account with AWS Truster access, it is correctly marked as the current one in the app. But in the dropdown list after clicking the Leapp icon in top bar, the icon (house) is gray.

When I select AWS account with Plain access, the icon (human) is orange.

**To Reproduce**

1. Select AWS account with Truster access
2. Click on the Leapp icon in the top bar

**Expected behavior**

Icon next to the selected icon should be orange.

**Screenshots**

![image](https://user-images.githubusercontent.com/4042673/115718076-12fff000-a37b-11eb-8e28-e06e3101db4f.png)

**Desktop (please complete the following information):**

 - OS: MacOS
 - OS Version: 10.15.6
 - Leapp Version: 0.5.0

**Comment by ericvilla** [comment]
Solved in [v0.6.0](https://github.com/Noovolari/leapp/releases/tag/v0.6.0)
