### ISSUE TITLE
Icons in top bar dropdown list barely visible [UI]

### ISSUE THREAD

**Issue by m-radzikowski** [Noovolari/leapp#113]
**Describe the bug**

On Mac, when you click Leapp icon in the top bar, the dropdown list is slightly transparent. Because of that, gray (not active) icons are sometimes barely visible.

If the color under the dropdown is white (like in browser), the "house" icon is almost invisible. But if the color under is dark (like in IDE with a dark theme), the "person" icon is invisible.

This is not a critical issue, rather a minor UI issue 🙂 

**Screenshots**

![image](https://user-images.githubusercontent.com/4042673/115726536-18613880-a383-11eb-8163-fd4478ab81bc.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.15.6
 - Leapp Version: 0.5.0

**Comment by andreacavagna01** [comment]
I Will change the color palette for the top bar

**Comment by PatrykMilewski** [comment]
In the dark mode it looks fine!

**Comment by urz9999** [comment]
I've changed the icon to be more visible in both themes, they will be available in the next patch release!

**Comment by andreacavagna01** [comment]
fixed in v.0.6.1
