### ISSUE TITLE
Interrupted SSO login but Leapp shows account active

### ISSUE THREAD

**Issue by m-radzikowski** [Noovolari/leapp#114]
**Describe the bug**

When during SSO login in the browser, I close the browser, Leapp thinks it went fine and shows the account as active. I can change to other accounts from the same SSO and Leapp shows it's ok. In reality, the credentials file is empty, as SSO was not completed.

To fix it, you need to restart the Leapp. Then when you select account it opens the browser to do SSO again.

**To Reproduce**

1. Select account with SSO login
2. Browser opens
3. Close the browser window
4. See Leapp showing account as active
5. Check `~/.aws/credentials` file, it's empty

**Expected behavior**

Leapp should show the account connection status as "in progress", with a spinner or something, until receiving the callback from the browser.

If I close the browser window I should be able to trigger SSO login again. Simplest - click on the currently selected account to deactivate it, and click it again to activate should trigger SSO login.

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.15.6
 - Leapp Version: 0.5.0

**Comment by andreacavagna01** [comment]
AWS SSO is refactored and the whole session specification for session status is up now https://github.com/Noovolari/leapp/wiki/specs
