### ISSUE TITLE
Missing [default] header from AWS SSO imported accounts

### ISSUE THREAD

**Issue by pethron** [Noovolari/leapp#115]
**Describe the bug**
Roles imported from AWS SSO integration with _default_ profile don't inject the [default] header in the configuration file.

**Leapp Version**
0.5.0

**To Reproduce**
1. Import with AWS SSO integration
2. Accounts are populated and displayed correctly
3. Click on the account to start the session
5. CLI commands fails because of missing header

You have to manually set the account as default from the Leapp interface. Once done everything runs as expected.

**Expected behavior**
Should automatically set the account as default.

**Screenshots**
<img width="1236" alt="Screenshot 2021-04-23 at 10 29 22" src="https://user-images.githubusercontent.com/12462586/115843979-b0acfb00-a41f-11eb-8214-a025302116b3.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 11.2.3
 - Leapp Version: 0.5.0 

**Additional Context**
Should check for other imports.

**Comment by m-radzikowski** [comment]
I think this is resolved but not yet released, see #109

**Comment by andreacavagna01** [comment]
Resolved with v.0.6.0
