### ISSUE TITLE
Current sort by stopDate is not working good

### ISSUE THREAD

**Issue by jgrumboe** [Noovolari/leapp#122]
In https://github.com/Noovolari/leapp/blob/74ba2d10338da83b3182e798d551f6651d1af010/src/app/services/session.service.ts#L79 the lastStopDate is used to sort the session list.
This only works fine, when the session is really ended by clicking on the active session. If Leapp is closed completely the session will be closed by the shutdown routine but the lastStopDate seems not to be updated.
Therefore the sort order for the next start doesn't work.

Either the lastStopDate is also set when the app is closed completely and active sessions are cleaned up
or I suggest to introduce a lastStartDate. This could be set at https://github.com/Noovolari/leapp/blob/c8de5c59f9e48d4876bd1a75551194c1163d34d8/src/app/services/session.service.ts#L115 when a sessions i marked as true. And that's in IMO the right way to identify a last used session.

**Comment by urz9999** [comment]
Hi @jgrumboe, we have already noted that. We are currently working on it and we have already switched to startDateTime for ordering, we plan to release a new version next week that addresses this problem too. Thanks for the suggestion! 👍

**Comment by jgrumboe** [comment]
I'm using version 0.6.1 now and somehow sorting has changed, but don't see in which way. It's no timesort anymore but also not fully alphabetical. Weird.
![image](https://user-images.githubusercontent.com/5127047/128352130-77181c8d-cfd3-4788-8fd6-0473cbc07a46.png)

**Comment by ericvilla** [comment]
Thank you @jgrumboe for the feedback! We'll check it asap and provide you with more info

**Comment by andreacavagna01** [comment]
closing by inactivity
