### ISSUE TITLE
Leapp CLI

### ISSUE THREAD

**Issue by pethron** [Noovolari/leapp#132]
Implementation of the Command Line Interface for Leapp.

~~As the codebase is expanding and we are trying to fit the needs of everyone while being open to the community and integrate with more and more third parties; we are starting to feel the need to do some separation of concerns of the application logic.~~

~~Namely, we would like to **split the core engine of Leapp into a separate daemon and a CLI on which the UI will be built upon** on a different project.~~

~~Like this, we think that we can better help both people using the UI and the terminal and empower people to easily get started in writing their own integrations and contribute to the project with a greater focus on their needs. 
It should come to even easier integration with package managers as brew and chocolatey, as pointed out in another discussion.~~

_Originally posted by @pethron in https://github.com/Noovolari/leapp/discussions/52_

**Comment by pethron** [comment]
The CLI will be implemented in typescript without the need to split the project. Closing due to roadmap change.

**Comment by demolitionmode** [comment]
Thanks for the update @pethron, is there an issue we can follow to track progress?

**Comment by pethron** [comment]
You're right! I'll reopen and rephrase the original post and we can use this to track progress on the CLI.

**Comment by managedkaos** [comment]
Adding a comment here vs opening a new issue for CLI requests:

**Question**: is there a way to trigger leapp from the CLI?  My workflow is to create an AWS profile and then tie it to a python virtual environment.  When I start the environment, it hooks into the AWS credentials and sets the environment for the corresponding profile.

With leapp, it looks like I would have to open the app and start a session before activating my python environment.  If I could pull leapp into my current workflow (without having to go to a GUI), it would be awesome.

Also, for folks that switch contexts often, is there a way to activate multiple profiles at the same time?  I could, of course, go into the UI and start multiple sessions, but would be cool if there was a way to link sessions so they are activated at the same time; for example, I need two sessions: one in the dev account and one in the prod account at the same time.

**Comment by andreacavagna01** [comment]
We are working on the CLI version and it will be available within 3 weeks.
Also, you can have more than one active Leapp Session at the same time through [Named Profiles](https://docs.leapp.cloud/0.10.0/built-in-features/aws-named-profiles/).

Thanks for the contribution!

**Comment by andreacavagna01** [comment]
Officially released!
