### ISSUE TITLE
Credentials Backup is overwritten if you do not finish setup and open leapp again

### ISSUE THREAD

**Issue by sevenfields-matt** [Noovolari/leapp#133]
**Describe the bug**
If you exit out of the OOBE setup then reload leapp it will overwrite the backup made during the initial setup

**Leapp Version**
Just downloaded it, but leapp no longer opens for some reason so I can't get the version

**To Reproduce**
1. Download Leapp
2. Open it the first time, watch for "Leapp has backedup credentials file"
3. Click exit during provider setup
4. Open Leapp again, watch for "Leapp has backedup credentials file"
5. Open credentials.leapp.bkp and notice it is blank

**Expected behavior**
Leapp will not overwrite the backup, and by extension delete all credentials the user had before installing leapp

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - OS 10
 - Leapp Version Latest as of 06-30-2021

**Additional context**
This is not good in 2 minutes after install I have to rebuild my credentials file.

**Comment by ericvilla** [comment]
Thank you @sevenfields-matt for the bug report! We'll fix it for the next release

**Comment by andreacavagna01** [comment]
released in v.0.6.2
