### ISSUE TITLE
Add as a chocolatey package

### ISSUE THREAD

**Issue by robcube** [Noovolari/leapp#134]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like leapp available through the Chocolatey package manager. (https://chocolatey.org/)

**Describe alternatives you've considered**
Websites can be have blocked thus this would be a nice alternative to direct download/install. In addition, minimizes the need to go through installers. (similar to how apt/yum/brew works)

**Additional context**
None

**Comment by andreacavagna01** [comment]
Nice Idea! There is a discussion about this: https://github.com/Noovolari/leapp/discussions/51#discussion-74530

I'm not confident with Choco but I will be happy to help if there is someone expert with this package manager

**Comment by robcube** [comment]
Closing since it's already mentioned. Thanks @andreacavagna01, didn't search well enough before. ✌
