### ISSUE TITLE
Support U2F hardware MFA keys

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#135]
One of the 2-factor authentication options for Google/Gsuite is U2F hardware security key such as YubiKey. I use it and would like Leapp to support it.

![image](https://user-images.githubusercontent.com/2793313/124027530-d8808800-d9a7-11eb-9f4f-55e7d373eb3a.png)

**Comment by andreacavagna01** [comment]
Nice enhancement, Need to check how to handle this case with webviews! 

Thanks for reporting the issue

**Comment by andreacavagna01** [comment]
refer to this issue:
https://github.com/electron/electron/issues/3226

will look in-dept on tomorrow

**Comment by m-radzikowski** [comment]
@andreacavagna01 what's the plan regarding the auth flow? Will you keep that in Electron or move it to the default browser (like you tried some time ago, in rollbacked version)? I think this decision influences how to approach this issue and #92 as well.

**Comment by andreacavagna01** [comment]
In the next weeks, we will re-implement the Default browser opening as a preference of Leapp for accessing AWS SSO, so users can choose if the in-app login is the preferred way as @AMMullan asked, or to choose it in the default browser, like @hoegertn asked

**Comment by clintoncampbell** [comment]
I assume that this also explains the inability to use WebAuthn methods for the AWS Identity Provider within SSO? I'm stuck at the prompt that reads "Additional verification required. Follow instructions from your browser". 

It seems like @andreacavagna01's proposed fix will also resolve that, but I'd be happy to provide more context or validate via a test build if needed.

**Comment by andreacavagna01** [comment]
I will add this to the project and we will introduce the way to log into AWS Single Sign-On with FIDO2 AuthN authentication, via the default Browser login.

This will be added as an option to login in to AWS Single Sign-On

**Comment by mholttech** [comment]
Looks like https://github.com/electron/electron/pull/30438 has brought native U2F support into Electron

**Comment by ericvilla** [comment]
Thank you @mholttech, it is necessary to test if it works by running the application with an updated Electron version

**Comment by Nuru** [comment]
Do we have a status update on this?

**Comment by pethron** [comment]
Implemented with electron update in v0.8.0. Closing.

**Comment by gbdlin** [comment]
I'm still seeing this error message when logging in. Was this change rolled back? or is it a regression?
