### ISSUE TITLE
Ability to rename sessions

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#136]
I created a session with a typo in the name. I would like to be able to rename it, but I cannot find a way to do so. 

Please enable users to rename sessions.

**Comment by andreacavagna01** [comment]
Implementing edit functionalities is easier with the new project structure, good first issue!

**Comment by RafPe** [comment]
@andreacavagna01 could you elaborate on that one a little bit ? I have multiple sessions now configured that I would like to simply rename however:
* for the ones which have source credentials I need to retype my credentials ?
* for chained sessions there is not even an option to rename

Is that something that is planned and if so what is the ETA for this ?

**Comment by andreacavagna01** [comment]
There is an ETA, I think we will do it in the next 2 sprints. Right after the new UX/UI :) thanks for the question

**Comment by bkmeneguello** [comment]
I can't change the names of AWS Single Sign-On sessions, there is no edit nor change name menu option.
