### ISSUE TITLE
No prompt for MFA

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#140]
When starting a session from the menu bar icon menu, if MFA token is needed and the Leapp window is closed, there is no prompt for the MFA token and no indication one is needed. Instead, what happens is the option for that session disappears from the menu.

**Leapp Version**
0.6.0

**Expected behavior**
Leapp window would open on the same screen and (macOS Spaces) desktop as the clicked menu bar icon and prompt for MFA token.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: 10.15.7
 - Leapp Version: 0.6.0

**Comment by andreacavagna01** [comment]
So, there is no notification whenever an MFA token expire?

**Comment by Nuru** [comment]
I think if you have Leapp open it might a request for the MFA token in the Leapp window, but that is it, and is far from sufficient.

I would expect Leapp to force its window open and to the front to present that notification. It might also make a notification center notification and add a decoration on the menu bar icon and dock icon.

**Comment by andreacavagna01** [comment]
fixed in v.0.6.1
