### ISSUE TITLE
Inadherances to Apple UI guidelines on macOS

### ISSUE THREAD

**Issue by mpkonmbk** [Noovolari/leapp#142]
Currently, Leapp's Menu Bar icon looks like this:
<img width="488" alt="Screenshot 2021-07-02 at 14 33 24" src="https://user-images.githubusercontent.com/53444155/124275201-76a85580-db42-11eb-9850-07fc350c7105.png">
sticking out like a sore thumb. It desperately wants to be monochrome (it told me), and appropriately sized - a nice and quick, noticeable UI/UX win.

**Comment by gzxiii** [comment]
Yes, I think it should stick with the apple UI guidelines. Same as for the Docking Icon. 

https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/
https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/

**Comment by andreacavagna01** [comment]
fixed with the last release
