### ISSUE TITLE
Backup of credentials file overwrites the backup file itself if run again

### ISSUE THREAD

**Issue by niklaswesterstrahlecybercom** [Noovolari/leapp#144]
**Describe the bug**
While starting to use the app for first time, it creates a backup of the credentials file that existed on users .aws directory (Mac client).

If at this point user restarts the application, while you have credentials file empty 0 bytes and no other login config. And restart the app, it notices the empty credentials file, and takes a new "backup" - overwriting the original backup.

**Leapp Version**
Mac 0.6.0

**To Reproduce**
1. Install a fresh Leapp
2. Open app, don't add credentials
3. Quit app
4. Open app again
5. Check your homedir

-rw-r--r--    1      0 Jul  6 12:53 credentials
-rw-r--r--    1 f      0 Jul  6 12:38 credentials.leapp.bkp

**Expected behavior**
If credentials.leapp.bkp file exists, that file is not touched again, rather renamed with a random identifier.

**Desktop (please complete the following information):**
 - OS: MacOs
 - OS Version 11.4
 - Leapp Version 0.6.0

**Comment by andreacavagna01** [comment]
We will fix this in the next release with this problem:
https://github.com/Noovolari/leapp/issues/133

thanks for reporting

**Comment by ericvilla** [comment]
I've re-opened the #133 issue that will be closed upon next release

**Comment by andreacavagna01** [comment]
fixed in v.0.6.1
