### ISSUE TITLE
Named profile icon sometimes but not always colored on activation

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#145]
After activating a session, in the Quick List, sometimes the icon for the named profile is updated from grey to orange, and sometimes it is not.

**Leapp Version**
0.6.0

**To Reproduce**
Not exactly sure. I have multiple sessions enabled. Sometimes the icon changes, usually it does not. At this point I am not even sure what the intended behavior is. 

**Expected behavior**
Probably the icon should always change to orange when the session is active. For sure it should be consistent. If there is some meaning other than "session active" for why the icon remains grey or turns orange, it should be documented. 

**Screenshots**
![Leapp Session Icon color](https://user-images.githubusercontent.com/2793313/124650431-985d5180-de4e-11eb-9f53-2a6ea94d0952.png)

**Desktop (please complete the following information):**

-    OS: macOS
-    OS Version: 10.15.7
-    Leapp Version: 0.6.0

**Comment by andreacavagna01** [comment]
We will fix this in the next releases

**Comment by andreacavagna01** [comment]
fixed in v.0.6.1
