### ISSUE TITLE
Add generic "back" button, keyboard shortcut, and/or menu command

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#150]
**Describe the bug**
If you click on a link in the Leapp window, for example as I did today to follow one of the links in the release notes, there is no way to navigate back to the main window. While it is good to have a nice big `Back` button in the UI where you expect it, there should still be a generic way to go back regardless of the page you are on so that we do not get stuck on a page.

This would also help with login issues when going through the IdP login flow, e.g. if you make a mistake typing in the username but hit submit anyway.

**Leapp Version**
0.6.0

**To Reproduce**
1. Launch Leapp 0.6.0
2. Wait for "New version available" popup to appear
3. Click a link in the popup
4. Try to return to main Leapp page

**Expected behavior**
A menu item and a keyboard shortcut should be provided for "back" and "home" browser navigation, regardless of screen content.

**Screenshots**
![image](https://user-images.githubusercontent.com/2793313/125700989-275b6378-8e4a-410f-a42a-7ae1c938dbc6.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: 10.15.7
 - Leapp Version: 0.6.0

**Additional context**
Because at its heart Leapp is a web browser, it is subject to forward navigation due to links in pages.

**Comment by andreacavagna01** [comment]
We missed the target blank links in the updater, thanks for reporting!
