### ISSUE TITLE
Can I change SessionId to username when I start and end SSM Session?

### ISSUE THREAD

**Issue by seun9su** [Noovolari/leapp#151]
When session is activated using the AssumeRole function and SSM Session is connected, it is shown below.

```
❯ aws ssm start-session --target [instanceID]--region [region]

Starting session with SessionId: assumed-from-leapp-918e122ee2440c19b
sh-4.2$ exit
exit


Exiting session with sessionId: assumed-from-leapp-918e122ee2440c19b.


~ 20m 0s
❯
```

"assumed-from-leapp-918e122ee2440c19b" <- Can't I change this string to username?
For example, replace "assumed-from-leapp-918e122ee2440c19b" with "myname-918e122ee2440c19b"

**Comment by andreacavagna01** [comment]
With username you mean the session Alias?

**Comment by seun9su** [comment]
> With username you mean the session Alias?

The best method is to indicate the name of the IAM user who has the access key.
Because Leapp user can manipulate the session alias.
The reason why I want this feature is because when I connect to an instance with SSM Session, the Session History displays`arn:aws:sts::[accountid]:assumed-role/[role name]/assumed-from-leapp` in the owner tab, so I don't know exactly who logged in.

**Comment by andreacavagna01** [comment]
#155 There is an open pull request for that! thanks to @matthewriedel-flux

**Comment by ericvilla** [comment]
@seun9su we've just merged the pull request mentioned by @andreacavagna01, and fixed a retro-compatibility bug.
