### ISSUE TITLE
MFA prompt does not include Session Identifier

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#158]
Following up on #140, Leapp now nicely prompts for an MFA token when needed, but it does not indicate _which_ MFA token is needed. I may have 2 sessions active, and all the prompt says is something like "enter the MFA token". I want the prompt to include at least the Session Name of the Session that needs an MFA token. IAM Role Name and Named Profile would nice, too. 

**Leapp Version**
0.6.2

**Expected behavior**
MFA Prompt includes session identifiers.

**Comment by andreacavagna01** [comment]
Great! We will add it in the next release for sure

**Comment by ericvilla** [comment]
I'm going to close this issue because we've already solved it in a past release
