### ISSUE TITLE
[question] How to backup profile and sessions?

### ISSUE THREAD

**Issue by gitowiec** [Noovolari/leapp#159]
Hi, I'm new to LeApp. When I begun my new job, everything was setup for me by my colleague. I would like to update 0.6.0 to 0.6.2 on my Mac but I am afraid to loose all the profile and sessions configuration. Is it save to update LeApp? Just in case, how to backup all the configuration?
Best regards

**Comment by andreacavagna01** [comment]
the configuration file is in `~/.Leapp/Leapp-lock.json` you can create a backup of it for the v0.6.0.

By updating, you will maintain all your configuration previously set.

Thanks for opening the issue.

Closing the issue now
