### ISSUE TITLE
How do you prounounce "Leapp"?

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#164]
Please document your preferred pronunciation of the app name "Leapp". Is it the same as "leap"? Is it like the French "le app"? Is it "leap" with an extra "p":  lēp-pə? Is it Throatwarbler Mangrove?

**Comment by pethron** [comment]
It's like the word "leap" in English, with the second p silent.
From the word dictionary I found this [li:p], since I'm not a native speaker can you confirm it's correct?

**Comment by pethron** [comment]
Updated first-page documentation to include pronunciation.
