### ISSUE TITLE
AWS Role with path does not display properly

### ISSUE THREAD

**Issue by mholttech** [Noovolari/leapp#166]
**Describe the bug**
After testing support for AzureAD AWS Federation (#165) and logging into our environment I found that the AWS role name does not appear correctly when the AWS Role is in a path.

**Leapp Version**
Fork of 0.6.2 with Pull Request #165 

**To Reproduce**
1. Create a new Session
2. Click on 'AWS'
3. Click on 'IAM Role Federated'
4. Fill out the details and use a Role ARN that is in a path such as ``arn:aws:iam::123456789123:role/CAVM/AVM_app_dev``
5. See error

**Expected behavior**
I would expect to see the role name "AVM_app_dev" or the entire role path "CAVM/AVM_App_dev"

**Screenshots**
![image](https://user-images.githubusercontent.com/6945933/131409346-a0b8c743-8aec-487f-becd-8af75469cce3.png)

**Comment by pethron** [comment]
Thanks for reporting; we need to fix the method that extracts the last part from the ARN.
We'll try to fix this for the next release, I think it should be easy.
