### ISSUE TITLE
'Copy Account Number' not working for IAM User sessions

### ISSUE THREAD

**Issue by tgjohnst** [Noovolari/leapp#172]
**Describe the bug**
When I attempt to use the **Copy Account Number** action from the session dropdown menu for an IAM User profile, nothing is added to the clipboard despite a message that the copy was successful.

**To Reproduce**
1. Add an AWS session with the **IAM User** access method via **AWS -> IAM User** and entering access + secret keys
2. Use the dropdown menu for that profile and select **Copy Account Number**, either while the account is active or from the bulk list of sessions
3. A message will appear saying "Information copied! Your information have been successfully copied!"
4. Try to paste into any other application, but the clipboard has not been updated

**Expected behavior**
Expected behavior is that this action should add an account number associated with that IAM user to the clipboard. Otherwise, if IAM User profiles are not meant to have the 'Copy Account Number' functionality, this option should either be excluded from the dropdown menu (similar to 'Copy Role ARN', which does not show up for IAM sessions) or the popup message should not indicate that information has been successfully copied

**Desktop (please complete the following information):**
Leapp 0.6.2 running on MacOS 11.6 (Big Sur) on an M1 mac

**Screenshots**
![image](https://user-images.githubusercontent.com/5710633/134405833-566ce12d-f7cc-4fd4-92c6-ea909d20e188.png)

**Additional context**
The Copy Account Number functionality works fine for all other AWS SSO sessions I am using, so this problem appears to be specific to IAM user sessions.

**Comment by tgjohnst** [comment]
Thank you @urz9999 for such a fast fix!!

**Comment by urz9999** [comment]
No problem!
