### ISSUE TITLE
AzureAD login does not open browser

### ISSUE THREAD

**Issue by MaartenUreel** [Noovolari/leapp#173]
**Describe the bug**
I have configured an AWS account through "IAM Role Federated", to try and login using my Azure (Office365) account.
This is setup through the browser, so that works, but now I want to use Leapp for this too.

I get no validation when configuring the account so I'm unsure if it's correct, but nothing happens when trying to login. No browser window opens, like it does for our company AWS SSO configured account.

**Leapp Version**
0.7.1.0

**To Reproduce**

1. Add an account for cloud provider AWS
2. Choose Access Method "IAM Role Federated"
3. Fill in settings accordingly, see also screenshot below

**Expected behavior**
Login procedure to occur.

**Screenshots**
Configure account:
<img src="https://user-images.githubusercontent.com/1901942/135138015-53292c88-4bd3-475a-b5ef-27e0da86f226.png" width="400" />

Loading icon keeps spinning:
<img src="https://user-images.githubusercontent.com/1901942/135137580-16cd7bca-15ff-4a6d-8c32-235ca5290ed9.png" width="400" />

**Desktop:**
 - OS: Windows 11
 - Leapp 0.7.1.0

**Comment by ericvilla** [comment]
Hi @MaartenUreel, thank you for opening this issue! May I ask you what kind of Azure AD Enterprise Application are you using? Is it a SAML one?

**Comment by MaartenUreel** [comment]
Yes:

<img src="https://user-images.githubusercontent.com/1901942/135420947-22d72779-1ed0-49d3-a0ee-595a99d0f86d.png" width="400" />

**Comment by ericvilla** [comment]
I see you're using the "App Federation Metadata Url". Have you already tried using the "User access URL"? You can find it under your specific Enterprise Application's properties. It starts with "https://myapps.microsoft.com/signin/"

**Comment by MaartenUreel** [comment]
That has fixed the issue indeed, thanks.

Some guidance in the user interface on this, or validation, might be a good improvement here :)

**Comment by ericvilla** [comment]
Glad to hear that @MaartenUreel! We will add the required info to smooth the process
