### ISSUE TITLE
Use different terminal App instead of Terminal App

### ISSUE THREAD

**Issue by andreacavagna01** [Noovolari/leapp#176]
The problem faced is that people are using alternative Terminal Application than the Default one, like [iTerm](https://iterm2.com/) for macOS.

Add the ability to use the terminal App preferred by the user and not the default one!

At the moment, Leapp opens the terminal with the following function:
https://github.com/Noovolari/leapp/blob/4b975c6bd043d9383bc3b80ddf9cdbe170b82afd/src/app/services/execute.service.ts#L53

This function use:
- for MacOS it uses an Applescript:
https://github.com/Noovolari/leapp/blob/4b975c6bd043d9383bc3b80ddf9cdbe170b82afd/src/app/services/execute.service.ts#L55
- for Windows the start command:
https://github.com/Noovolari/leapp/blob/4b975c6bd043d9383bc3b80ddf9cdbe170b82afd/src/app/services/execute.service.ts#L59
- for Linux it uses this command:
https://github.com/Noovolari/leapp/blob/4b975c6bd043d9383bc3b80ddf9cdbe170b82afd/src/app/services/execute.service.ts#L61

This action is used in the SSM connect the action of Leapp and can be tested [following the documentation](https://docs.leapp.cloud/tutorials/aws/aws_ssm_connect/)

**Comment by ericvilla** [comment]
In Leapp v0.10.0 you can start an AWS SSM session through iTerm2 by selecting it in the options menu!

**Comment by ORuessel** [comment]
Hello @ericvilla is this also possible for windows application not only for MacOs ? Thanks for you help and best regards
