### ISSUE TITLE
refactor New Users documentation for IAM Users

### ISSUE THREAD

**Issue by andreacavagna01** [Noovolari/leapp#177]
Add more detailed information for new users on adding an IAM User session:
https://docs.leapp.cloud/tutorials/aws/iam_user/setup_in_leapp/

By clicking on the pencil in the top-right corner you can refactor the documentation page.

The needed information is:
- Specify the usage of an IAM User with reference to any AWS Doc
- Specify each Field of the AWS IAM User form and where to find it in the AWS account of the user

**Comment by pethron** [comment]
Closing due to updated documentation.
