### ISSUE TITLE
SSO Sync session somewhere on the front page

### ISSUE THREAD

**Issue by jgrumboe** [Noovolari/leapp#181]
**Is your feature request related to a problem? Please describe.**
Since we have a self service to temporarily create a more privileged AWS SSO account assignment for yourself, I would like to have a "Sync Sessions" button on the front page.
Currently, I need to promote myself in our tool and then open the Identity provider options menu to sync new sessions.

**Describe the solution you'd like**
I want to have a "sync sessions" button (maybe only some icon like 🔄  icon) near the searchbox and also in the taskbar menu.

**Comment by ericvilla** [comment]
This enhancement issue is covered in the last [release](https://www.leapp.cloud/releases)! I'm going to close it
