### ISSUE TITLE
Multiple MFA prompts for chained profile

### ISSUE THREAD

**Issue by jcogilvie** [Noovolari/leapp#182]
**Describe the bug**
I have two active sessions, one I'll call `master` and one I will call `chained`.  `master` requires MFA.  `chained` inherits MFA from `master`.  

When my mfa token expires, I am prompted twice.  Entering my MFA token in either of the prompts works equally well to authenticate, and the other prompt can be canceled (albeit an error is displayed upon canceling; this seems to have no effect).

**Leapp Version**
0.7.3

**To Reproduce**
1. Create an AWS session (in my case an IAM user) with MFA called `master`.  
2. Create a chained role session (in my case an IAM role), using `master` as root.    
3. Activate both sessions (which should only require MFA once iirc).
4. Wait for expiry
5. Notice that you are prompted for MFA reauthentication twice.

**Expected behavior**
A single prompt for MFA token.

**Desktop (please complete the following information):**
 - OS: OSX
 - OS Version 11.6
 - Leapp Version 0.7.3

**Comment by ericvilla** [comment]
Hi @jcogilvie, nice catch! 

As far as now, these two modals take part in two different flows and are not aware of each other.
To be precise, the modal is exactly the same, but there is no logic that checks whether an "equivalent" modal is currently open or not.

To manage AWS IAM User MFA modal concurrency we need to implement that logic, which is not trivial. At this moment, I think the best workaround is to ignore the second modal; as you said, it has no side effect if you ignore it in favour of the other one.

I hope it makes sense to you. I just leave this issue open, cause it can't be considered closed without any further investigation.

**Comment by jcogilvie** [comment]
It's still an issue in the latest version.
