### ISSUE TITLE
Upgrade to Fedora35 causing FATAL:gpu_data_manager_impl_private.cc(415)] GPU crash

### ISSUE THREAD

**Issue by mikecarrington** [Noovolari/leapp#187]
**Describe the bug**
Upgrade from Fedora 34 to 35 caused the Leapp AppImage to crash on start.

**Leapp Version**
0.7.3

**To Reproduce**
Steps to reproduce the behaviour:
Launch Leapp

➜ Leapp
Checking for update
Update for version 0.7.3 is not available (latest version: 0.7.3, downgrade is disallowed).
[4918:1105/130913.717686:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
fish: Job 1, 'Leapp' terminated by signal SIGTRAP (Trace or breakpoint trap)

**Expected behavior**
App opens.

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - OS Version

➜ uname -a
Linux fedora 5.14.15-300.fc35.x86_64 #1 SMP Wed Oct 27 15:53:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
Looks similar to https://ask.fedoraproject.org/t/all-chromium-based-apps-crashing-with-gpu-related-messages-after-recent-upgrade/16201/6

**Comment by mikecarrington** [comment]
Working in 0.8.0 version

**Comment by ericvilla** [comment]
Thank you for this precious feedback @mikecarrington 
If you encounter this issue again, please feel free to re-open the issue with additional info, if needed
