### ISSUE TITLE
Leapp Configuration File

### ISSUE THREAD

**Issue by Gowiem** [Noovolari/leapp#188]
**Is your feature request related to a problem? Please describe.**
I have a team of AWS users I support. Everyone uses AWS IAM Users that then assume roles into a dozen+ accounts. All of that information in regards to the various role assumptions + accounts is static and should be able to be shared across the various accounts.  

**Describe the solution you'd like**
I'd like the ability to have a single configuration file that I can share with my team, so that they only need to setup their root AWS IAM user and then they can import the leapp configuration file so that they can assume the many roles mentioned in that file. 

**Describe alternatives you've considered**
Using `~/.aws/config` possibly? May in conflict with #98 

**Additional context**
N/A

**Comment by pethron** [comment]
Hi @Gowiem, thanks for the suggestion; this is the use-case for the Team tier shown in this discussion https://github.com/Noovolari/leapp/discussions/178 . The mentioned issue was a way to import existing configurations from credentials or config files, and it's designed as a one-time action.

**Comment by Gowiem** [comment]
Ah @pethron understood -- I didn't know ya'll were planning on turning Leapp into a proper SaaS product. Sounds good and with that being the case... I think the one time import mentioned in #98 fits the bill. I'll close out.
