### ISSUE TITLE
Support logging into AWS Console via Leapp / Federated Session

### ISSUE THREAD

**Issue by Gowiem** [Noovolari/leapp#189]
**Is your feature request related to a problem? Please describe.**
Using `aws-vault`, I can utilize the `aws-vault login` command which opens a new browser tab and logs me into the AWS Console using the selected profile or role. 

**Describe the solution you'd like**
I'd like to be able to do the same with Leapp as this is a major time saver when switching between many accounts. 

**Describe alternatives you've considered**
None. 

**Additional context**
N/A

**Comment by pethron** [comment]
Thanks for the suggestion @Gowiem! We're already aware of this use-case and we already planned to support it, but I can't give an estimate on when it will be available. If by any chance someone want to try we can provide sone guidance on implementation.

**Comment by gshpychka** [comment]
This would be a major reason to switch to Leapp for me.

**Comment by drmikecrowe** [comment]
Instructions from [AWS here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-custom-url.html)

A [python gist](https://gist.github.com/ottokruse/1c0f79d51cdaf82a3885f9b532df1ce5)

**Comment by Gowiem** [comment]
@pethron any update on this one? I'm continuing to use and enjoy Leapp, but I still keep `aws-vault` around specifically so I can run their `aws-vault login` command and I'd love to ditch it once and for all once this gets implemented.

**Comment by pethron** [comment]
We scheduled to implement it in the previous quarter (obviously, we couldn't deliver it), so we're doing it this quarter! I can't be more precise on the ETA, but it's coming! https://docs.leapp.cloud/roadmap/

**Comment by Gowiem** [comment]
@pethron Great -- Thanks for the update and looking forward to it!

**Comment by gberenice** [comment]
@pethron looking forward to this feature 👍

**Comment by ericvilla** [comment]
In Leapp v0.10.0 you can open an AWS Web Console directly from a Leapp Session!

**Comment by Gowiem** [comment]
@ericvilla @pethron -- Just used this feature for the first time -- It's awesome 👏  👏  👏  

I'm now looking forward to uninstalling aws-vault from my machine :100:

**Comment by ericvilla** [comment]
A shout out to @rick-rtt and @andreacavagna01 for the implementation!
