### ISSUE TITLE
Freeze on force refresh

### ISSUE THREAD

**Issue by pethron** [Noovolari/leapp#19]
**Describe the bug**
When hitting the force refresh key combination, the page tries to refresh but it doesn't load anymore and become unresponsive. Quit will not work and only way to restart is to kill the process. 

**To Reproduce**
1. Hit CTRL+SHIFT+R
or
1. Select "view"
2. Hit Force Refresh

**Expected behavior**
App should refresh the page and display the home page or the page the user was on.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 10.15.6

**Comment by urz9999** [comment]
Solved in release [0.23](https://github.com/Noovolari/leapp/releases/tag/0.2.3)
