### ISSUE TITLE
v0.7.4 Signon Window can not be moved

### ISSUE THREAD

**Issue by mholttech** [Noovolari/leapp#191]
**Describe the bug**
prior to v0.7.4 you were able to move the signon window as shown below.
![image](https://user-images.githubusercontent.com/6945933/142035497-46278e84-5513-418d-af7d-f30df1c8832a.png)

With v0.7.4 there is no longer a border that allows moving the window:
![image](https://user-images.githubusercontent.com/6945933/142035471-59da18bd-2777-40f7-9629-733f920c8b0f.png)

**Leapp Version**
v0.7.4 vs v0.7.3

**To Reproduce**
1. Click on an account to sign in (Mine are configured as Azure AD SAML Links)
2. Try to move the window

**Expected behavior**
I expect to be able to move this window. I regularly do this so that I can access my password manager when logging in.

**Screenshots**
See Above

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version 10
 - Leapp Version v0.7.4

**Comment by pethron** [comment]
Still present in v0.8.0 (MacOS).

**Comment by ericvilla** [comment]
Solved in Leapp v0.10.0! You can download it from [here](https://www.leapp.cloud/releases)
