### ISSUE TITLE
"AWS SSO" page on the docs site 404s

### ISSUE THREAD

**Issue by seano-vs** [Noovolari/leapp#193]
**Describe the bug**
1. Visit https://docs.leapp.cloud/contributing/aws-sso.md by clicking on the "AWS SSO" link in the sidebar
2. See a 404

**Expected behavior**
It does not 404.

**Desktop (please complete the following information):**
pretty sure this will work across all OSes

**Additional context**
It's not entirely clear that I should file this elsewhere, so me deepest apologies if this is in the wrong place.

**Comment by pethron** [comment]
Thanks for reporting, working on the docs!

**Comment by pethron** [comment]
Updated docs:
https://docs.leapp.cloud/configuring-integration/configure-aws-single-sign-on-integration/
