### ISSUE TITLE
The Leapp icon is larger than all other icons in the MacOSX Dock

### ISSUE THREAD

**Issue by Gowiem** [Noovolari/leapp#196]
**Describe the bug**
The Leapp icon is larger than all other icons in the MacOSX Dock. See screenshot here: 

![CleanShot 2021-11-23 at 13 53 39](https://user-images.githubusercontent.com/1392040/143116571-ef4567b2-b372-4b34-9867-6b8819f827ef.png)

**Leapp Version**
Leapp 0.7.4

**To Reproduce**
1. Install Leapp on Mac OSX
2. Open Leapp
3. Check out the size of the icon compared to other icons

**Expected behavior**
Icon should be the same size as everything else.

**Screenshots**
![CleanShot 2021-11-23 at 13 53 39](https://user-images.githubusercontent.com/1392040/143116598-dfa35768-e815-4c25-9aed-14e6f8adc2d9.png)

**Desktop (please complete the following information):**
 - OS: MacOSX
 - OS Version: Big Sur 11.6
 - Leapp Version: 0.7.3

**Additional context**
N/A

**Comment by andreacavagna01** [comment]
We will fix in the next version, thanks for reporting!

**Comment by ericvilla** [comment]
This enhancement issue is covered in the last [release](https://www.leapp.cloud/releases)! I'm going to close it
