### ISSUE TITLE
ENOENT error unable to find '%USERPROFILE%/.Leapp/.latest.json

### ISSUE THREAD

**Issue by wsmelton** [Noovolari/leapp#197]
**Describe the bug**
Open the application after extracting the zip file.

After doing screen recording was able to pull the application showing the following message:
> ENOENT: no such file or directory, open 'c:\users\smelton/.Leapp/.latest.json'

**Leapp Version**

0.7.4.0

**To Reproduce**
1. Download the zip from the site
2. Extract to local disk (e.g. C:\tools)
3. Open the application
4. See the application do nothing, if you watch without blinking you may see the message noted above show up.
5. Check the `%USERPROFILE%\.leapp` path and only file found `Leapp-lock.json` with content, but no other file is found in the directory.
6. Tray icon exists
7. Task Manager shows 4 processes running, have to manual kill them to close it out completely.

**Expected behavior**
Have option to perform initial setup for cloud provider

**Screenshots**
![image](https://user-images.githubusercontent.com/11204251/143161205-945ce7f8-f63e-4fe8-8d29-dbe5681f6ba7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version 10
 - Leapp Version 0.7.4.0

**Additional context**

**Comment by pethron** [comment]
Can you confirm it's still present in v.0.8.0?

**Comment by wsmelton** [comment]
No issues in v0.8.0!

**Comment by pethron** [comment]
Fixed in v0.8.0.
