### ISSUE TITLE
AzureAD login to AWS using iam role federated

### ISSUE THREAD

**Issue by TamerElfeky** [Noovolari/leapp#198]
**Describe the bug**
Cannot use AzuereAD as SSO for AWS

**Leapp Version**
0.7 and 0.8

**To Reproduce**
1. use 'IAM Role federated'
2. for Idp "https://login.microsoftonline.com/xxxx-xxxx-xxx-xxx/saml2"
3. Add both Idp and assumed roles .
4. Save and start the session

**Expected behavior**
- expected to get microsoft  mail credential window but found nothing ;

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by urz9999** [comment]
Hi @TamerElfeky! Thanks for reporting us! We'll look into it ASAP and respond to you with further information when we have some details to share. Briefly looking at the code, it could be a missing condition in our filter.

**Comment by m-radzikowski** [comment]
I think I have the same problem. Access to AWS is provided through Active Directory. To access web Console, I go to custom page to log in and it redirects me to https://signin.aws.amazon.com/saml where I have a list of available roles to choose.

In Leapp I tried to add AWS -> IAM Role Federated and provide:

- Role ARN: the role I’m assuming at the end, let’s say `arn:aws:iam::123456789012:role/Admin`
- SAML 2.0 Url: the custom URL that redirects me to AWS SAML after authorization
- AWS Identity Provider ARN: the trusted entity value from the role I’m assuming, let’s say `arn:aws:iam::123456789012:saml-provider/AD`

but when choosing this session in Leapp it only spins, I’m not getting any error.

Also, #186 can be related.

**Comment by TamerElfeky** [comment]
@m-radzikowski, i doubt the way AzureAD [implemented](https://github.com/Noovolari/leapp/blob/master/src/app/services/session/aws/methods/aws-iam-role-federated.service.ts#L192)  may expect another path or redirection. 

can you example of saml 2.0 url , i have use the one from "IAM , identity provider" after setup the integration with AzureAD

**Comment by m-radzikowski** [comment]
The SAML URL I'm using is in the format: `https://mycompany.com/adfs/ls/idpinitiatedsignon?loginToRp=urn:amazon:webservices` which seems to be a standard thing (https://aws.amazon.com/blogs/security/how-to-implement-federated-api-and-cli-access-using-saml-2-0-and-ad-fs/).

I'm not sure how does this logic work: https://github.com/Noovolari/leapp/blob/6128f90b6b720788d444d6d6ca78504106851129/src/app/services/session/aws/methods/aws-iam-role-federated.service.ts#L176
but I added

```ts
if (details.url.indexOf('https://mycompany.com/') !== -1) {
  idpWindow = null;
  resolve(true);
}
```

for test, to see what will happen. And also I added this domain to the filters list.

As a result, the window opened with mycompany AD login page (previously it did not), however in console I got:

```
[21070:1129/231026.361997:INFO:CONSOLE(1072)] "Unhandled Promise rejection: ERR_FAILED (-2) loading 'https://mycompany.com/adfs/ls/idpinitiatedsignon?loginToRp=urn:amazon:webservices' ; Zone: <root> ; Task: null ; Value: Error: ERR_FAILED (-2) loading 'https://mycompany.com/adfs/ls/idpinitiatedsignon?loginToRp=urn:amazon:webservices' Error: ERR_FAILED (-2) loading 'https://mycompany.com/adfs/ls/idpinitiatedsignon?loginToRp=urn:amazon:webservices'
```

and log in had no effect.

I can debug more, but I have no idea how this works tbh 😄 But if want, reach me on slack, and we can have a call and investigate it live if that would be helpful?

**Comment by urz9999** [comment]
Thanks :) I'll check it today with an internal setup so I can reach both of you ASAP with some news about this!

**Comment by mholttech** [comment]
I put this in slack but I figured I'd also post here. Based on the information @m-radzikowski provided they are actually using Microsoft ADFS to authenticate which is different from AzureAD

**Comment by urz9999** [comment]
Hi @TamerElfeky we currently pushed a possible fix for your problem with commit 4f5739ea90ae63e994a46cd839dd1cac8380679b

You can clone and test it yourself, we plan to make another release real soon with some quality fixes including this one.

Note: To make it work you need another IDP URL from the Azure console, please refer to the attached screen. In Properties, inside your Enterprise Application, the User access URL.

@m-radzikowski if you have any problem regarding ADFS, please open another issue so we can keep track of it separately (as we need to investigate another filter).

![Screenshot 2021-11-30 at 17 01 49](https://user-images.githubusercontent.com/9497292/144083670-4179380a-3cf0-49ad-8b80-26e59d1c73f9.png)

**Comment by m-radzikowski** [comment]
Sorry, I'm only using this auth flow and I'm not an expert in terms of AD, ADFS, etc. Created #200.

**Comment by ericvilla** [comment]
Hi to everyone in this discussion! Starting from @TamerElfeky issue, I think it is not related to a Leapp misbehavior but to the fact that it expects the **User access URL** to be specified during IAM Role Federated creation. The URL that you've specified - that ends with **/saml** - is used during the authentication process, but it is not the starting point. Please let us know if it works with the suggested URL, so that we can decide whether to close the issue or to further investigate it. Thank you!

**Comment by TamerElfeky** [comment]
@ericvilla  yes , using the suggested **user access url** working for me , resolved for me 

```
https://myapps.microsoft.com/signin/<app-id>
```

will be good if we add simple doc for azureAD

**Comment by ericvilla** [comment]
Yes @TamerElfeky, we'll definitively add a dedicated section in the docs
