### ISSUE TITLE
Cancel connecting

### ISSUE THREAD

**Issue by m-radzikowski** [Noovolari/leapp#199]
**Is your feature request related to a problem? Please describe.**

If the session cannot be activated, because of the wrong configuration of closing the browser window for SSO flow, there is no way to cancel connecting. The session is listed under "active sessions" with a spinner in the status column. You can't re-connect (in case of accidentally closed SSO login window).

**Describe the solution you'd like**

Click the session again to cancel connecting.

**Describe alternatives you've considered**

Closing the Leapp and reopening it.

**Comment by ericvilla** [comment]
Thank you for reporting @m-radzikowski 

I think we've to find a way to properly undo connections that are not working for many reasons. It does not regard only AWS SSO sessions, but Leapp sessions in general

**Comment by m-radzikowski** [comment]
Sure, it was just an example 👍

**Comment by ericvilla** [comment]
This enhancement issue is covered in the last [release](https://www.leapp.cloud/releases)! I'm going to close it
