### ISSUE TITLE
Support ADFS federated login for AWS

### ISSUE THREAD

**Issue by m-radzikowski** [Noovolari/leapp#200]
**Is your feature request related to a problem? Please describe.**

My client is using ADFS for federated login, including AWS. While this is SAML integration, Leapp does not work with it. Right now, I have to use custom python script to get CLI access and have to re-run it every hour when credentials expire...

**Describe the solution you'd like**

Allow configuring ADFS authorization as AWS IAM Role Federated.

**Additional context**

To access web Console, I go to custom page to log in and it redirects me to https://signin.aws.amazon.com/saml where I have a list of available roles to choose.

In Leapp I tried to add AWS -> IAM Role Federated and provide:

- Role ARN: the role I’m assuming at the end, let’s say `arn:aws:iam::123456789012:role/Admin`
- SAML 2.0 Url: the custom URL that redirects me to AWS SAML after authorization, something like https://mycompany.com/adfs/ls/idpinitiatedsignon?loginToRp=urn:amazon:webservices
- AWS Identity Provider ARN: the trusted entity value from the role I’m assuming, let’s say `arn:aws:iam::123456789012:saml-provider/AD`

but when choosing this session in Leapp it only spins, I’m not getting any error.

The SAML URL is in the format: https://mycompany.com/adfs/ls/idpinitiatedsignon?loginToRp=urn:amazon:webservices which seems to be a standard thing (https://aws.amazon.com/blogs/security/how-to-implement-federated-api-and-cli-access-using-saml-2-0-and-ad-fs/).

Right now, the logic in Leapp code for SAML auth https://github.com/Noovolari/leapp/blob/6128f90b6b720788d444d6d6ca78504106851129/src/app/services/session/aws/methods/aws-iam-role-federated.service.ts#L176

is filtering out SAML URLs and allows only a few standard URLs, as far as I understand. Since ADFS can use any custom domain, I guess something like `*/adfs/ls/idpinitiatedsignon` must be whitelisted and handled.

For test, I added my company domain to the filters list and added 

```ts
if (details.url.indexOf('https://mycompany.com/') !== -1) {
  idpWindow = null;
  resolve(true);
}
```

to `onBeforeRequest` to see what will happen.

As a result, the window opened with mycompany ADFS login page (previously it did not), however, in console I got:

> [21070:1129/231026.361997:INFO:CONSOLE(1072)] "Unhandled Promise rejection: ERR_FAILED (-2) loading 'https://mycompany.com/adfs/ls/idpinitiatedsignon?loginToRp=urn:amazon:webservices' ; Zone: <root> ; Task: null ; Value: Error: ERR_FAILED (-2) loading 'https://mycompany.com/adfs/ls/idpinitiatedsignon?loginToRp=urn:amazon:webservices' Error: ERR_FAILED (-2) loading 'https://mycompany.com/adfs/ls/idpinitiatedsignon?loginToRp=urn:amazon:webservices'
and log in had no effect.

So something more needs to be done. I'm not knowledgeable enough about AD / ADFS / SAML to know what 🤷‍♂️

**Comment by pethron** [comment]
Thanks, @m-radzikowski, for gathering all this data! Our main issue for this is getting up and running an ADFS to test this behavior. If someone has more insight into how ADFS works, we can sort this out pretty quickly.

**Comment by peteawood** [comment]
Making this change works for me. I followed the same steps as @m-radzikowski although was maybe less explicit with the filter:

```TypeScript
const filter = {
        urls: [
          'https://*.onelogin.com/*',
          'https://*/adfs/ls/idpinitiatedsignon.aspx?loginToRp=urn:amazon:webservices',
          'https://*.okta.com/*',
          'https://accounts.google.com/ServiceLogin*',
          'https://login.microsoftonline.com/*',
          'https://signin.aws.amazon.com/saml'
        ]
      };
```

and

```TypeScript
// ADFS
if (details.url.indexOf('adfs/ls/idpinitiatedsignon.aspx?loginToRp=urn:amazon:webservices') !== -1) {
  idpWindow = null;
  resolve(true);
}
```

This opened the window (which it did not do before), I selected the appropriate provider, the window closed and the session connected.

**Comment by m-radzikowski** [comment]
I tried to do this again. For some reason, the `onBeforeRequest` is never executed now, even when I removed the `filters` parameter or added a filter like `*://*/*`. This is also true for other URLs - I've added some debug logs, and everything is executed apart from the `onBeforeRequest` 🤷‍♂️ The window never opens.

The `onBeforeRequest` is executed on the production app. So this is something with dev app, maybe on macOS?

At the same time I can't build production app because I'm getting size errors:

```
Warning: bundle initial exceeded maximum budget. Budget 2.00 MB was not met by 3.14 MB with a total of 5.14 MB.
Error: bundle initial exceeded maximum budget. Budget 5.00 MB was not met by 146.84 kB with a total of 5.14 MB.
```

while I only added few log lines.

Anyway, I can try it later on Linux. Otherwise, if that works for you @peteawood , maybe you would be willing to raise a PR with this change? One small detail is that it would be nice to support both `idpinitiatedsignon.aspx` and `idpinitiatedsignon` (without `.aspx`) in the address, as both are valid.

**Comment by peteawood** [comment]
Regarding PR - sure, no problem. Whilst this may work for later versions/another OS, I can only guarantee this works for ADFS 2.0 from a Windows 10 OS client and any documentation should state as much. 

Additionally - are you able to try your company domain ADFS in the browser with .aspx present? I only ask as I can't see anywhere in the [documentation ](https://docs.microsoft.com/en-us/previous-versions/adfs-2.0/ee895361(v=msdn.10)?redirectedfrom=MSDN) where the extension-less option is expected as a standard. If adding .aspx still works for you in the browser, I would suggest only matching on this.

**Comment by m-radzikowski** [comment]
> Regarding PR - sure, no problem.

❤️ 

> Additionally - are you able to try your company domain ADFS in the browser with .aspx present?

Yes. Both formats, with and without `.aspx` work for me. Just the version without the extension is provided by company devops team as login URL.

I guess it's fairly common in .NET to "beautify" URLs by rewriting them if they do not have the extension.

Since people will put the URL in the format they receive from someone else, and there is a huge chance of both the formats to be used, I think it will be nice to support them both. Otherwise people will have troubles investigating what's wrong with their URL, since it works perfectly fine in the browser.

**Comment by peteawood** [comment]
PR added as #235 but as a first time contributor I need a maintainer to approve the workflow 😁

**Comment by marcojahn** [comment]
I would like to ask if there might be away of allowing "custom" urls added via some "settings" instead of adding them all manually ?
I've added "my customers custom URL" like in #235 but it might be not a good idea of having to add customer specific urls directly in the code.

My customers URL format ist `https://sso2fa.service.COMPANYNAME.com/aws`

I've added the custom url as an IDP Url in the appropriate UI settings and it might be an idea to use these URLs als "dynamic" filter options to behave like #235 and show me the custom 2fa login dialog ?

My current workaround ist to checkout leapp, patching it and starting it using `npm run build-and-run-dev` what is ok for now :)

**Comment by ericvilla** [comment]
Hi @marcojahn, that's a great idea and we've already thought about it!

As you can see from the codebase, each supported SAML IdP comes with a filter (e.g. `https://\*.onelogin.com/\*`) and a condition on the filtered URL (e.g. `if (details.url.indexOf('.onelogin.com/login') !== -1) {`).

Both *filter* and *condition* are used to understand if authentication is needed; if they are bypassed - the user is redirected to `https://signin.aws.amazon.com/saml` - it means the user is already logged in.

The previously described logic is implemented by the aws-iam-role-federated.service's needAuthentication method.

If authentication is required, a new Electron BrowserWindow will be opened to let the user authenticate against the SAML IdP. As you can see in the aws-iam-role-federated.service's awsSignIn method, a `https://signin.aws.amazon.com/saml` filter is added; it allows to grab the successful login response, i.e. the one that contains the SAML Assertion.

The SAML assertion is then used to perform the `aws sts assume-role-with-saml` call.

I have described the whole process to point out that needAuthentication is the method that needs to be generalized (as you suggested).

I think we could extract the concept of SAML IdP from the AwsIamRoleFederatedService by encapsulating the filter and condition logic described above. Moreover, as for AWS SSO integration, we could cache the SAML Assertion - grabbed from the successful login response - in the System Vault (e.g. macOS Keychain).

Let me know what you think about it?

PS: it opens a scenario where people can propose their SAML IdP objects as PRs

**Comment by marcojahn** [comment]
Hi @ericvilla,

not sure if proposed solution might get to complicated for "my" simple use case and violates the constraint that I am not allowed to share that URL using a PR to this project (but I am aware that I don't know all use cases!)
But as a general solution it seems to be the right way :D

But i would recommend to keep one "feature" in mind:
Companies/Users would not want to "share" their "Pre Login" Urls with the "world" (I have to count me in here)
Therefore a "local only" (aka settings/options dialog) solution to add URLs that need that kind of pre login would be a nice way instead of making PRs.

I must admit I am not as familar with the code base as needed to make the changes but will be willing to help as best as I can, so please let me know
