### ISSUE TITLE
Support AWS IAM User access with U2F MFA

### ISSUE THREAD

**Issue by m-radzikowski** [Noovolari/leapp#201]
**Is your feature request related to a problem? Please describe.**

IAM user can have MFA auth with either virtual method (code generated by app like Authy) or U2F key (like YubiKey). Code is supported, U2F key not.

#135 was about supporting U2F key when authorizing through SSO. This ticket is to support IAM User authentication with a physical key.

**Describe the solution you'd like**

If U2F is configured as MFA, ask to touch key for MFA.

**Comment by andreacavagna01** [comment]
Sadly not possible, there is not any API for doing this, we check this out the last week, closing because it isn't possible at the moment

**Comment by all4innov** [comment]
@andreacavagna01 hello, can we open this as now AWS can support the Security Key (eg yubikey/fido)

**Comment by m-radzikowski** [comment]
@all4innov AWS always supported security keys, that's nothing new. What's new from AWS they now support **multiple** MFA devices, but this doesn't change the issue here, I guess.

**Comment by all4innov** [comment]
@m-radzikowski inline and this is the recent announcement : https://aws.amazon.com/fr/blogs/security/you-can-now-assign-multiple-mfa-devices-in-iam/
The main point is about supporting a FIDO Security key (not HW TOTP) withing Leapp. 
If already supported then please any support/link/doc of how to make it working ? else any issue ID to follow (this to reopen or any other one) ?

**Comment by m-radzikowski** [comment]
MFA devices, like FIDO keys, were already supported by AWS. This recent announcement is about supporting multiple keys - until now, you could add only a single one per IAM user. Now you can add multiple.

FIDO keys were never supported by Leapp. I've created this issue to ask for supporting them, @andreacavagna01 did research concluding this is not possible. I don't think anything changed on that front - just like it was not possible to support a single U2F key, it's not possible to support multiple ones.
