### ISSUE TITLE
On upgrade to 0.8.0, all sessions reverted to "default" profile

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#202]
**Describe the bug**
Upgrading Leapp caused all configured sessions to change to "default" named profile.

**Expected behavior**
Upgrade should not change existing settings

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 10.1
 - OS Version [e.g. 22]  10.15.7
 - Leapp Version [e.g. 0.2.5] 0.7.4 upgraded to 0.8.0

**Comment by urz9999** [comment]
Thanks, @Nuru will check the retro compatibility service to address this issue.

**Comment by Nuru** [comment]
Please let me know if you have a workaround for this. I'm stuck on version 0.7.4 until then.

**Comment by hustvedt** [comment]
This also occurs when logging out of the integration, which is a frequent thing due to #220 .

**Comment by ericvilla** [comment]
@hustvedt thank you for reporting. These are two different issues. 

- With 0.8.1 version we solved a bug that caused every AWS SSO session to be reset upon sync (automatic provisioning of AWS SSO sessions based on online access information). 

- As described [here](https://github.com/Noovolari/leapp/issues/108), we've to introduce a try/catch logic that triggers browser login if the expiration token is expired. Currently token expiration is stored in Leapp configuration, but this information is no more coherent as soon as you log out from the AWS Console (during an AWS SSO session)

We need to find a way, for those who are in stuck in a lower version than 0.8.0, to migrate the configuration without resetting the underlying sessions

**Comment by ericvilla** [comment]
In [this](https://github.com/Noovolari/leapp/commit/dbff233f7a94ad1062fe8f01b60cdabfba6b1d09) commit we fixed the bug that reset sessions' profiles to default.
We are going to introduce this fix in the next release!

**Comment by ericvilla** [comment]
As stated in the last comment, this issue is solved. I'm going to close this issue as a new v0.10.0 version of Leapp is available
