### ISSUE TITLE
Add grouping and/or prefix on integration name for session overview

### ISSUE THREAD

**Issue by Osterjour** [Noovolari/leapp#203]
When you have multiple integrations (in my case multiple AWS SSO integrations) the session list is only using the account names based on how they're provided by AWS SSO. If you now have account names like "dev", "prod", "stage" in multiple different AWS SSO organizations there is no differentiation anymore.
It would be nice to have a grouping by integration name that can be enabled or at least have a Prefix/Label with the integration name visible in the session overview to distinguish the different accounts, Combined with the feature request of a sorting functionality (https://github.com/Noovolari/leapp/issues/58) that would highly increase the UX and usability in my opinion!

**Comment by urz9999** [comment]
Hi, @Osterjour thanks for your suggestion! We are currently working on a major overhaul of Leapp's interface that will address most of the common issues with the user experience, in the meantime we are also working on a series of QoL fixes that will be released soon including adding a quick identifier in the session list for the integration name. Stay tuned!

**Comment by ericvilla** [comment]
This enhancement issue is covered in the last [release](https://www.leapp.cloud/releases)! I'm going to close it
