### ISSUE TITLE
White screen on MacOS Monetary 12.0.1

### ISSUE THREAD

**Issue by max-blue** [Noovolari/leapp#206]
**Describe the bug**
Installing the latest version of leapp and launching it shows a white screen. I have to force quit the app to launch it again. Same white screen after launching it. 

**Leapp Version**
0.80.0

**To Reproduce**
1. Install the latest version of the app 
2. launch the app 
3. you will see white screen 

**Expected behavior**
The app should launch correctly allowing you to setup credentials for AWS

**Screenshots**
![image](https://user-images.githubusercontent.com/95645675/145142808-b602657b-f3bb-4476-a8b0-715078143f27.png)
![image](https://user-images.githubusercontent.com/95645675/145142865-9550f21e-654d-4930-b08e-6659161fec2c.png)

**Desktop (please complete the following information):**
 - OS: MacOS 
 - OS Version 12.0.1
 - Leapp Version 0.80.0

**Comment by pethron** [comment]
Thanks for reporting @max-blue , can you please attach the logs? In MacOs they should be at this path: ~/Library/Logs/Leapp/log.log

Also your mac is using the M1 chipset?

**Comment by ericvilla** [comment]
Hi @max-blue!

Is v0.8.0 your first installation of Leapp? If not, I think this problem is related to a retrocompatibility issue regarding the configuration file. Just to try it out, please create a backup copy of your configuration file, placed under **~/.Leapp/Leapp-lock.json**. Then, try to quit and run the application again; I think it could solve the issue. Let me know if it works

**Comment by max-blue** [comment]
> Thanks for reporting @max-blue , can you please attach the logs? In MacOs they should be at this path: ~/Library/Logs/Leapp/log.log
> 
> Also your mac is using the M1 chipset?

Hi there @pethron 
Yes - my uses the M1 chipset. I did not see a log folder in the path you specified. However @ericvilla suggestion to make a backup copy of  ~/.Leapp/Leapp-lock.json worked. I was looking for this file and I couldn't find last night. 

Thanks both for support!

**Comment by pethron** [comment]
If you're ok with this, I'll close the issue. Feel free to reopen if needed!
