### ISSUE TITLE
Accessibility/nitpick:  pressing "enter" after entering a MFA token does not submit the token

### ISSUE THREAD

**Issue by jcogilvie** [Noovolari/leapp#207]
**Describe the bug**
I get a prompt for an MFA token inside Leapp.  When I enter the token, I instinctively press "enter" to submit it.  But nothing happens and instead I have to click the button.

**Leapp Version**
0.8.0

**To Reproduce**
1. Click on a profile that requires MFA
2. Enter MFA code
3. Press "enter" (or "return")
4. Observe that nothing happens

**Expected behavior**
I expect the code to be submitted.

**Desktop (please complete the following information):**
 - OS: OSX
 - OS Version 11.6
 - Leapp Version 0.8.0

**Comment by pethron** [comment]
Thanks for the suggestion, we'll see what we can do about it for sure.

**Comment by mdourmouch** [comment]
I would also suggest to auto focus the cursor to the MFA textbox

**Comment by m-radzikowski** [comment]
Enter works good in 0.10.0 👍  I think this may be closed now.
