### ISSUE TITLE
UI cuts the last part of the latest item in the credentials list

### ISSUE THREAD

**Issue by Pymatteo** [Noovolari/leapp#21]
## Description

On ubuntu the UI cuts the last part of the latest item in the credentials list

## Additional Context

![image](https://user-images.githubusercontent.com/16803060/95088259-01c6fd00-0723-11eb-98be-f61c51e58ed2.png)

**Comment by urz9999** [comment]
solved in commit 3f6835e - expected in patch 0.2.4
