### ISSUE TITLE
Leapp Open with Blank window

### ISSUE THREAD

**Issue by pmpavlov** [Noovolari/leapp#210]
Hi recently updated the Leapp and a few days after the update opening it it shows me Blank window and the app is not opining . 
I dont see anything . When I run the debug I see only one js script is failing . I have delete and reinstalled the app several times . 
<img width="626" alt="Screenshot 2022-01-13 at 10 50 27" src="https://user-images.githubusercontent.com/2073978/149316591-a1ab1acf-9e82-4109-a64a-91e2a1979a5d.png">

**Comment by andreacavagna01** [comment]
from which version you have switched? 

It is for sure a retro compatibility problem, you can delete the files inside the `.Leapp` folder in your main directory, this will solve your problems at least.

Thank you.

This solution sadly will delete all the previously created sessions.

From the latest releases a new retro compatibility system has been added

**Comment by andreacavagna01** [comment]
Is this issue solved @pmpavlov?

**Comment by zswanson** [comment]
I've been seeing a similar issue sporadically after updating to 0.8.1. Not only is it blank, but I can't kill the window and have to  grep the process tree to force kill it.

**Comment by andreacavagna01** [comment]
closing because it's an old issues
