### ISSUE TITLE
Enhancement - easier access to commonly used profiles

### ISSUE THREAD

**Issue by tgjohnst** [Noovolari/leapp#214]
**Is your feature request related to a problem? Please describe.**
Many devs have a specific session that is used most often for day to day work, with others available for specific purposes or access to compartmentalized resources. With many roles/sessions/accounts available, it can be cumbersome to sort through the list to find that commonly used profile every day when logging in.

**Describe the solution you'd like**
A simple enhancement to improve user experience would be to add the ability to "star" or "favorite" certain sessions and have those starred sessions appear at the top of the list for quicker access.

**Describe alternatives you've considered**
The ability to sort sessions by most recently used would also solve this problem without introducing new UI elements.

**Comment by pethron** [comment]
Thanks for the suggestion, we're pretty aware of the current problem in navigation, and we've already been implementing it in the new UX/UI (coming forth in the next month or so). I'll leave it open until release as a reminder

**Comment by ericvilla** [comment]
This enhancement issue is covered in the last [release](https://www.leapp.cloud/releases)! I'm going to close it

**Comment by ericvilla** [comment]
This enhancement issue is covered in the last [release](https://www.leapp.cloud/releases)! I'm going to close it
