### ISSUE TITLE
gpu_init on WSL2 - Leapp_0.8.1_amd64.deb

### ISSUE THREAD

**Issue by rjackson-dev-ops** [Noovolari/leapp#217]
**Describe the bug**

rjackson@RJACK-SERVER:Downloads$ leapp
Checking for update
[12462:0130/194136.347577:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is
rjackson@RJACK-SERVER:Downloads$ Checking for update

**Leapp Version**
Leapp_0.8.1_amd64.deb

**To Reproduce**
1. Install on WSL2 Unbuntu
2. Launch Leapp

**Expected behavior**
clean launch

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10, WSL2 Ubuntu 18

**Additional context**

**Comment by rjackson-dev-ops** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> rjackson@RJACK-SERVER:Downloads$ leapp Checking for update [12462:0130/194136.347577:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is rjackson@RJACK-SERVER:Downloads$ Checking for update
> 
> **Leapp Version** Leapp_0.8.1_amd64.deb
> 
> **To Reproduce**
> 
>     1. Install on WSL2 Unbuntu
> 
>     2. Launch Leapp
> 
> 
> **Expected behavior** clean launch
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [e.g. iOS] Windows 10, WSL2 Ubuntu 18
> 
> 
> **Additional context** Add any other context about the problem here.

This looks like "user" error.

I apparently had the old version running while trying to start a new version.

After killing the old process, it's launching.

**Comment by andreacavagna01** [comment]
Hi thanks for the contribution, this is a well-known flow. Having 2 different apps working at the same time will cause a concurrency problem so it's is not possible to have 2 different Leapp apps open at the same time.

I'm going to close the issue
