### ISSUE TITLE
Tray icons are low res/pixelated

### ISSUE THREAD

**Issue by connorads** [Noovolari/leapp#218]
**Is your feature request related to a problem? Please describe.**
Very minor but the Leapp icons in the tray are low res compared to other apps' icons.
You can't even really tell from my screenshot because of compression 😅
But I can assure you that the Leapp logo and house icons are pixelated compared with the other icons like Google Drive
![image](https://user-images.githubusercontent.com/10026538/151832230-d789eb29-60c5-4df7-b2a6-4b749175c4d2.png)

**Describe the solution you'd like**
Not familiar with desktop development but I imagine you would use some sort of high res or vector graphic for the icons

**Additional context**
I'm using a 4k screen with 1920 x 1080 scaling mode
![image](https://user-images.githubusercontent.com/10026538/151833105-b5ef4190-fffe-4b49-b643-cc516ed97fdb.png)

**Comment by andreacavagna01** [comment]
Thanks! we are testing the new UX/UI release and this will be fixed.

Also a new Logo is coming too 💯

**Comment by connorads** [comment]
Fixed in https://github.com/Noovolari/leapp/releases/tag/v0.9.0 🚀
