### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by gshpychka** [Noovolari/leapp#221]
**Describe the solution you'd like**
Are there plans to host the app in the archlinux AUR for easy installation?  It would make updating a lot easier. 

**Describe alternatives you've considered**
Currently, I create `pacman` packages from the `.deb` releases manually, this makes updating Leapp a chore and disjointed from the way I update every other package on my machine.

**Additional context**
I saw that it existed at https://aur.archlinux.org/packages/leapp, but it's been removed.

**Comment by andreacavagna01** [comment]
Hi thanks for reporting. No there is not a plan for the archlinux support at the moment in roadmap.
I see that exist a package of Leapp [here](https://aur.archlinux.org/leapp-bin.git) but this is not maintained by the maintainers of the project. So I cannot grant you the stability of it.

If you know how to host the app with archlinux and want to contribute, please feel free to join the community and I will help you in doing it

**Comment by gshpychka** [comment]
>I see that exist a package of Leapp [here](https://aur.archlinux.org/leapp-bin.git) but this is not maintained by the maintainers of the project. So I cannot grant you the stability of it.

That link gives me 404.

>If you know how to host the app with archlinux and want to contribute, please feel free to join the community and I will help you in doing it

It should be straightforward, I'll message you when I can spare the time.

**Comment by andreacavagna01** [comment]
Thank you!

**Comment by gshpychka** [comment]
https://aur.archlinux.org/packages/leapp-bin seems to be well maintained
