### ISSUE TITLE
Dark mode UI

### ISSUE THREAD

**Issue by nitrocode** [Noovolari/leapp#224]
**Is your feature request related to a problem? Please describe.**
The white background hurts my eyes and my screen

**Describe the solution you'd like**
It would be nice to have the Leapp UI use Dark mode or rather respect the system UI preferences on mac/windows/linux

**Describe alternatives you've considered**
Quickly look at Leapp, login, and minimize it

**Additional context**
N/A

**Comment by pethron** [comment]
Thanks for the feedback. It could be a great addition! I went and added to the [portal roadmap!](https://roadmap.leapp.cloud/tabs/1-under-consideration), but I took the liberty to put it already under consideration

**Comment by ericvilla** [comment]
The dark side of the Leapp is now supported in v0.10.0!
