### ISSUE TITLE
Installation URL in readme is broken

### ISSUE THREAD

**Issue by dnsmichi** [Noovolari/leapp#227]
**Describe the bug**

https://github.com/Noovolari/leapp#download points to https://docs.leapp.cloud/installation/install-leapp/ which returns 404.

The documentation uses versioned docs, with the version in the URL. Example: `https://docs.leapp.cloud/0.9.0/installation/install-leapp/` 

It seems this was introduced with https://github.com/Noovolari/leapp/commit/fa48565f3ecf4a514b9b0f6ece7d3f5b7b86eb4a - there is no PR describing the full change. Suggest making changes with PRs, and avoid pushing to the main branch directly :)

**Suggested solution**

- Add a docs version with `latest` which redirects to the recent version
- Deployment CI/CD jobs should test the most important URLs for reachability (or use online monitoring tools to check the website)

**Comment by andreacavagna01** [comment]
Fixed, we switched to the version of the documentation in this release
