### ISSUE TITLE
Add region selector for the active session

### ISSUE THREAD

**Issue by gando91** [Noovolari/leapp#23]
**Is your feature request related to a problem? Please describe.**
Users should be able to change the "default region" at any time for a specific session.

**Describe the solution you'd like**
We already have a region setting, it would be perfect if this setting would be used as a default on each session start.
Users should be able to switch region for the current session using a simple selector. The selector should reset to the "default region" for the account when changing the session.

**Comment by NicoloniFerro** [comment]
+1

**Comment by mdourmouch** [comment]
+1

**Comment by damianogiorgi** [comment]
+1

**Comment by andreafranzoso** [comment]
+1

**Comment by andreacavagna01** [comment]
By now, we are supporting a default, per session, region selector.
in the 0.4 release, we are thinking to add a selector in App to easy switch between AWS or Azure regions.

So you can have a default, per session region, and a selector to switch between them in a click.
Is that what are you looking for?

**Comment by pethron** [comment]
I think this needs further discussion. It's ok to have a general selector for the current session, but how it should behave when switching between profiles? The region remains the same or override the current region with the one defined in the specific profile?

**Comment by andreacavagna01** [comment]
Added in version v0.4.3
