### ISSUE TITLE
0.9.0 allow view and edit of session config after creation

### ISSUE THREAD

**Issue by zswanson** [Noovolari/leapp#230]
**Is your feature request related to a problem? Please describe.**
In the new 0.9.0 UI we can't edit anything in an AWS Federated Session once you hit save. If a user makes a mistake in a role name or account number etc there is no way to update the config except deleting and trying again. Its also difficult to help other team members because once the config is saved we can't even see the details.

**Describe the solution you'd like**
Allow view and edit function of the configuration after its created

**Describe alternatives you've considered**
Only workaround right now is to delete and create again

**Additional context**
Using version 0.9.0

**Comment by andreacavagna01** [comment]
Yeah, I think edit will be a great addition and also easy to implement, will add it in the requests

**Comment by jonasoneves** [comment]
Solved in [v0.12.0](https://github.com/Noovolari/leapp/releases/tag/v0.12.0) release

**Comment by m-radzikowski** [comment]
@andreacavagna01 / @zswanson  I think this can be closed now?
