### ISSUE TITLE
0.9.0 clicking outside the session create modal cancels the action

### ISSUE THREAD

**Issue by zswanson** [Noovolari/leapp#231]
**Describe the bug**
When creating a new session if the user mistakenly clicks anywhere outside the modal in the main leapp window the configuration action is totally canceled and the user has to start over providing the information again. Note - clicking on the top application bar (where the 'search session' box appears) does NOT exhibit this behavior.

**Leapp Version**
Add the version of your Leapp (you can find it under taskbar -> about or Leapp -> about on MacOS X)

**To Reproduce**
1. Go to Add New Session (+ icon in main panel)
2. Click on Amazon AWS. Config modal for Amazon AWS session appears.
3. Click mouse anywhere on the main panel that is now 'grayed out' behind the modal.
4.  AWS config panel is removed, any details are not saved.

**Expected behavior**
Since this popup panel has a 'cancel' and 'X' button to close the window I would expect it to stay 'on top' and not close if someone clicks outside the area.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version 12.2.1 (21D62)
 - Leapp Version 0.9.0

**Additional context**
Clicking on the top application bar (where the 'search session' box appears) does NOT exhibit this behavior, seems to be isolated to the other panels in the application.

**Comment by pethron** [comment]
We'll research standard UX practices, but I think you are right and should be pretty easy to add. Coupling what you're saying with the need to usually click outside of leapp to get the data needed can result in problems. Thanks for reporting!

**Comment by zswanson** [comment]
Yup thats basically how I found this. Switched over to chrome to grab a role arn and copy it to leapp, when I clicked into leapp I wasn't in the 'modal' part of the session creation and it closed.

**Comment by m-radzikowski** [comment]
In 0.12.0 clicking outside the modal no longer closes the popup.

@pethron / @zswanson I think this issue can be closed now?
