### ISSUE TITLE
Build for ARM (Apple M1) architecture

### ISSUE THREAD

**Issue by jodok** [Noovolari/leapp#233]
**Is your feature request related to a problem? Please describe.**
Leapp uses more CPU power, battery than necessary because it is not yet compiled for M1/ARM architecture and using the rosetta emulation layer on OS X.

**Describe the solution you'd like**
Provide a build/dmg that supports both, intel and arm architecture.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by pethron** [comment]
Thanks for reporting. We're planning to support M1, but we had a few problems compiling with keytar, so we're currently investigating this.

**Comment by nwouda** [comment]
I've been able to compile it for M1 without big issues. I just changed to the latest nodejs 16 release (which is built for m1).
