### ISSUE TITLE
AWS SSO Integration not working with GovCloud

### ISSUE THREAD

**Issue by lorengordon** [Noovolari/leapp#239]
**Describe the bug**

AWS SSO is available in GovCloud, but the start URLs are different than in Commercial regions. For example:

```
https://start.us-gov-west-1.us-gov-home.awsapps.com/directory/<directory-alias-or-id>
```

When attempting to configure an AWS SSO integration in Leapp for an instance in GovCloud, I get an error, "Error during SSO Login. Invalid SSO URL". But it's definitely valid, so I am guessing Leapp is parsing the URL and doing some validation, and just isn't aware of how the URL is structured in GovCloud.

**Leapp Version**
Leapp v0.10.0

**Screenshots**

<img width="402" alt="image" src="https://user-images.githubusercontent.com/8457307/157703367-909b0d35-cede-437a-805a-c9c9de8ebd4b.png">

**Comment by andreacavagna01** [comment]
Hi have you tried to use the portal url that ends with `/start` for the AWS SSO in cloud gov. At the moment i have not AWS Single Sign-On to try if there is some problem but I will look at it deeply soon!

Thanks for the contribution

**Comment by lorengordon** [comment]
Unfortunately, no logs are generated when I attempt to sign in to the Govcloud SSO integration.

There is no portal url in Govcloud AWS SSO that ends with /start. As the doc you linked mentioned, the portal url in Govcloud has the format:

* `https://start.us-gov-home.awsapps.com/directory/<IdentityStoreId>` or
* `https://start.us-gov-home.awsapps.com/directory/<CustomAlias>`

>Hi have you tried to use the portal url that ends with /start for the AWS SSO in cloud gov.

**Comment by andreacavagna01** [comment]
This should be solved now with v.0.16.0. I can close the issue now. Feel free to re-open the issue if the problem persists.

If there are some problem please provide us additional logs with the new version installed
