### ISSUE TITLE
The quick list only shows the current section and the last ADDED not USED accounts

### ISSUE THREAD

**Issue by Pymatteo** [Noovolari/leapp#24]
**Describe the bug**
The quick list only shows the current section and the last ADDED not USED accounts. 

**To Reproduce**
1. Add a few accounts to Leapp (e.g. 10)
2. start a session in the first inserted account
3. Open the quick list in notification bar: you see the current session marked and the latest added accounts
4. start a new session with the second added account
5. open again the quick list and the previous session is gone: you just have the current session marked and the four latest added ADDED accounts

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by urz9999** [comment]
Solved waiting for release 0.3.0 to be added.

**Comment by Pymatteo** [comment]
We still have the issue, if i change the account by using the dropdown the history his deleted
