### ISSUE TITLE
Leapp v0.11.0 Install Error: "session-manager"

### ISSUE THREAD

**Issue by kbakeradi** [Noovolari/leapp#245]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When installing the new Leapp v0.11.0, I got the attached error.

<img width="437" alt="error" src="https://user-images.githubusercontent.com/101585925/161080723-585b8348-bb41-44ce-8999-ffc877a22dc9.png">

To fix it I just needed to install the AWS session-manager on my machine.

> [Install the Session Manager plugin on macOS with the signed installer](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html#install-plugin-macos-signed )

### Details:
| Leapp Version | 0.11.0 |
| - | - |
| SsmPluginVersion | undefined |
| Platform | darwin|
| Awscli | aws-cli/2.4.15 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off

**Comment by andreacavagna01** [comment]
A try catch is missing, this should only be a check if it is installed. we will fix it

Thanks for the feedback

**Comment by Nuru** [comment]
Similar but slightly different error in v0.11.1:

![image](https://user-images.githubusercontent.com/2793313/164799919-9c6df550-17a8-4a7c-b33c-ebb28738d87a.png)

**Comment by m-radzikowski** [comment]
A little bit annoying to have this every time you launch Leapp, since I have no intention to access EC2 machines.

**Comment by Nuru** [comment]
Similar issue remains in v0.12.0

**Comment by fancywriter** [comment]
Seeing the same picture for 0.13.1. What should I do to fix it?
![image](https://user-images.githubusercontent.com/1200256/179741124-cc1b5597-d49a-431a-a72c-03559df22036.png)

**Comment by andreacavagna01** [comment]
install the session manager plugin by now, in the next release we will fix this, thanks for pointing It out

**Comment by pethron** [comment]
@fancywriter, here's the official AWS documentation:
https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html

**Comment by fancywriter** [comment]
@pethron great, would be nice to see this link (better clickable) in this warning.

**Comment by pethron** [comment]
Yeah, I was thinking the same! To better understand, I think we'll add a section in the docs and redirect there

**Comment by andreacavagna01** [comment]
close due to inactivity

**Comment by andreacavagna01** [comment]
Fixed in v0.14.2
