### ISSUE TITLE
v0.11.0 session-manager-plugin missing

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#249]
### Description:
While running version 0.10.0 I got the upgrade notice but Leapp froze (I believe there is a bug involving MFA expiring while the computer is asleep, but that would be a separate issue once I can narrow it down) so I had to quit (not force quit) it from Activity Monitor. I then downloaded v0.11.0 from [the website](https://asset.noovolari.com/latest/Leapp-0.11.0-mac.zip) and installed it the usual way. Now when it starts, I get this error message:

![image](https://user-images.githubusercontent.com/2793313/161124067-066a0cd1-120f-4b9d-a2e2-dda4db6b3414.png)

### Details:
| Leapp Version | 0.11.0 |
| - | - |
| SsmPluginVersion | undefined |
| Platform | darwin|
| Awscli | aws-cli/2.4.18 Python/3.9.10 Darwin/20.6.0 source/x86_64 prompt/off

**Comment by ericvilla** [comment]
Thank you @Nuru for reporting this issue! We already managed to resolve it. You will receive a more user-friendly message using the next Leapp version

**Comment by andreacavagna01** [comment]
I think no message should appear, it should only inform you when opening an issue, that no plugin of AWS SSM is installed

**Comment by ericvilla** [comment]
This issue is linked to #245

**Comment by Plasma** [comment]
I'm receiving this error too, but SSO works fine -- Its not clear also how to resolve it, what is it asking me to do? Thank you

**Comment by ericvilla** [comment]
I'm going to close this issue due to inactivity
