### ISSUE TITLE
SSM session list is not properly formatted

### ISSUE THREAD

**Issue by NicoloniFerro** [Noovolari/leapp#25]
**Describe the bug**
The string list in the SSM session tab is unformatted. Buttons are pushed to the next line.

**To Reproduce**
1. Start an active session
2. Click on SSM session

**Expected behavior**
I expect to have a short view of the name of the EC2 (and it's IP) with a tooltip with the entire one.

**Screenshots**
 
![Screenshot 2020-10-08 at 16 06 14](https://user-images.githubusercontent.com/47815721/95469837-5e732380-0980-11eb-934c-571c4afc16e7.png)

**Comment by ericvilla** [comment]
Thank you @NicoloniFerro, we will fix this issue asap. Is this the latest version, i.e. 0.2.4?
