### ISSUE TITLE
Install CLI tool without NPM

### ISSUE THREAD

**Issue by Gowiem** [Noovolari/leapp#250]
**Is your feature request related to a problem? Please describe.**

Installing the CLI tool via NPM seems wrong -- if I install the GUI then I would expect the CLI installed alongside that. I shouldn't have to have NPM installed to use the Leapp CLI. 

**Describe the solution you'd like**

Either of the following: 

1. The CLI is installed alongside the GUI application and is automatically added to my PATH by linking it to `/usr/local/bin` or something. 
2. If I must install the CLI separately then I would like the ability to install it with `brew` (or apt-get, yum, or whatever the windows kids use)

**Describe alternatives you've considered**

N/A

**Additional context**

Managing the CLI as an NPM package bugs me 😅

**Comment by andreacavagna01** [comment]
I think it's definetely a good Idea. It's in the roadmap to make CD automatic for the CLI

**Comment by nitrocode** [comment]
I thought the same thing today. I put in this PR to close this issue https://github.com/Homebrew/homebrew-core/pull/103998. I hope it gets accepted soon!

**Comment by nitrocode** [comment]
@Gowiem @andreacavagna01

This can be closed. You can now `brew install leapp-cli`.

**Comment by andreacavagna01** [comment]
absolutely! We are working on the brew arm-64 issues as well but this issue can be closed
