### ISSUE TITLE
No brew for Linux

### ISSUE THREAD

**Issue by carlosleoliveira** [Noovolari/leapp#251]
**Describe the bug**
The installation guide is showing brew to install on Linux, but this option is only available on MacOS.

**Screenshots**
![image](https://user-images.githubusercontent.com/60003832/161863044-e31e4d48-db1c-4459-a9c8-6791b603bc1d.png)

![image](https://user-images.githubusercontent.com/60003832/161863144-dde72553-39f9-43d2-8522-7229a0b34b73.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - OS Version 35

**Comment by pethron** [comment]
You're right; currently, we don't support Leapp on Homebrew for Linux.
We will fix the documentation in the following days, but it would be interesting to know what's needed to make Leapp available to homebrew on Linux.

**Comment by pethron** [comment]
Closing because now it's working on Linux, but not for arm architectures.
We'll update the documentation accordingly, but for now, I'll close the issue.

**Comment by afolarin** [comment]
The CLI page still shows an npm installation. 
https://docs.leapp.cloud/0.23.0/cli/
```
$ npm install -g @noovolari/leapp-cli
$ leapp COMMAND
running command...
$ leapp (--version)
@noovolari/leapp-cli/0.1.53 darwin-x64 node-v16.14.0
$ leapp --help [COMMAND]
USAGE
  $ leapp COMMAND
...
```
It would also be clearer if the installation specifically mentions Linux on the leap-cli installation instruction it mentions Linux for the desktop app, but for the leapp-cli it is not specific, and given most from the Linux world wouldn't by default use brew it would make sense to specifically not that that is required to install on Linux. https://docs.leapp.cloud/0.23.0/installation/install-leapp/
