### ISSUE TITLE
Incorrect requirements?

### ISSUE THREAD

**Issue by jalaziz** [Noovolari/leapp#258]
**Describe the bug**
The [docs say that there are no requirements for Windows or Mac users](https://docs.leapp.cloud/0.11.0/installation/requirements/). However, when launching Leapp for the first time, I was met with two error prompts, one for the AWS CLI and the second for AWS Session Manager Plugin. 

**Leapp Version**
0.11.0

**To Reproduce**
1. Install Leapp on a fresh Mac

**Expected behavior**
Docs should be updated with requirements or Leapp should prompt to install the requirements.

**Desktop (please complete the following information):**
 - macOS 12.3.1
 - Leapp 0.11.0

**Additional context**
This is also related to #257. I discovered the issue because of Leapp failing to find the AWS CLI in the correct location. Once I symlinked to work around the issue, I received the error about AWS Session Manager Plugin (which I didn't have installed).

**Comment by andreacavagna01** [comment]
Correct point!

I think it should be added in the documentation. 

I think a section with your point could be added here:

https://docs.leapp.cloud/0.11.0/installation/requirements/

**Comment by andreacavagna01** [comment]
added requirement
