### ISSUE TITLE
All Leapp CLI commands should take inputs in order to automate configurations

### ISSUE THREAD

**Issue by nitrocode** [Noovolari/leapp#259]
**Is your feature request related to a problem? Please describe.**
We have a lot of profiles to setup and it would be nice to set them all up to Leapp, however, setting this all up in the GUI is painful so I was very happy when the 0.11.0 version announced the CLI. I played with the CLI today and noticed that many commands such as `leapp sessions add` require a prompt and I cannot set configurations using switches like `--session-name`, `--profile-name`, etc.

This means that I cannot use the Leapp CLI to automate the GUI and so the Leapp CLI is more or less the same as the GUI.

**Describe the solution you'd like**
Add switches to each command so we can automate adding profiles

**Describe alternatives you've considered**
Use leapp to authenticate to our main identity user and use an extension or AWS SSO to switch roles instead of leapp

**Additional context**
N/A

**Comment by andreacavagna01** [comment]
Thanks for the feedback! 

We are implementing this feature this week! 

I think una week the feature will be out, we are adding oclif flags to each commands

**Comment by mikedizon** [comment]
@andreacavagna01 perfect timing! is this close to being released?

**Comment by RafPe** [comment]
@mikedizon CLI flags are implemented ( just update ur package )

**Comment by nitrocode** [comment]
I can see the command line flags with the new cli but it still shows me a prompt. It seems like it ignores all my flags for `leapp sessions add` which is the main item I'd like to automate.

Set my env vars.

```console
export LEAPP_IDP_URL="https://example.com"

export LEAPP_IDP_ARN="arn:aws:iam::1234567890:saml-provider/identity"

export LEAPP_PROFILE_NAME="my-identity-profile"

export LEAPP_PROFILE_ALIAS="my-profile-alias"

export LEAPP_ROLE_ARN="arn:aws:iam::1234567890:role/identity"

export LEAPP_REGION="ap-southeast-1"
```

Run commands

```bash
✗ leapp idp-url create --idpUrl $LEAPP_IDP_URL
identity provider URL created
✗ leapp profile create --profileName $LEAPP_PROFILE_NAME
profile created
✗ LEAPP_PROFILE_ID=$(leapp profile list -x | grep $LEAPP_PROFILE_NAME | awk '{ print $1 }' | head -1)
✗ echo $LEAPP_PROFILE_ID
7b60156a-4e35-4a0e-a2f5-94b37f35489a
✗ leapp session add \
  --providerType "aws" \
  --sessionType "awsIamRoleFederated" \
  --roleSessionName $LEAPP_PROFILE_ALIAS \
  --region $LEAPP_REGION \
  --roleArn $LEAPP_ROLE_ARN  \
  --idpUrl $LEAPP_IDP_URL \
  --idpArn $LEAPP_IDP_ARN \
  --profileId $LEAPP_PROFILE_ID
? select a provider (Use arrow keys)
❯ aws
  azure
```

I tried the above with and without the environment variables and no luck.

Is there a way to enable debug logging ? Do you have a working example that I can run ?

**Comment by nitrocode** [comment]
cc: @RafPe @andreacavagna01 (friendly bump for visibility)

**Comment by andreacavagna01** [comment]
I think the bug is in this function: https://github.com/Noovolari/leapp/blob/71eb0c6d0dbe5a12bda083e183af70ca2684ea88/packages/cli/src/commands/session/add.ts#L147

**Comment by nitrocode** [comment]
Ah thank you. I was missing `sessionName` (updated the command above). Once I added that, it worked correctly.

Perhaps some more logging would help if it fails the `verifyFlag` function. It could also only prompt the required inputs that are not defined.
