### ISSUE TITLE
No support of multi-factor authentication

### ISSUE THREAD

**Issue by bastienpebayle** [Noovolari/leapp#26]
**Describe the bug**
The current version does not support AWS accounts that require multi-factor authentication.

**To Reproduce**
1. Create a plain account
2. Click on 'Create account' to add a Truster account
3. The Truster option is greyed out

**Expected behavior**
After creating a plain account, there should a possibility to click on "Truster" and add a truster account.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 02.4

**Comment by ericvilla** [comment]
Thank you @bastienpebayle for the report! 

We'll soon add support to MFA. I think the bug described in **To Reproduce** and **Expected behavior** is not related to the MFA support.

Thank you

**Comment by pethron** [comment]
This is more a feature request than a bug, I'll change the label to better manage the roadmap.

**Comment by urz9999** [comment]
added feature in 0.3.0
