### ISSUE TITLE
Leapp v0.11.0 - Trying to activate sessions loops endlessly with no login prompt

### ISSUE THREAD

**Issue by joseph-max-coalfire** [Noovolari/leapp#261]
**Describe the bug**
When opening Leapp v0.11.0 on a Mac, trying to activate an already configured session will result in an endless loading state (spinning wheel next to session name) with no login prompt in-app or in-browser. Log file has no errors and shows session attempting to be created, but nothing else occurs. Several restarts have not fixed this.

Similar issue when trying to login with an AWS SSO integration-- clicking "Login" on an integration will result in no login prompt or error message.

**Leapp Version**
v0.11.0

**To Reproduce**
1. Open Leapp
2. Click on an already configured AWS SSO session
3. Click "Start Session"
4. Wait for nothing to happen

For integrations:
1. Open Leapp
2. Right-click on an AWS SSO integration from the left toolbar
3. Select "Login" from the dropdown
4. Wait for nothing to happen

**Expected behavior**
Leapp either produces a login prompt via browser or in-app, or an error message is logged to the app log and console.

**Screenshots**
![image](https://user-images.githubusercontent.com/77305023/164490628-b2df87b1-6d5b-4877-80ae-ce2eb6d057f2.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - OS Version: 11.6.1
 - Leapp Version 0.11.0

**Comment by joseph-max-coalfire** [comment]
Sessions using IAM users (not AWS SSO) work just fine, looks like it's just AWS SSO sessions+integrations

**Comment by ericvilla** [comment]
Hi @joseph-max-coalfire, thank you for reporting!
I've just tried it locally, with two AWS SSO integration, and it's working fine. I suggest to double-check the Portal URL, it may be wrong

**Comment by joseph-max-coalfire** [comment]
Hi @ericvilla , I double checked the portal URL by copy-pasting it into my browser and it worked fine. I did upgrade from v0.8 directly to v0.11-- were there any changes to the authentication flow between those two versions that could be causing this?

**Comment by ericvilla** [comment]
@joseph-max-coalfire from 0.8.0 to 0.11.0 there is a change in the AWS SSO integration model. I think it is a retro-compatibility problem. I suggest deleting and re-create the AWS SSO integration. This should create a new AWS SSO integration model in the configuration file. If you have some chained session created from the AWS SSO ones, let's investigate a different solution

**Comment by joseph-max-coalfire** [comment]
Thanks Eric, that worked! One thing to note is I had to delete all of the integrations before recreating them. If I left any integrations alive before recreating one, the new one would fail with the same issue.
