### ISSUE TITLE
Unable to have multiple accounts

### ISSUE THREAD

**Issue by spotlessthoughful** [Noovolari/leapp#27]
**Describe the bug**
The current version will only allow for a single account

**To Reproduce**
Create an account
Create AWS account
Select Plain
Fill in the form
will replace the only account in the application

**Desktop (please complete the following information):**

OS: MacOS
Version 10.15.7

**Comment by andreacavagna01** [comment]
thanks for reporting, it's a bug in the validator.
which version do you have?

**Comment by urz9999** [comment]
@spotlessthoughful have you tried the latest version?

**Comment by spotlessthoughful** [comment]
Sorry for late response. Latest version worked and is good to go!
