### ISSUE TITLE
Opening a SSM Session doesn’t include the right AWS_PROFILE name

### ISSUE THREAD

**Issue by brunodasilvalenga** [Noovolari/leapp#276]
**Describe the bug**
When I create a new SSM Session from the Leapp application it does redirect to my terminal with the following command:

```
aws ssm start-session --region ap-southeast-2 --target 'i-0c743bda11f1ed95c' && unset AWS_SESSION_TOKEN && unset AWS_SECRET_ACCESS_KEY && unset AWS_ACCESS_KEY_ID
```

but is missing the `--profile` variable.

**Leapp Version**
v0.12.0

**To Reproduce**
1. In the session's list
2. Click with right button on the session.
3. Click on "View SSM Sessions"
4. Pick a region
5. Click in Connect

**Expected behavior**
It should also bring the `--profile` in the command to get the right profile configured in the session.

**Desktop (please complete the following information):**
 - OS: MACOS
 - OS Version Monterey 12.0
 - Leapp Version v0.12.0

**Comment by andreacavagna01** [comment]
Hi, thanks for the feedback! thanks for pointing it out! I think it can be added in the next release @ericvilla ?

**Comment by brunodasilvalenga** [comment]
Hey @andreacavagna01, it doesn’t make sense to me :(

If I'm using a profile session with an assumed role and would like to access an SSM session using that role, it should also bring the profile, right?

If not, every time, I will need to edit the command to include the profile I was supposed to use.

**Comment by urz9999** [comment]
A Profile is not something linked to the role or to a session, is something you use to have more than one set of credentials in your credentials file, so you can use more than one set at a time, but because Leapp generates credentials on-the-fly, these are generated from THAT role regardless of profile, you connect to the remote instance with that role, otherwise, you wouldn't be able to do so. Probably you're are confusing something you want to do with something this feature does.

**Comment by brunodasilvalenga** [comment]
Hey @ericvilla, now it looks fine. I don't know if it was a feature created after my PR. But at that time, when I open a session and it was just opening my terminal with the aws command to start the session.

I tested it now and looks like it runs a pre-script before opening the terminal with the command.

Script:
`$ source /Users/<username>/.Leapp/ssm-env`

Before this injecting step wasn't happening.

But thanks for the reply!
