### ISSUE TITLE
Sign windows installation package

### ISSUE THREAD

**Issue by rainmaker2k** [Noovolari/leapp#277]
**Describe the bug**
On Windows when you try to run the setup installation it will try to prevent the installation, because the package is not signed. 

**Leapp Version**
0.12.0 (Windows)

**To Reproduce**
1. Download Windows package through the releases page on https://leapp.cloud
2. Unpack zip
3. Run Leapp Setup.exe

Microsoft Defender will block the installation and you can only continue if you explicitly. 

**Expected behavior**
Installation should not be blocked by Defender or User Account Control

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 11
 - Leapp Version: 0.12.0

**Additional context**
I'm on a company controlled laptop that doesn't allow any unsigned installations.

**Comment by urz9999** [comment]
Hi, @rainmaker2k! As you may know, Windows UAC bases its warning message on the reputation of the software and how many times has been downloaded and effectively used. To prevent this, developers can buy ad hoc certificates, to help with the process of being recognized as fast as possible as a valid application. 

Currently, we are renovating our certificate and changing our pipeline to avoid having the pfx certificate in our codebase. Unfortunately, our certifying company is still evaluating in these days the new certificate, so there is a small maintenance time window, in which in some cases UAC warns about the issue. It will be auto-resolved by itself in no more than 2-3 days.

Sorry for the inconvenience

**Comment by 3apa3a-b-ta3e** [comment]
Honestly speaking, there is a signature on both setup file and main exe, but cert is explicitly revoked — that's why Windows Defender was blocking it and doesn't allow to launch anyway.

**Comment by Plasma** [comment]
Hi @urz9999 unfortunately I think as per @3apa3a-b-ta3e 's comment, the certificate in use has been revoked, so now the latest release has been blocked from use even after installation:

![image](https://user-images.githubusercontent.com/229209/170382959-722227d6-58ed-4224-8784-480dea08b517.png)

**Comment by urz9999** [comment]
We know, we are currently asking Sectigo for support, it seems that the old certificate has been revoked while the new one is STILL in review. It's a very frustrating situation, but we hope to get in touch with them soon. Unfortunately, they already missed the SLA for replying to our support ticket.

**Comment by jbouse** [comment]
Leapp has become totally useless at this point

**Comment by pethron** [comment]
We are working with the certificate supplier to fix this, and bear in mind that we want this issue fixed asap as much as you. To give you a bit of insight if we can’t come to an agreement with our supplier in a short time we’ll change supplier and request a new certificate. I can’t give you an ETA other than **this is one of our top priorities right now**.

Leaving the certificate issue aside, the application logic fully works and you can compile and run it yourself if the windows certificate is blocking you. Also, Leapp is free and open-source and for this kind of problem there’s always the option of the [enterprise support](https://www.leapp.cloud/support) :slightly_smiling_face:

**Comment by urz9999** [comment]
We just released a patch for the Windows certificate. Please verify that it no longer shows the UAC warning.

**Comment by jbouse** [comment]
@urz9999 0.12.2 worked fine on Windows 11

**Comment by rainmaker2k** [comment]
Awesome. UAC warning is gone. I'll close this issue.
Thanks
