### ISSUE TITLE
Lost AzureAD Federation Support

### ISSUE THREAD

**Issue by nick-doyle-slalom** [Noovolari/leapp#279]
**Is your feature request related to a problem? Please describe.**
Latest release has reverted to only supporting AWS SSO integration

**Describe the solution you'd like**
Would like the other IdPs to be reintroduced

**Describe alternatives you've considered**
-

**Additional context**
It looks like support for SSO login via AzureAD was added in this commit https://github.com/Noovolari/leapp/commit/2d0b70b5f935ad0b5abac72ee73cf6bcfdba0cef
which was merged into master

However it looks like commit f1761f88b0a507cd53346742bde8176021370aae (unintentionally I guess) backed out these changes, so now only AWS SSO is available.

**Comment by andreacavagna01** [comment]
@ericvilla can we check this?

**Comment by ericvilla** [comment]
Hi @nick-doyle-slalom, thanks for your feedback! Is the setup you are referring to a SAML federated access to AWS from Azure AD? If so, I can confirm it works at least in Leapp v0.12.0
