### ISSUE TITLE
MacOS High Sierra forever loading client

### ISSUE THREAD

**Issue by TeoGore** [Noovolari/leapp#28]
**Describe the bug**
The client stucks/hangs during the loading screen after the first installation.

**To Reproduce**
1. Downloaded the DMG
2. Mounted and copied the app into the application folder
3. open the app and followed the instructions

**Expected behavior**
Would like to see what's next to the loading screen

 - OS: [MacOS]
 - Version [High Sierra 10.13.6]

![Schermata 2020-10-10 alle 10 25 36](https://user-images.githubusercontent.com/32876096/95650334-4d8ef300-0ae3-11eb-8084-98ff22bd5531.png)

**Additional Information**
I can't update my OS since my PC is old!

**Comment by pethron** [comment]
Hi @TeoGore, you tried to install the latest version of Leapp? Did you have previous versions of Leapp installed?

**Comment by TeoGore** [comment]
Hi @pethron! I've installed the latest .dmg version (0.2.5) but it was the first time for me using leapp (haven't tried previous versions)

**Comment by pethron** [comment]
Thanks for the info. For this, I think we need to get our hands on an earlier version of macOS.
While you wait you can try to build Leapp yourself and see if it resolve your problem.

**Comment by ericvilla** [comment]
Hi @TeoGore, we just released a new version, the 0.2.6, that solves this issue.
I'm looking forward to your feedback to know if it works fine!
Thank you

**Comment by TeoGore** [comment]
Thanks! it works fine now!
