### ISSUE TITLE
As an AD user Windows installer prompts for admin credentials and sessions won't work

### ISSUE THREAD

**Issue by c-sami** [Noovolari/leapp#284]
**Describe the bug**
When a normal Active Directory user logins into computer and executes Leapp Windows installer, UAC prompt will pop up and ask for administrator credentials. If user has different credentials for administering the computer, fills them into UAC and finishes installation Leapp will be installed into admin profile. After installation, starting Leapp will ask for admin credentials and sessions are not available for current user as it is running under admin profile.

**Leapp Version**
0.13.1 and earlier

**To Reproduce**
1. Login to AD joined computer as a normal AD user
2. Download Windows installer from https://www.leapp.cloud/releases
3. Extract .zip and execute the installer or start standalone exe.
4. Get UAC prompt for admin credentials
5. Fill admin credentials and finish the installation
6. Start the application
7. Get UAC prompt for admin credentials
8. Fill admin credentials
9. Add AWS profile and start the session

**Expected behavior**
`C:\Users\<username>\.aws\credentials` contains session credentials and AWS CLI works.

**Actual behavior**
Credentials resides under admin profile at `C:\Users\<admin username>\.aws\credentials` and AWS CLI says that no credentials has been defined.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise, 64-bit
 - 21H1, OS build 19043.1826, Windows Feature Experience Pack 120.2212.4180.0
 - Leapp Version 0.13.1 and earlier

**Additional context**
Changing `packages/desktop-app/packages.json`:
```
"requestedExecutionLevel": "highestAvailable",
```
to
```
"requestedExecutionLevel": "asInvoker",
```
and building the app with self-signed certificate fixes the problem, but will it work also with standalone Windows (not AD joined)?

I have built fixed versions and used them with "aws iam user" and "aws single sign-on" sessions since at least Leapp v0.8.0 and haven't had any problems so far.

**Comment by andreacavagna01** [comment]
Thanks for the detailed issue. we will check the Windows UAC functionalities with @ericvilla.

Maybe is it possible to work on it in [a dedicated PR](https://github.com/Noovolari/leapp/compare)?

**Comment by andreacavagna01** [comment]
Is this problem solved?  can we close this issue?

**Comment by c-sami** [comment]
Sorry, I was on vacation. I just tested with the newest version and issue is still valid.
I'll create a PR for this.

**Comment by c-sami** [comment]
I created a PR #305 and need help testing this for possible side effects.
