### ISSUE TITLE
Hang on wake from sleep with MFA prompt

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#285]
**Describe the bug**

I have an AWS IAM User session that requires MFA (TOTP). If I put the computer to sleep and the session expires while the computer is asleep, when I wake the computer, Leapp will show a prompt for the MFA code, but will not respond (hangs). Activity monitor shows Leapp and Leapp Helpers using significant CPU (20-80% of 1 core each), but Leapp will not even quit: it has to be killed (Force Quit). 

**Leapp Version**
0.12.1

**To Reproduce**
1. Log in as AWS IAM User with MFA
2. Put the computer to sleep
3. Wait for AWS Session to expire
4. Wake computer
5. Switch to Leapp
6. Attempt to enter MFA code

**Expected behavior**
I would prefer (at least as an option) that when the session expires, I get a notification that the session has expired, perhaps with the ability to click on the notification to get prompted for the MFA code, but NOT have Leapp automatically put up the prompt for the MFA code until I ask for it.

In any case, Leapp should not hang, ever.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version 11.6.6
 - Leapp Version 0.12.1

**Comment by andreacavagna01** [comment]
Thanks! thats definitely a bug!

I can confirm that in the past we have had some issues related to the sleep mode. we will check them as soon as possible.

**Comment by andreacavagna01** [comment]
This problem is related to the lack of network in the sleep mode of macOS, this should be fixed in v0.16.0. 

Can you confirm that?

**Comment by pethron** [comment]
Closing as it should be fixed in https://github.com/Noovolari/leapp/compare/v0.15.2...v0.16.0 and no update in the last months. Feel free to reopen the issue if it happens again.
