### ISSUE TITLE
Select all in search bar

### ISSUE THREAD

**Issue by AlbertoCasadei** [Noovolari/leapp#287]
**Actual behaviour**
When typing something in the search bar is not possibile to 'ctrl+a' to quickly select the whole line and re write it if necessary

**Expected**
While searching for a session is possibile to use 'ctrl+a' in the search bar and select all. 

**Notes**
Not blocking nor breaking. Just useful to search faster in case of typos

**Comment by ben-buitendijk** [comment]
I would like to +1 this request. Even after using Leapp for some time, I keep forgetting this doesnt work :)

Btw I am on Mac, so for me the shortcut is cmd + A
