### ISSUE TITLE
Azure session shows AWS logo in edit session page

### ISSUE THREAD

**Issue by mzarglis** [Noovolari/leapp#290]
**Describe the bug**

Azure session shows AWS logo in edit session page
**Leapp Version**
0.12.2

**To Reproduce**
1. Add an azure session in the app c the 
2. click the three dot menu on the right and select "edit session"
3. edit menu pops up showing the AWS logo

**Expected behavior**
Show Azure logo

**Screenshots**
![Leapp_YQH73zMYGC](https://user-images.githubusercontent.com/994599/173887949-23789f48-3743-4db5-9951-7442a2dbeb64.png)
![Leapp_5ciwSgS2Xq](https://user-images.githubusercontent.com/994599/173887954-cac83133-9d38-4b16-a10d-fb8911c4c1c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OS Version: 21H2 
 - Leapp Version: 0.12.2

**Comment by andreacavagna01** [comment]
Clearly a mistake, we are working on changing the Azure functionality to comply with the MSAL authorization method. We will fix this soon

**Comment by pethron** [comment]
We moved the Azure sessions to the Integrations; it's missing the logo right now, but it doesn't show the wrong one. Closing.
