### ISSUE TITLE
Allow copying the URL for "Open Web Console"

### ISSUE THREAD

**Issue by sandfox** [Noovolari/leapp#296]
**Is your feature request related to a problem? Please describe.**
Leapp automatically opens the web console in the default browser. This prevents me from using firefox containers which in turn means I can only have one session active at a time in the browser.

**Describe the solution you'd like**
I'd like to be able to copy the URL so that I can choose which firefox container it's opened in

**Describe alternatives you've considered**
I'm not aware of any work arouns.

**Comment by c-sami** [comment]
For CLI, should it be a new command `session get-web-console-url` in addition to existing `session open-web-console` or should open-web-console refactored into `session web-console print` and `session web-console open`?
