### ISSUE TITLE
leapp-cli: allows deleting the "default" profile breaking aws sso

### ISSUE THREAD

**Issue by nitrocode** [Noovolari/leapp#300]
**Describe the bug**
leapp-cli: allows deleting the "default" profile breaking aws sso

**Leapp Version**
0.12.2

**To Reproduce**

1. leapp profile list
2. leapp profile delete <id>
3. add aws-sso integration
4. see error regarding "no default profile"

**Expected behavior**
Deleted profile without causing other issues

If other issues would be caused, deny deleting the profile

If other issues would be caused, deny even showing me the profile

**Screenshots**
N/A

**Additional context**
Workaround was to remove ~/.Leapp and reinstall Leapp

**Comment by nitrocode** [comment]
I don't believe the formula is the issue

```
$ leapp --version
@noovolari/leapp-cli/0.1.13 darwin-x64 node-v16.15.0
```

**Comment by rick-rtt** [comment]
The latest CLI version is 0.1.14. That formula is not the official one and is not guaranteed to be up to date. Try to install it through the formula from the docs and check if the problem persists.

**Comment by nitrocode** [comment]
I noticed this was closed but was the problem fixed?
