### ISSUE TITLE
Enable "log out" before "Open Web Console" action

### ISSUE THREAD

**Issue by Gowiem** [Noovolari/leapp#309]
**Is your feature request related to a problem? Please describe.**
When I use "Open Web Console" with an SSO integration or SAML or a chained role and I'm already logged into the console with another federated user in some fashion, then I get something like the following: 

![CleanShot 2022-07-27 at 11 49 24](https://user-images.githubusercontent.com/1392040/181327592-420f77ba-78ed-45c5-9b65-3c70a65df2fe.png)

**Describe the solution you'd like*
I'd like to see Leapp log me out of any existing console session before trying to open a new one. 

**Describe alternatives you've considered**

* N/A

**Additional context**

When using aws-vault, I did this with aliases here: https://github.com/Gowiem/DotFiles/blob/master/aws/aliases.zsh#L10-L13

**Comment by pethron** [comment]
Thanks for the idea, Matt! This could be a nice workaround until we publish the multi-account extension.

**Comment by perpil** [comment]
Since it appears Leapp is using the federate api to login to the console, it could be modified to [call logout and federate at the same time]( https://serverfault.com/questions/985255/is-it-possible-to-switch-between-aws-accounts-without-signing-out-first/1097528#1097528).

**Comment by andreacavagna01** [comment]
Hi @perpil I think this could be a great addiction to the federated Web Console. thanks for the suggestion

**Comment by adamantike** [comment]
I've implemented this in #520! @perpil's reference to ServerFault was extremely useful :)

**Comment by andreacavagna01** [comment]
I'll check it out next week!
