### ISSUE TITLE
Do not see a list of instances when using the SSM Connect link

### ISSUE THREAD

**Issue by 094459** [Noovolari/leapp#32]
**Describe the bug**

Do not see a list of instances to connect to.

**Leapp Version**

Version 0.2.6 (0.2.6)
10.14.6 (18G6032) Mac OSX Majave

**To Reproduce**

1) I created a new EC2 instance (t2.micro) using Amazon Linux 2 as I know it has the agent and then added the instance role that allows Session Manager to work
2) once it started, I tested from my browser if i could start a session manager - it worked ok
3) then i setup a new profile on Leapp
4) tried connection and it just sits there.
I thought it might have been vpn at first so disconnected and still getting that

**Expected behavior**

A list of instances

**Additional context**
Tried disconnecting VPN. Tried different AWS users. Tried accessing session manager via console - all ok.

**Comment by 094459** [comment]
[log.log](https://github.com/Noovolari/leapp/files/5422361/log.log)

**Comment by urz9999** [comment]
try with the new version 0.3.0. If it works for you, I'll close the issue

**Comment by 094459** [comment]
Ok progress.

0.30 now brings up a list of instances. When I go to connect with them, I get the following error:

SessionManagerPlugin is not found. Please refer to SessionManager Documentation here: http://docs.aws.amazon.com/console/systems-manager/session-manager-plugin-not-found

**Comment by andreacavagna01** [comment]
We will add documentation for all those issues in the README, thanks for reporting it!
