### ISSUE TITLE
3-dots menu does not close

### ISSUE THREAD

**Issue by mdourmouch** [Noovolari/leapp#33]
**Describe the bug**
When you click on multiple 3-dot menu buttons the menus do not close automatically.

**Leapp Version**
0.2.6

**To Reproduce**
1. Click on the "3-dots" button next to any Role.
2. Click on the "3-dots" button next to another Role.
3. The menu of the first role is still open

**Expected behavior**
There should be only one open menu at time

**Desktop:**
 - OS: macOS Catalina
 - OS Version 10.15.7
 - Leapp Version 0.2.6

**Comment by ericvilla** [comment]
Thank you @mdourmouch, we will keep you informed about the resolution of this issue.
I personally appreciate a lot how precisely you described the bug!

**Comment by urz9999** [comment]
fixed, to see in next release
