### ISSUE TITLE
Invalid Grant error logging on AWS SSO with AzureAd as IdP

### ISSUE THREAD

**Issue by edwardgale** [Noovolari/leapp#332]
**Describe the bug**
Invalid Grant error when logging in via AWS SSO and AzureAd as IdP

**Leapp Version**
Version 0.14.2 (0.14.2)

**To Reproduce**
1. Setup SSO (either browser or in app)
2. Login via IdP (azure ad)
3. Invalid grant error returned

**Desktop (please complete the following information):**
 - Mac

<img width="570" alt="Screenshot 2022-09-07 at 15 30 09" src="https://user-images.githubusercontent.com/1876761/188904365-da94b404-1144-49e5-ad8e-e6fd1176df2a.png">
<img width="470" alt="Screenshot 2022-09-07 at 15 30 15" src="https://user-images.githubusercontent.com/1876761/188904370-c24533a7-da24-4f41-bdb6-b20940a29dba.png">

**Comment by andreacavagna01** [comment]
Thanks for reporting the issue, have you checked the correct form of the portal URL?

**Comment by edwardgale** [comment]
My mistake.  Incorrect AWS region in SSO configuration.
