### ISSUE TITLE
Leapp UI not opening up after closing

### ISSUE THREAD

**Issue by jisujit** [Noovolari/leapp#333]
**Describe the bug**
_Once you close the leapp UI, the app won't start up again_

**Leapp Version**
_Leapp 0.14.2
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044_

**To Reproduce**
_1. Start the Leapp app by clicking on the App icon under Start
2. Close the window
3. Now try to restart the app (as in Step 1)
4. A blank window pops up for a brief second and closes
5. UI does not open up
6. Two2 Leapp processes continue to run under Task manager
7. After restarting the machine, the UI opens up (as in Step 1). Restarting the windows laptop is teh only way I am able to reopen the app_

**Expected behavior**

_The app UI should open up everytime after closing the UI window, and not have to restart windows machine_

**Screenshots**
**Screenshot of task manager showing the 2 running Leapp processes ( at the time UI does not open up)**
![image](https://user-images.githubusercontent.com/45203324/189555392-b94452a1-13a7-4cbf-9640-0d5fd37cf1a0.png)

**Desktop (please complete the following information):**
 _- OS: **Microsoft Windows 10 Pro**
 - OS Version:  **10.0.19044 Build 19044**
 - Leapp Version:  **0.14.2**_

**Additional context**
**NOTE** _that if I use the Quit option in the menu to close the window, the app UI opens up correctly_

**Comment by c-sami** [comment]
Hi,

Did you try to re-open the window from Leapp's Task bar context-menu?
![image](https://user-images.githubusercontent.com/92857136/189592580-24879144-486a-482e-adca-5955221b9ecd.png)

This is a feature that has bugged me a lot and have been thinking of creating an issue about it.
It would be good if Leapp re-opens the window, if it is already running.
Maybe even add an option for "minimize to tray" or "close button minimizes application to tray" so behavior of minimize and/or close buttons could be customized.

**Comment by jisujit** [comment]
Thank you, c-sami,
Yes, I am able to re-open the window from the Task-bar context menu.

**Comment by jisujit** [comment]
My issue is resolved

**Comment by c-sami** [comment]
Welcome!
It needs still to be checked if behavior can be fixed when application is launched while one instance is already running.
I can work on it after I have finished certificate issue.

**Comment by andreacavagna01** [comment]
Awesome! The minimizing/closing electron feature is slightly difficult to manage and does not work in the same in all the OS.

Thanks @c-sami as always!
