### ISSUE TITLE
Leapp not starting ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by Pymatteo** [Noovolari/leapp#334]
**Describe the bug**
On ubuntu 22.04 leapp is not starting: [55202:0902/124111.477466:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is Checking for update

**Leapp Version**
0.14.2

**Desktop (please complete the following information):**
Ubuntu 22.04

**Comment by andreacavagna01** [comment]
Thanks for the feedback! 

This issue is related to the Open Electron bug:
https://github.com/electron/electron/issues/32317

I'm checking in it

**Comment by remixtj** [comment]
hello @Pymatteo i'm running succesfully on ubuntu 22.04, also later releases. Which kind of setup you have?
