### ISSUE TITLE
core: upgrade crypto-js from 4.0.0 to 4.1.1

### ISSUE THREAD

**Issue by ghost** [Noovolari/leapp#339]
**Describe the bug**
With crypto-js 4.0.0 core build generates red warning:
```
../core/node_modules/crypto-js/core.js:40:17-34 - Warning: Module not found: Error: Can't resolve 'crypto' in '/home/user/code/github/leapp/packages/core/node_modules/crypto-js'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
```
**Leapp Version**
master

**To Reproduce**
1. cd leapp && npm ci
2. cd packages/core && npm ci && npm run build
3. cd ../desktop-app && npm install ../core && npm run build-and-run-dev
4. See warning

**Expected behavior**
No warnings.

**Desktop (please complete the following information):**
 - OS: Windows 10, WSL2
 - OS Version: 10
 - Leapp Version: master

**Additional context**
Steps to fix:
1. cd leapp && npm ci
2. cd packages/core && npm ci
3. **npm install crypto-js@4.1.1** && npm run build
4. cd ../desktop-app && npm install ../core && npm run build-and-run-dev
5. No warning about crypto

This comment can also be then removed (lines 4 and 5) https://github.com/Noovolari/leapp/blob/8b5a3c49faab1fd341b0ed3ec6671f884e88d075/packages/core/src/services/file-service.ts#L4

**Comment by andreacavagna01** [comment]
@ericvilla  easy to fix?

**Comment by andreacavagna01** [comment]
We will fix this in the next release

**Comment by rick-rtt** [comment]
We just released a new version of Leapp and bumped the version of crypto-js to 4.1.1. I'm closing this issue.
