### ISSUE TITLE
Hamburger menu button does not work after the menu is closed

### ISSUE THREAD

**Issue by mdourmouch** [Noovolari/leapp#34]
**Describe the bug**
Hamburger menu button does not work after the menu is closed.

**Leapp Version**
0.2.6

**To Reproduce**
1. Click hamburger menu button
2. Close the lateral menu
3. Click hamburger menu button again
4. Menu does not open
5. If you click that button again it works

**Expected behavior**
Open the menu with one click.

**Desktop**
 - OS: macOS Catalina
 - OS Version 10.15.7
 - Leapp Version 0.2.6

**Comment by urz9999** [comment]
solved, to be released in 0.3.0
