### ISSUE TITLE
leapp cli start session should show roles

### ISSUE THREAD

**Issue by lordgordon** [Noovolari/leapp#341]
**Is your feature request related to a problem? Please describe.**
Using Leapp with AWS SSO, an user may have multiple roles per account. When running `leap session start`, the list only shows the accounts without the associated role:
```
> leap session start
? select a session (Use arrow keys)
❯ myorg-sec
  myorg-management
  myorg-prod
  myorg-qa
  myorg-qa
  myorg-prod
  myorg-prod
(Move up and down to reveal more choices)
```

This make impossible to choose the right session to start. A tedious workaround is to first run `leapp session list -x`, then `leapp session start --sessionId <value copied from previous command>`.

**Describe the solution you'd like**
When running `leapp session start` I would like to see a list like it already happens with macOS helper:
```
> leap session start
? select a session (Use arrow keys)
❯ myorg-sec / AdminRole
  myorg-management / AdminRole
  myorg-prod / AdminRole
  myorg-qa / AdminRole
  myorg-qa / ReadOnlyRole
  myorg-prod / ReadOnlyRole
  myorg-prod / SomeOtherSpecialRole
```

**Describe alternatives you've considered**
I don't have alternative proposals.

**Additional context**
Not applicable.

**Comment by lordgordon** [comment]
Is this easy to implement? If so, I can submit a PR.

**Comment by andreacavagna01** [comment]
Yes. It is quite easy, it's just a modification of this line of code:
https://github.com/Noovolari/leapp/blob/73dc8ecd8944cd669f5e855505b14d1c8f495fb6/packages/cli/src/commands/session/start.ts#L67

I will open the PR right now

**Comment by andreacavagna01** [comment]
Created the PR @ericvilla need review to be merged,I'm adding you as a reviewer

**Comment by lordgordon** [comment]
@andreacavagna01 thank you very much!
