### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by laserpez** [Noovolari/leapp#349]
Starting from this morning, I receive an `Internal error` message each time I login to my AWS account:

![image](https://user-images.githubusercontent.com/1087567/195527085-fdbe80c0-c437-4a23-bba8-41b73391560e.png)

I tried both In-App and In-Browser authentication methods but the result is the same. 

I also tried:
 - deleting and recreating the account;
 - restarting the application;
 - reinstalling the application.

Software version is:

> Leapp
> Version 0.15.0 (Core: 0.1.123)
> © 2022 Noovolari

running on macOS Monterey Version 12.6 (21G115).

**Comment by imewish** [comment]
+1

**Comment by umuteyilmaz** [comment]
Unf, I have get this error also

**Comment by andreacavagna01** [comment]
https://www.reddit.com/r/aws/comments/y2tfe3/apparently_theres_an_aws_issue_that_causes_aws/

I think it is related to this issue caused by the AWS Identity center. can you confirm it's resolved now?

**Comment by laserpez** [comment]
> https://www.reddit.com/r/aws/comments/y2tfe3/apparently_theres_an_aws_issue_that_causes_aws/
> 
> I think it is related to this issue caused by the AWS Identity center. can you confirm it's resolved now?

Yes, it works now.

**Comment by andreacavagna01** [comment]
Closing the issue since it's AWS Identity center related
