### ISSUE TITLE
Unable to open multiple browser consoles

### ISSUE THREAD

**Issue by mosaic-nick** [Noovolari/leapp#351]
**Describe the bug**
Unable to start multiple browser sessions

**Leapp Version**
0.16.0

**To Reproduce**
1. Select "Open Web Console" for one AWS account.
2. Select "Open Web Console" for a different AWS account.
3. New browser tab shows "You must first log out before logging into a different AWS account.".
4. Error "Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag." shows in Extensions tab

**Expected behavior**
New browser tab should log into the second AWS account.

**Screenshots**
<img width="981" alt="Screenshot 2022-11-02 at 11 43 26" src="https://user-images.githubusercontent.com/59836651/199481849-09ddc899-52c6-4586-968a-083bdf3556e5.png">
<img width="632" alt="Screenshot 2022-11-02 at 11 44 24" src="https://user-images.githubusercontent.com/59836651/199481853-842fb140-2dd5-4740-a24b-e2bee1d70436.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version 12.3
 - Leapp Version 0.16.0
 - Chrome Version 107.0.5304.87 (arm64)

**Additional context**

**Comment by mosaic-nick** [comment]
Not sure whether it's related, but I have also been having some issues accessing parts of the AWS console with the extension enabled (particularly around security groups). The page initially loads, but navigating around to e.g. inbound rules for a particular security group just spins forever. Disabling the extension fixes the behaviour.

**Comment by andreacavagna01** [comment]
Hey, @ericvilla is it possible to have a problem with cookies? Have you followed [this guide ](https://docs.leapp.cloud/0.16.0/built-in-features/multi-console/#chrome-edge-and-other-chromium-based-browsers_1) @mosaic-nick ?

**Comment by mosaic-nick** [comment]
Thanks @andreacavagna01. I should learn to read docs better...I do now have the multi-console working. I still see the secondary issue I describe above, but I'll raise a separate bug for that.

**Comment by PatrykMilewski** [comment]
To future readers, make sure you follow docs for latest version, not the one linked above, or you might miss some extra steps:
https://docs.leapp.cloud/0.18.5/built-in-features/multi-console/#chrome-edge-and-other-chromium-based-browsers_1
