### ISSUE TITLE
Chrome extension causes lagged/crashed tabs

### ISSUE THREAD

**Issue by mosaic-nick** [Noovolari/leapp#353]
**Describe the bug**
With the Leapp extension installed and enabled, some pages in the AWS console do not load properly or become unresponsive.

**Leapp Version**
0.16.0

**To Reproduce**
1. Make sure the Leapp extension for Chrome is installed and enabled
2. Browse to the AWS console for an account (makes no difference whether this is via "Open Multi-Console Extension" or any other way of getting there)
3. Go to EC2
4. Select Security Groups
5. Click on a security group in the list. Note that the lower pane does load up, but after a considerable time spinning
6. Click on the Inbound Rules tab.
7. Note that the inbound rules never load. After a short while, the page becomes completely unresponsive.
8. Disable the Leapp extension.
9. Browse to the AWS console for an account.
10. Go to EC2
11. Select Security Groups. Note that the lower pane loads up immediately.
12. Click on the Inbound Rules tab.
13. Note that the inbound rules load.

**Expected behavior**
Security groups and rules should load without lag and without pages becoming unresponsive. I have not tested other areas of the AWS console, so this could be a more widely-spread issue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version 12.3
 - Leapp Version 0.16.0
 - Chrome Version 107.0.5304.87

**Additional context**

**Comment by andreacavagna01** [comment]
Thanks for reporting it. 

we will look at it and get back to you.

**Comment by rick-rtt** [comment]
It should be fixed with the latest extension version. Try installing it and if the error persists, we can reopen this issue.

**Comment by mosaic-nick** [comment]
I agree, this looks to be fixed now. Thanks for the quick turnaround! This feature is killer.
