### ISSUE TITLE
Automatically focus on text field when asking for MFA code

### ISSUE THREAD

**Issue by PatrykMilewski** [Noovolari/leapp#359]
**Is your feature request related to a problem? Please describe.**
When I'm trying to start a session with MFA assigned, I always need to click on MFA text input field

**Describe the solution you'd like**
I would like it to be focused, so I can start writing without clicking on the text field

**Additional context**
<img width="1312" alt="Screenshot 2022-11-15 at 17 10 37" src="https://user-images.githubusercontent.com/21146316/201970772-2dc64a42-3a7b-4fe0-af14-62f77c5b3b1f.png">

**Comment by andreacavagna01** [comment]
Great addition!

**Comment by rick-rtt** [comment]
I checked and noticed there was a problem with Angular and autofocusing a modal, so I added a very short setTimeout and it should work now! This fix will be available in the next release

**Comment by PatrykMilewski** [comment]
Wow thanks! It was quick!
