### ISSUE TITLE
The drop down forgets history when account is changed using the task bar dropdown

### ISSUE THREAD

**Issue by Pymatteo** [Noovolari/leapp#36]
**Describe the bug**
The drop down forgets history when account is changed using the task bar dropdown

**Leapp Version**
0.2.7 deb ubuntu

**To Reproduce**
1. Change accounts using leapp app
2. change account using taskbar cropdown
3. history is gone

**Desktop (please complete the following information):**
 - OS:ubuntu 18.04
 - OS Version 18.04
 - Leapp Version 0.2.7

**Comment by urz9999** [comment]
marked for release 0.2.8

**Comment by urz9999** [comment]
closed in 0.3.0
