### ISSUE TITLE
AWS SSO Integration stopped working after update, doesn't open login window.

### ISSUE THREAD

**Issue by saurabhshri-evive** [Noovolari/leapp#365]
**Describe the bug**
Updated Leapp to `Version 0.16.2 (0.16.2)`. AWS SSO integrations stopped working. It'd not open browser window for login. Changing to in-app method does nothing as well, it stays at this window. 

<img width="1137" alt="Screenshot 2022-11-24 at 1 24 01 PM" src="https://user-images.githubusercontent.com/45559829/203725375-7556a76e-e426-4394-9bcc-3c345d01153b.png">

**Leapp Version**

Version 0.16.2 (0.16.2)

**To Reproduce**
1. Open Leapp
2. Click on SSO integrations to login
3. Nothing happens.

**Expected behavior**
Login window to AWS SSO should open, like it used to.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - macOS (Apple M1 Pro)
 - OS Version [e.g. 22] - macOS 13
 - Leapp Version [e.g. 0.2.5] - Version 0.16.2 (0.16.2)

**Additional context**
- there's nothing relevant in `/Users/saurabhshri/Library/Logs/Leapp/log.electronService.log`, here's last few logs 

```
[2022-11-24 13:23:30.734] [info]  [renderer] Preparing for closing instruction...
[2022-11-24 13:23:30.736] [info]  [renderer] Closing app with cleaning process...
[2022-11-24 13:23:48.243] [info]  [renderer] Check existing credential file: false
[2022-11-24 13:23:48.246] [info]  [renderer] Loaded plugins...


[2022-11-24 13:23:48.791] [info]  [renderer] execute from Leapp
info:{
    "command": "/usr/local/bin/aws --version",
    "stdout": "aws-cli/2.5.6 Python/3.9.12 Darwin/22.1.0 source/x86_64 prompt/off\n",
    "stderr": "",
    "error": null
}
[2022-11-24 13:23:48.794] [info]  [renderer] execute from Leapp
info:{
    "command": "/usr/local/bin/session-manager-plugin --version",
    "stdout": "",
    "stderr": "/bin/sh: /usr/local/bin/session-manager-plugin: No such file or directory\n",
    "error": {
        "killed": false,
        "code": 127,
        "signal": null
    }
}
[2022-11-24 13:23:48.794] [error] [renderer] [TrayMenuComponent] Error: An error occurred getting AWS Session Manager Plugin version. <span class='link'>Click here to follow the instructions on the docs</span> and solve the issue.
    at file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.17be7b89f7d16e9b.js:9297:19
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.17be7b89f7d16e9b.js:186024:24)
    at _throw (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.17be7b89f7d16e9b.js:186050:9)
    at _ZoneDelegate.invoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.23a56c6b24ce7905.js:424:158)
    at Object.onInvoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.17be7b89f7d16e9b.js:145059:25)
    at _ZoneDelegate.invoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.23a56c6b24ce7905.js:424:46)
    at Zone.run (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.23a56c6b24ce7905.js:208:37)
    at file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.23a56c6b24ce7905.js:1300:28
    at _ZoneDelegate.invokeTask (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.23a56c6b24ce7905.js:451:171)

```

- tried backing up and removing lockile from `/Users/saurabhshri/.Leapp`; it reset the app, but adding new integration had the same issue. So reverted back to old lockfile.

I am not sure how to open the debug console, but it was working till day before yesterday. I am not sure if it's a coincidence that it stopped after the update, but that seems like a primary suspect. 

Let me know if I can provide with any other information. Thanks!

**Comment by saurabhshri** [comment]
`aws sso configure` appears to be working fine. 

PS sorry for the Github account mix-up! 🤦

**Comment by urz9999** [comment]
Hi @saurabhshri, thanks for reaching us! Here are a few questions to help us understand better:
1) When the modal appears have you tried clicking on the link provided there to force open the page in the browser?
2) In-app method should not open the modal version, what step did you do?
3) Are you using the credential file or process method in the option?
4) In what region do you do SSO?
5) Can you provide some hints about your configuration, obviously without giving sensible information :)?
6) Try seeing cookies in your browser and remove those relevant to google to see if those are somewhat corrupted
5) Was SSO working with what version prior to 1.16.2?

In the meantime, we will check for eventual bugs in the code that could lead to this problem and let you know if we find something!

**Comment by saurabhshri** [comment]
1. Yes, multiple time. Tried changing default browser as well, no avail.
2. Nothing happens when I click "Login" after choosing In-app method. See the video (sorry for the weird crop, had to hide names).
https://user-images.githubusercontent.com/12415700/203736041-0c51734d-59cf-42cb-889d-c0ac2a0ca8d2.mov
3. Credentials file. 
<img width="512" alt="Screenshot 2022-11-24 at 2 21 36 PM" src="https://user-images.githubusercontent.com/12415700/203736246-a7549ff4-4c36-4bee-ae11-d0a0b01e2d0e.png">
4. `us-east-1`
5. It's a simple AWS SSO integration. 
<img width="491" alt="Screenshot 2022-11-24 at 2 22 42 PM" src="https://user-images.githubusercontent.com/12415700/203736622-7f828c30-d529-4e5e-9e68-d057784dc4fd.png">
6. It doesn't even open browser, so I doubt that's the issue. Plus `aws sso configure` works.
7. So, last I used Leapp was day before yesterday and yes it was working. But today I directly updated and then tried. So not sure if something broke in between or it's just the update. 

Feel free to let me know I can provide any other information, thanks!

**Comment by urz9999** [comment]
We tried to do SSO with all combination of configuration possible and it's working as it should, and the developer console is blocked in the standard release version. 
The best option to try and resolve your problem at the moment seems to download and compile the source code locally to access the developer console and look out for errors (probably some network related ones).

**Comment by saurabhshri** [comment]
I am afraid it's going to be one of "those" issues. It started working normally when I re-tried today. Did not do anything different after last attempt. I'll close this issue and re-open in case it reoccurs. Thank you for you time.

PS Do you think it'd be a good idea to allow users to optionally enable developer console from settings, in release versions?

**Comment by andreacavagna01** [comment]
It could be an idea, or an enhanced logs to display more meaningful errors message

**Comment by urz9999** [comment]
No problem @saurabhshri, glad it started working again. Maybe we could add a button to force-open the developer tool window in release.
