### ISSUE TITLE
Session connection status is grey when selected

### ISSUE THREAD

**Issue by hungluong5791** [Noovolari/leapp#366]
**Describe the bug**
When selecting a session in the session list, the connection status dot on the right is grey - same color as unconnected session - instead of green.

**Leapp Version**
0.15.2

**To Reproduce**
1. Go to 'All Session' tab, should have at least 1 session
2. Click on any session row in the table
3. Observe the connection status dot

**Expected behavior**
Connection dot should be green whether selected/highlighted or not

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/11902001/205810432-1221f294-be67-4ac6-9e63-c40c4fbd1079.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I am using Dark Color theme

**Comment by andreacavagna01** [comment]
This error is fixed in already fixed in the v0.16.2. 
I'm going to close this issue since is fixed
