### ISSUE TITLE
Filter flag in the cli does not seem to work

### ISSUE THREAD

**Issue by Pat-Ayres** [Noovolari/leapp#367]
**Describe the bug**
When using cli commands with the `--filter` flag I get an error ` ›   Error: Filter flag has an invalid value` even if I use the documented example. I have tried multiple ways of passing the flag.

**Leapp Version**
0.16.2

**To Reproduce**
1. run any `list` command with the `--filter` flag. E.G. `leapp profile list --filter=name=foo`

**Expected behavior**
I expect a table with results filtered to match my query.

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version 12.6.1
 - Leapp Version 0.16.2

**Comment by Pat-Ayres** [comment]
I realized the issue is that `name` is not a valid field, the field is actually `Profile Name`, so the working command needs to look like `leapp profile list --filter="Profile Name=foo"` (quotations are required because of the space in the column name).  Would a PR to update the documentation clearing up this confusion be helpful?

**Comment by pethron** [comment]
Closing. Fixed documentation in [v0.17.2](https://github.com/Noovolari/leapp/compare/v0.17.1...v0.17.2).
