### ISSUE TITLE
Extend web console session beyond an hour

### ISSUE THREAD

**Issue by bf-jamesworville** [Noovolari/leapp#370]
**Is your feature request related to a problem? Please describe.**
It's frustrating having a console session that's only an hour long. I tried a lot of the plugins but they seem incompatible. Perhaps due to some of the constants that have been set with regards to the session duration.

**Describe the solution you'd like**
Option to customise your own session duration

**Describe alternatives you've considered**
I've tried some additional plugins and amending some code, to no avail.

**Additional context**
N/A

**Comment by andreacavagna01** [comment]
Hello @bf-jamesworville, thanks for opening the issue! 

We are aware of your frustration, and I think we can extend the session duration of the Web Console soon. 

> Describe the solution you'd like
Option to customise your own session duration


I think the essay option will be first to extend the session duration up to 8 hours, then we can add an option in the settings!

How does this sound?

**Comment by bf-jamesworville** [comment]
Hey! That would be fantastic. I did try amending the value in the web console plugin, but it didn't like it - possible becuase of a reference to `constants.ts` that wouldn't allow it. I'd give a go with a pull request if I was any use with TypeScript 😆

**Comment by ericvilla** [comment]
Hi @bf-jamesworville, the PR we've merged and included in the last [v0.17.0](https://github.com/Noovolari/leapp/pull/319) release should solve this enhancement issue. Please, let us know if the v0.17.0 version is working as you meant. Feedbacks are always welcome. I'm going to close this issue.
