### ISSUE TITLE
Feature Request : Leapp-CLI in Non Interactive mode

### ISSUE THREAD

**Issue by RamazanKara** [Noovolari/leapp#384]
**Is your feature request related to a problem? Please describe.**
Leapp is currently not scriptable, but the multi account structure would be very ideal to use in non interactive mode for multi account deployments. Leapp should be able to be scripted without requiring interactions.

**Describe the solution you'd like**
Session-start aswell as session-ssm-start are startable in non interactive mode and therefore scriptable

**Describe alternatives you've considered**
There is no alternative.

**Additional context**

**Comment by andreacavagna01** [comment]
Thanks for the enhancement!

Have you take a look at the Leapp CLI?

https://www.leapp.cloud/cli

You can create script on top of the interactive UI.

Is that what you are looking for?

**Comment by RamazanKara** [comment]
Hi. unfortunately not. So what we would want would leapp-cli to be completely scriptable in for example a python script. For that you would have to be able to pass the session alias in non interactive mode. 

So a basic example workflow that we would want to achieve would be:

- Start Python script
- Python script automatically assumes a role in an account in the script with leapp
- Python script can start do stuff in said account
- Python script assumes a new role in a different account with leapp
- Python script continues to do stuff in the new assumed account.

**Comment by andreacavagna01** [comment]
Thanks for the explanation. 
I know the session alias is not unique. You can do it by session ID. 

You can check [this article](https://medium.com/leapp-cloud/how-to-quickly-automate-aws-federated-session-generation-with-leapp-cli-e5e505653001) by @urz9999.

This is an hack to make the CLI scriptable. But I add this to the roadmap

**Comment by RamazanKara** [comment]
Thank you. Seems like basically being able to pass params to session start command would still be a better way to do this, so thanks for adding this to the roadmap.

**Comment by andreacavagna01** [comment]
now the CLI has `--no-interactive` mode
