### ISSUE TITLE
Feature Request: Config share between teammates

### ISSUE THREAD

**Issue by RamazanKara** [Noovolari/leapp#385]
**Is your feature request related to a problem? Please describe.**
Currently, Leapp configurations are not shareable for teammates as they are encrypted. This should however be possible for atleast the chained roles for usability improvements.

**Describe the solution you'd like**
Being able to export and import the leapp and leapp cli configuration.

**Describe alternatives you've considered**
Manual configuration by each user, which increases the onboarding process.

**Comment by pethron** [comment]
Hi @RamazanKara, this feature falls in our Team plan as it's a collaboration feature.
The platform is still in development, but you can get in touch with us at https://www.leapp.cloud/team

**Comment by andreacavagna01** [comment]
Hello @RamazanKara, this feature is now out and accessible in early access on: https://www.leapp.cloud/solutions/team

I'm going to close this issue.
