### ISSUE TITLE
Dot-delimited profile names are escaped when written to the credentials file

### ISSUE THREAD

**Issue by jalaziz** [Noovolari/leapp#392]
**Describe the bug**

The AWS CLI (and other tooling) allows profile names to contain dots (e.g. `myprofile.admin`). Leapp _seems_ to support dot-delimited profile names too, except for when the profile is written to the `credentials` file, the dots are escaped (e.g. `myprofile\.admin`). While this may seem perfectly valid, the AWS CLI fails to load the profile with the unescaped name.

I've done some digging and the issue is not strictly a Leapp problem. The escaping is done in [ini](https://github.com/npm/ini) lib when the credential file is written [here](https://github.com/Noovolari/leapp/blob/master/packages/core/src/services/file-service.ts#L120). Up until that point, the profile name is correctly unescaped. It seems that the `ini` lib _does_ support unescaped dots in section headers, but only for nested keys.

**Leapp Version**
0.17.1

**To Reproduce**
1. Create an AWS session with the named profile `myprofile.admin`
2. Start the session
3. Attempt to use the profile using `aws sts get-caller-identity --profile myprofile.admin`
4. Observe the error: `The config profile (myprofile.admin) could not be found`

**Expected behavior**
The profile should be found and the identity of the authenticated user should be returned.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: 13.2
 - Leapp Version: 0.17.1

**Additional context**

It's not super clear where this should be fixed. One option would be for Leapp to convert dot-delimited profile names into nested objects. Another option would be to try to fix this upstream in the `ini` library by introduce a new `encode` option.

I'd be happy to contribute a fix, but I'm curious which approach is preferred.

Some related issues:
* https://github.com/npm/ini/issues/60
* https://github.com/aws-amplify/amplify-cli/issues/10525

**Comment by ericvilla** [comment]
We've just release Leapp v0.17.3 which solves the reported issue. I'm going to close this issue
