### ISSUE TITLE
Leapp Browser window sometimes says "Javascript is not enabled in your browser" in Google Sign-in

### ISSUE THREAD

**Issue by kevcube** [Noovolari/leapp#407]
on macOS 13.3.1 sometimes when I get the google sign-in window for re-authenticating, google claims my browser doesn't support javascript and doesn't let me proceed with sign-in flow.

If I try again it usually works, but this would not be an issue with using either the user's default browser.

Another related issue is the inability to use my safari saved passwords in this browser popup - this may be fixable by using [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession)

ref: https://github.com/Noovolari/leapp/blob/6223d0d2748581c879ef5e0a630315bc61c670ab/docs/troubleshooting/faq.md?plain=1#L14

**Comment by ericvilla** [comment]
Hi @kevcube, thanks for reporting this issue!

Please follow the [Bug Report](https://github.com/Noovolari/leapp/issues/new?assignees=&labels=bug&projects=&template=bug-report.md&title=) to provide all the information needed to fully understand the scenario.

Just a few questions that you can provide an answer to in the template:

- what type of Leapp Session causes this error?
- are you using the in-app login window or the default browser?
- what version of Leapp are you using?

Thank you in advance!

**Comment by ericvilla** [comment]
I'm going to close this issue due to inactivity
