### ISSUE TITLE
Windows wrong Certificate - defender smart screen does not allow to install the app safely

### ISSUE THREAD

**Issue by ohrmaman** [Noovolari/leapp#408]
Hello, quick question,
I came across your amazing project, and I want to implement it in our organization the following message pops
![image](https://user-images.githubusercontent.com/92078035/236025829-038f4714-1d7b-460b-8b90-898aa4e9870f.png)

Why windows does not recognize it as a safe package? and can you please solve it somehow?

**Comment by andreacavagna01** [comment]
Thanks for the Issue. I think it's just a problem of certificates that can be quickly resolved by changing the certificate type for Windows. 

Thanks for reporting the issue

**Comment by ohrmaman** [comment]
Great if you can also apply it on the CLI it would be great
Do you know when would it be released? more or less ?😅

**Comment by urz9999** [comment]
Hi, @ohrmaman can you confirm that the problem is resolved for the Windows App? We have recently changed the signing certificate and procedure.

Thanks for your patience.

**Comment by andreacavagna01** [comment]
Closing this issue since it's fixed
