### ISSUE TITLE
Make the "back" button of the Create Account wizard more evident

### ISSUE THREAD

**Issue by paolofulgoni** [Noovolari/leapp#41]
**Is your feature request related to a problem? Please describe.**

If I start the Create Account wizard and change my mind, there is apparently no way to go back to the main page.
Except... that little "<" button in the "My Access strategy" area, which I found when I was already writing this issue :-)
I think that that button is not evident enough to the user.

**Describe the solution you'd like**

Replace the "<" button with an "exit" (or "back", "home") button on the left of the "save" button, which exits the wizard and shows me the main page.

**Describe alternatives you've considered**

Restarting the app :-)

**Additional context**

I'm using version 0.3.2

![image](https://user-images.githubusercontent.com/5703017/99724469-f00f9e00-2ab3-11eb-99e7-9df11a3c933b.png)

**Comment by ericvilla** [comment]
Hi @paolofulgoni, thank you for the report! Well, that's an issue that other users have already encountered. We will take this into account for the next minor release. Hope you find the 0.3.2 version stable!

**Comment by andreacavagna01** [comment]
Nice first issue @paolofulgoni, thanks for helping us.

Usability is something we are working on deeply!

**Comment by paolofulgoni** [comment]
Thanks for your speedy reply!
Unfortunately I don't know Typescript so I can't help :-(
I'm glad that you appreciate feedback!!

**Comment by andreacavagna01** [comment]
No problem, in an open-source projects there are several ways to help improving the project.

For sure testing and feature requesting are a great help!

Also if you want meet our team and talk about roadmap and possible feature, join our server on Discord

**Comment by andreacavagna01** [comment]
closed in v0.4.5
