### ISSUE TITLE
Truster account edit

### ISSUE THREAD

**Issue by paolofulgoni** [Noovolari/leapp#42]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to edit a "truster" account which I previously created

**Describe the solution you'd like**

Add an edit menu like the one for "plain" accounts

**Describe alternatives you've considered**

Delete and create the account again

**Additional context**

Leapp 0.3.2

**Comment by andreacavagna01** [comment]
At the moment the edit account has been disabled to facilitate some flow. 

But it will be re-enabled soon I Think

**Comment by hoegertn** [comment]
Anything on this topic?

**Comment by pethron** [comment]
It will be fixed in the upcoming UX refactoring

**Comment by pethron** [comment]
Fixed
