### ISSUE TITLE
no proxy configuration available (under linux?)

### ISSUE THREAD

**Issue by aogier** [Noovolari/leapp#421]
ciao, I've seen #8 and other issues but I'm having hard time figuring out how to configure a proxy with current leapp version 0.17.6. Could you please help on that, perhaps integrating current documentation if that's the case?

Thank you, ciao :)

**Comment by aogier** [comment]
tl;dr but thank you for your feedback :) ciao!

**Comment by siipimutteri** [comment]
It's coming.

Unfortunately supporting proxy feels an easy fix, but it isn't. It involves ability to trust self-signed certificates which also seems to be an easy thing to do, but it isn't.
Good news is that both abilities are doable and we have many small pieces already done.
I feel that it's something that needs to be supported sooner than later and the demand for this feature will increase. There are many companies who uses visible or invisible proxy for IDS and feature is mandatory for them.

**Comment by aogier** [comment]
> Unfortunately supporting proxy feels an easy fix, but it isn't. It involves ability to trust self-signed certificates which also seems to be an easy thing to do, but it isn't.

https://en.wikipedia.org/wiki/Excusatio_non_petita,_accusatio_manifesta

it's pretty boring to be put on the side of certain complaints, if you feel like doing it fine, if not don't do it, nobody forces anybody to do anything my friend :)
