### ISSUE TITLE
programmatically get a session id

### ISSUE THREAD

**Issue by aogier** [Noovolari/leapp#423]
Hi, it would be great if `session get-id` command could take a command line argument specifying session name, so I can do something like

```shell
leapp session list | awk '/whatever/ {print $1}' | while read session_name
do
    leapp session delete --sessionId $(leapp session get-id --name $session_name)
done
```

otherwise housekeeping become pretty boring when you have dozen sessions configured :P

```shell
$ leapp session list | wc -l
101
```

TIA, ciao

**Comment by urz9999** [comment]
Hi @aogier, thanks for the suggestion. We'll check and put it in roadmap. We'll give you an update here as soon as we start working on this.

**Comment by aogier** [comment]
ciao! Many thanks and let me know should I could help you somehow, beside writing javascript because it's not my cup of tea (in fact I'm working on a python library which wraps this tool)

**Comment by aogier** [comment]
Ciao! I think you've worked on that because today I've updated leapp-cli and now something like that is indeed possible:

```shell
leapp session list -x | awk '/xx/ {print $1}' | while read id
do 
    leapp session delete --sessionId $id -f 
done
```

so thank you, I'm closing that :rocket: :heart:

**Comment by aogier** [comment]
@urz9999 just so you get notified: issue solved in the latest, thx
