### ISSUE TITLE
Make the window resizable

### ISSUE THREAD

**Issue by paolofulgoni** [Noovolari/leapp#43]
**Is your feature request related to a problem? Please describe.**

I have some account alias which are quite long, so the account name on the main page is truncated.
It's not possible to resize the window to show the full account name.

**Describe the solution you'd like**

Make the window resizable and "expand" the shown account name.

**Describe alternatives you've considered**

Right-click on the system try icon to see the full name

**Additional context**

Leapp 0.3.2

**Comment by andreacavagna01** [comment]
The feature is already been fixed in the future releases, by now this fix is in another feature branch.

Thanks for all this enanchement

**Comment by ericvilla** [comment]
This enhancement issue is covered in the last [release](https://www.leapp.cloud/releases)! I'm going to close it
