### ISSUE TITLE
tray icon in linux

### ISSUE THREAD

**Issue by aogier** [Noovolari/leapp#444]
Ciao, while this feature request is obviously not related to a problem, I find it quite annoying to use third-party tools like https://kdocker.sourceforge.net/ in order to put leapp in my linux traybar.

If you could consider implementing at some point in future, this would be great :)

ciao!

**Comment by ericvilla** [comment]
Thank you for reporting @aogier! What do you mean with traybar, as we tested it in Linux and it appears (maybe we intend two different things). Can you provide a screenshot of the actual icon position and where you expect it to be?

**Comment by aogier** [comment]
ciao Eric, traybar = system tray. I'm on linux using i3 and I see no icon at all on my status bar app which is compliant to common specifications like System Tray Protocol Specification etc, ie. other things like discord or dropbox or slack et al usually are displayed without particular problems.

Thank you, ciao!

**Comment by icholy** [comment]
This was fixed in electron https://github.com/electron/electron/pull/36815 and back-ported to the v22-x-y branch. So updating to `v22.3.24` should fix this.

**Comment by aogier** [comment]
thank you! We found setting a proper SSO w/ aws identity center a breeze and a totally better solution, cause it's aws cli native and does not require third party electron toys... thx anyway, ciao!

**Comment by aogier** [comment]
also, I will never again be asked if by traybar I mean the traybar, not even if I were my grandmother complaining that the internet is broken. And I like that very much :D

**Comment by icholy** [comment]
@aogier grow up

**Comment by aogier** [comment]
hahaha no need to

https://docs.aws.amazon.com/singlesignon/latest/userguide/manage-your-identity-source-idp.html

**Comment by andreacavagna01** [comment]
Thanks for the comment @icholy. 

@aogier, it is my goal as a maintainer to make participation in our project and our community a harassment-free experience for everyone, and with your expressions, you are violating our [Code of Conduct](https://github.com/Noovolari/leapp/blob/master/.github/CODE_OF_CONDUCT.md).

I'm happy you found a solution for your specific use case. Please remember that we are an inclusive Community, and we embrace any enhancement. 

As a maintainer, I have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned with this Code of Conduct, so please mind your language while you are participating to this community.

**Comment by aogier** [comment]
I was legitimately complaining about the very poor support I received and was told that I need to grow up: glad to see that it is my attitude that is considered non-inclusive. Anyway, that's perfectly fine. Regards and good luck with Leapp.

**Comment by icholy** [comment]
Resolved by https://github.com/Noovolari/leapp/commit/efcf6e22554032799db27ecfcc4c2b4de5610131

**Comment by icholy** [comment]
Confirmed fixed in 0.20.2 
![image](https://github.com/Noovolari/leapp/assets/943597/c14323ca-3a78-41ab-9c1e-677cb890f2a1)
