### ISSUE TITLE
Support for Keycloakx

### ISSUE THREAD

**Issue by pat-s** [Noovolari/leapp#447]
**Is your feature request related to a problem? Please describe.**

Despite Keycloak being supported, it seems [Keycloakx](https://www.keycloak.org/2019/10/keycloak-x.html) isn't. 

**Describe the solution you'd like**

Add support for Keycloakx.

**Describe alternatives you've considered**

**Additional context**

I just skimmed through the code and I think the issue could be in https://github.com/Noovolari/leapp/blob/28979e208a10a9e2ad03fee88c571a0551894a7e/packages/core/src/services/aws-saml-assertion-extraction-service.spec.ts#L36

as here the assertion of `/auth/realms/xx` is being checked. However Keycloakx moved to `/realms/xx`, i.e. omitting the `auth/` part in the path.

Maybe allowing both, the regex with `/auth/` and without `/auth/` would be enough to add support?

Currently I get a "SAML authentication timeout exceeded" when trying to use Keycloakx with a "AWS IAM Role Federated" session profile.

**Comment by urz9999** [comment]
Hi, is exactly as you pointed out, if you want you can make a PR yourself (as you have the account to test it out), otherwise we'll add it to the roadmap and add it as soon as possible. Thanks for pointing it out!

**Comment by kiduko** [comment]
same issue on the latest version of keycloak (v22.0)

**Comment by pethron** [comment]
Fixed with #428
