### ISSUE TITLE
Support MFA for Azure auth

### ISSUE THREAD

**Issue by pat-s** [Noovolari/leapp#450]
**Is your feature request related to a problem? Please describe.**

It seems like Azure MFA isn't supported

![image](https://github.com/Noovolari/leapp/assets/8430564/ebfabc9c-4848-41ba-9fa2-3fb1da75e095)

**Describe the solution you'd like**

Support Azure MFA

**Describe alternatives you've considered**

none

**Additional context**

**Comment by ericvilla** [comment]
Hi @pat-s, thank you for reporting! Have you already tried to logout from the Azure integration and logged in again?

**Comment by pat-s** [comment]
Thanks @ericvilla, that did the trick!
