### ISSUE TITLE
Support truster account as source for another truster account

### ISSUE THREAD

**Issue by hoegertn** [Noovolari/leapp#46]
**Is your feature request related to a problem? Please describe.**

When configuring trusted accounts, I cannot use another truster account as a credentials source.
In my scenario I have my company account T. To access customer's accounts I now have a trust relationship to their org account C. This org account has trust relationships with the workload accounts of the clients W1, W2, ...

I now need to use the following cred chain: T -> C -> W1

**Describe the solution you'd like**
I would love to have a truster account as a credential source

**Describe alternatives you've considered**
None come to my mind

**Comment by pethron** [comment]
Multiple chaining is something we will definitely support in future releases. Thanks for the feedback.

**Comment by andreacavagna01** [comment]
Added In v0.6.0
