### ISSUE TITLE
v0.18.6 does not create "~/.aws/credentials" file if it does not exist

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#466]
**Describe the bug**
If the `~/.aws` directory exists but the `~/.aws/credentials` file does not, Leapp does not create the file and instead throws an error:

```
ENOENT: no such file or directory, open '/Users/user/.aws/credentials'
```

**Leapp Version**

Leapp Version v0.18.6

**To Reproduce**
1. Close Leapp if running 
2. Delete `~/.aws/credentials` if it exists
3. Start Leapp
4. Use Leapp to start a session
5. See error

**Expected behavior**

Leapp should create the credentials file if it does not exist

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: 12.6.8
 - Leapp Version: 0.18.6

**Comment by andreacavagna01** [comment]
Hi @Nuru, Thanks for the feedback! This is clearly unexpected behavior. I will check it as soon as possible.

**Comment by rick-rtt** [comment]
Hello @Nuru, I installed v0.18.6 and tried to follow the steps you described, but I couldn't reproduce the bug. That error pops up when I try to start a session and I deleted the credential file _after_ I started the application. If I restart Leapp, the file is automatically created again.

**Comment by urz9999** [comment]
We tried again and in the last version the code seems to work as expected, We are closing this issue do to inactivity, in case the problem is not resolved for you, feel free to open a new issue :)
