### ISSUE TITLE
App crashes after automatic update

### ISSUE THREAD

**Issue by bastienpebayle** [Noovolari/leapp#47]
**Describe the bug**
Dialog boxes "A new version has been downloaded. Close and re-open Leapp to use the new version." keep popping up after automatic application update and closing then re-opening the app as indicated. The app crashes when trying to open it.

**Leapp Version**
0.3.2 (before automatic update)

**Expected behavior**
- Click "ok" on dialog box
- Close Leapp
- Re-open Leapp

**Screenshots**
![image](https://user-images.githubusercontent.com/29253804/100746885-4538a180-341c-11eb-8c8c-dd8dd49ec660.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Leapp Version: 0.3.2

**Comment by ericvilla** [comment]
Hi @bastienpebayle, can you provide a picture with a bigger resolution so we can debug it? Thank you

**Comment by ericvilla** [comment]
We've just investigated this issue. You should quit the application from the task bar, not only using the "x" button. The reason behind this is that we want to maintain the same behaviour as mac and linux applications, where the app is reduced to icon by clicking the "x" button, instead of being closed.

**Comment by bastienpebayle** [comment]
Hi @ericvilla sorry for the late reply - I also quit the application from the task manager but the app would automatically re-open with the same update message. I had to uninstall the app

**Comment by ericvilla** [comment]
Hi @bastienpebayle, at the moment I think that the only way to debug your issue is to analyze Leapp's logs. You can find them in %USERPROFILE%\\AppData\\Roaming\\**Leapp**\\logs\\log.log

**Comment by ericvilla** [comment]
Hi @bastienpebayle, I will close this issue. If you're still experiencing this problem, please reach out to us, and we'll re-open the issue and discuss about it.

**Comment by nathaniellarson** [comment]
Just so that @bastienpebayle knows that they weren't alone, I had the same happen with all the same settings. The solution was to BOTH uninstall AND end the Leapp task. I suppose I could redownload. I uninstalled before I could grab the logs.
