### ISSUE TITLE
Custom 404 page not found

### ISSUE THREAD

**Issue by parthrc** [Noovolari/leapp#489]
**Is your feature request related to a problem? Please describe.**
Currently when a user clicks on a broken link or tries to access a page that does not exist, a 404 page by Github pages is shown. It has a link to the GitHub pages documentation which might confuse the user. 

**Describe the solution you'd like**
I would like to create a custom 404 page not found in line with the design of the website and which would also have a link to the homepage improving the user experience.

**Describe alternatives you've considered**

**Additional context**

I can help create this page, please assign me. Thanks

**Comment by andreacavagna01** [comment]
That's a good idea I think. also easy to implement with material docs. 

I will check the feature

**Comment by parthrc** [comment]
Let me know If I can help in anyway.

**Comment by andreacavagna01** [comment]
Added 404 page in the documentation
