### ISSUE TITLE
Update cli to use newer version of crypto-js

### ISSUE THREAD

**Issue by FutureKode** [Noovolari/leapp#496]
**Describe the bug**

![Screenshot 2023-11-10 at 10 14 34](https://github.com/Noovolari/leapp/assets/332387/4ab10bbb-52ac-44b3-8938-c4b12943a45c)

**Leapp Version**

`@noovolari/leapp-cli": "^0.1.43`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version [e.g. 22]
 - Leapp Version [e.g. 0.2.5]

**Additional context**

**Comment by andreacavagna01** [comment]
Thanks a lot! We are currently working on a release with crypto js updated, at the moment, the main problem to solve is the Apple notarization updated

**Comment by andreacavagna01** [comment]
Solved now
