### ISSUE TITLE
Support Truster Account names

### ISSUE THREAD

**Issue by aletheia** [Noovolari/leapp#5]
AWS Truster account ids are nice, but accounts can be identified also by their name (or alias) which usually works in "switch role" functionality. Having support also for account names would be great

**Comment by pethron** [comment]
Unfortunately not. At least not a way that I'm aware of. The only available way is to use the list-account-aliases API, but you need to have already configured a set of credentials with permission to do so... and it's pointless as we need the role arn to make the API call. If someone is aware of another a workaround we are open to suggestions.

**Comment by pethron** [comment]
Closing this issue because it's not possible to implement.
Feel free to re-open if someone find a workaround to implement.
