### ISSUE TITLE
Azure AD -> AWS federation

### ISSUE THREAD

**Issue by what-name** [Noovolari/leapp#50]
**Describe the solution you'd like**
Ability to use Azure AD as an identity provider for AWS accounts.

**Additional context**
We would like to use Leapp to programatically access multiple AWS accounts. The SSO is federated by Azure AD, we log in through `myapps.microsoft.com` and choose "AWS SSO" from the list of options. This in turn takes us to the usual AWS accounts list. From here we choose "Command line or programmatic access".

**Current steps**
1. Log in to `myapps.microsoft.com`
2. Chose "AWS SSO" from the list of options
3. Site `xyzxyzxyz.awsapps.com/start` gets opened with all accounts present
4. Choose account and "Command line or programmatic access" (which assumes an AdministratorRole in the target account)
5. Paste access keys into terminal manually

**Screenshots (console)**
<img width="1402" alt="Screenshot 2020-12-16 at 12 18 49" src="https://user-images.githubusercontent.com/20590073/102342006-f43ab880-3f98-11eb-9db0-921611b09fc4.png">
<img width="1142" alt="Screenshot 2020-12-16 at 12 18 58" src="https://user-images.githubusercontent.com/20590073/102342271-4da2e780-3f99-11eb-9ab3-e4a1c31b6d9e.png">

**Comment by ericvilla** [comment]
Hi @what-name, thanks for the enhancement proposal, that's very interesting!

So, if I understood right, it regards the possibility to list and access AWS Account - belonging to your AWS Organization - and automatically generate temp credentials to access AWS Account, without setting them manually.

I guess you already set up the federation between Azure AD and AWS SSO; what type of IdP is Azure AD, SAML or OIDC?

Thanks!

**Comment by andreacavagna01** [comment]
supported in v.0.4.0
