### ISSUE TITLE
Leapp Team invite dead ends on "pro" registration complete page

### ISSUE THREAD

**Issue by arcaven** [Noovolari/leapp#506]
### Description:
> Links from Leapp Team invite and announcement page dead end with "pro" registration page

### Details:
| Leapp Version | 0.23.0 |
| --- | --- |
| SsmPluginVersion | 1.2.463.0 |
| Platform | darwin |
| Awscli | aws-cli/2.13.17 Python/3.11.5 Darwin/23.1.0 source/arm64 prompt/off

Note: I am an early adopter, and have Leapp pro installed, using my personal account, which is also my github account. I am also a candidate to bring Leapp Team to my company, and it might be with github email or with company email. We have okta, and use an okta identity for most things, using company email domain(s).

Not sure how to proceed, should I try logging out of pro somehow to get started on Leapp Teams? All links to sign up/sign in with teams results in the attached screenshot. Do I need to attempt to log in with NOT my Leapp pro email / with my company email where I received the invite (seems like it is open beta enrollment?)

![Screenshot 2023-12-13 at 10 34 39 AM](https://github.com/Noovolari/leapp/assets/2000551/0a5ef212-c4da-4062-b068-b3c4f4b3e077)

**Comment by andreacavagna01** [comment]
Hi Michael, thanks for reporting, at the moment, you have to clean your local storage in order to register your Team with Leapp. We will fix the issue shortly

**Comment by andreacavagna01** [comment]
Let me know if cleaning the local storage helps in resolving your issue

**Comment by andreacavagna01** [comment]
This problem is now solved, we have added a link to sign out and register as a new user, thanks for noting that!
