### ISSUE TITLE
leap CLI team login not working

### ISSUE THREAD

**Issue by cap10morgan** [Noovolari/leapp#507]
**Describe the bug**
`leapp team login` returns `login successful` after entering credentials that also work in the desktop app. But after that I can't set any team workspaces and `leapp team status` returns `you're not logged in`.

**Leapp Version**
Leapp desktop version: 0.23.0
Leapp CLI version: Version 0.1.51 (Core: 0.1.154) (installed via Homebrew)

Using fish shell v3.6.4 in case that matters.

**To Reproduce**
1. Setup a team and login to it in the desktop app to verify that all works.
2. Run `leapp team login` in the term
3. Ensure it returns `login successful`
4. Run `leapp team status`

**Expected behavior**
`leapp team status` should indicate that I'm logged in and `leapp set-workspace MYWORKSPACE` should work.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: 14.2

**Comment by ericvilla** [comment]
Hi @cap10morgan, thanks for reporting this issue! It seems to be a problem related to the CLI release pipeline. We're going to further investigate it and provide a solution for everyone is using Leapp Team through the CLI (it's going to be a 0.1.53 release for the CLI)

**Comment by ericvilla** [comment]
Hi @cap10morgan, we've just released Leapp CLI v0.1.54

Please, update the CLI to this version, so that you can start using Leapp Team from the command line.
Still, we are investigating the pipeline issue that I've mentioned in the previous comment.
Let us know if everything works fine with the new version.

Thanks!

**Comment by cap10morgan** [comment]
I just upgraded it via Homebrew and got version 0.1.53, which exhibited the same behavior:

```
$ leapp team login
? insert your email me@my.org
? insert your password [hidden]
login successful
$ leapp team status
you're not logged in
```

Once I get 0.1.54 I'll try it again. Thanks!

**Comment by cap10morgan** [comment]
Working in 0.1.54. Thanks!
