### ISSUE TITLE
Leapp Multi-Console Causes 400 Request Header or Cookie Too Large on Amazon.com

### ISSUE THREAD

**Issue by mcalhoun** [Noovolari/leapp#508]
**Describe the bug**
After using the Leapp multi-console for some period of time, there is an accumulation of cookies that begin with `##LEAPP`. When visiting the amazon retail site (amazon.com), I get the following error:

```
400 Bad Request
Request Header Or Cookie Too Large
```

If I remove these `##LEAPP##` cookies, I can browse the site again normally. After using the multi-console again for some time, I again get the same error.

**Leapp Version**
Version 0.22.1 (0.22.1)

**To Reproduce**
1. Use leapp multi-console for a period of time until you have a lot of cookies
2. Browse to https://amazon.com

**Expected behavior**

**Screenshots**
![CleanShot 2023-12-18 at 10 07 11](https://github.com/Noovolari/leapp/assets/930247/06b0b109-bea7-4e12-8c4a-459593857ade)

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version:  Sonoma 14.1.1 (23B81)
 -  Leapp Version: Version 0.22.1 (0.22.1)

**Comment by mcalhoun** [comment]
As a possible quick-fix solution, could you scope the cookies to `console.aws.amazon.com` rather than `.amazon.com`?

**Comment by mcalhoun** [comment]
Has anyone looked at this? It's occurring daily for me now.

**Comment by andreacavagna01** [comment]
We are actively looking into that right now, I'll get back to you

**Comment by ericvilla** [comment]
@mcalhoun this issue should have been fixed with the latest v0.1.8 Web Extension release. We're going to close it as soon as you confirm it's working as expected.

**Comment by mcalhoun** [comment]
It seems to have been resolved for me. I'll definitely let you know if it shows up again. Thanks!

**Comment by ericvilla** [comment]
Thanks @mcalhoun for your feedback! I'm going to close the issue. Feel free to re-open it, if the error shows up again
