### ISSUE TITLE
Firefox Multi-Container Web Console not working after first session with a profile

### ISSUE THREAD

**Issue by zampettim** [Noovolari/leapp#525]
**Describe the bug**
Starting with Version 0.24.6 (0.24.6) of Leap on Mac M1, using the "Open Web Console" option in Leapp on Firefox fails after first session for a profile. 

**Leapp Version**
Version 0.24.6 (0.24.6)

**To Reproduce**
1. Right Click on a configured AWS profile and choose "Open Web Console"
2. Confirm that AWS Console opens with the correct profile information
3. Close the browser tab
4. Right Click on the same configured AWS profile and choose "Open Web Console"
5. Message appears that the web console was opened, but nothing happens in Firefox

**Expected behavior**
A new browser tab opens with the AWS Console logged in and available.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version 14.3 (23D56)
 - Leapp Version 0.24.6

**Additional context**
Disabling the Leapp extension in Firefox and then re-enabling restores functionality once. Clicking on a different profile works the first time as well.

It appears that after the first session for a particular profile is started, no new sessions can be started without clearing the extension memory (which disable/enable does) or restarting firefox.

**Comment by Bozz95** [comment]
The multi-container web console is not working to me either on Windows 10.

To make it work again after the first session I have to restart Firefox.

**Comment by andreacavagna01** [comment]
I'm going to close this issue
