### ISSUE TITLE
After deleting session(s) UI reports unable to sync workspace

### ISSUE THREAD

**Issue by arcaven** [Noovolari/leapp#528]
### Description:
> After deleting AWS IAM User Sessions from a Pro Workspace, Leapp is reporting "An issue in Syncing Workspace" Request failed with status code 401, RETRY Wait a second and then retry to manually sync
Selecting RETRY does not clear the errors.
Restarting the application, all the sessions that had been deleted/attempted to delete and cleared from the UI have returned.

![Screenshot 2024-02-09 at 9 39 45 PM](https://github.com/Noovolari/leapp/assets/2000551/da6af56d-c77c-42c9-8999-a68234431b8a)

### Details:
| Leapp Version | 0.24.6 |
| --- | --- |
| SsmPluginVersion | 1.2.463.0 |
| Platform | darwin |
| Awscli | aws-cli/2.15.14 Python/3.11.7 Darwin/23.1.0 source/arm64 prompt/off

**Comment by arcaven** [comment]
Behavior may be related to deleting multiple sessions in series, without waiting for the "sync" to complete between each. 
If you wait 5-8+ seconds for the sync to complete, they get deleted. If you do not wait, sync fails for good until you restart the app.

**Comment by ericvilla** [comment]
Hi @arcaven, thank you for reaching out to us! We tried to reproduce the issue by deleting multiple sessions in series from a Pro workspace. It's working on our side. Are you trying to delete them using a Leapp CLI script?

**Comment by arcaven** [comment]
@ericvilla no script, but I’m connected over starlink, so the api calls may have piled up for me in ways they dont for you. I often see lag of several seconds between action and response, such as when an auth session fails.  as much as 2-5 seconds sometimes. Or after dispatching a request to start a session, it can take 3-5 seconds before succeeds or fails to initiate sso. 

if you’re not see it, i’m not worried about it. 
when i waited until i got the tooltip pop up on the left confirming it had deleted, then it worked fine

and it’s not something i expect to do often or even again

**Comment by arcaven** [comment]
closing, if i see it again, i’ll check back?

**Comment by ericvilla** [comment]
Ok @arcaven, feel free to reach out to us if the error shows up again
