### ISSUE TITLE
Unable to login to AWS SSO with "in-app" method 

### ISSUE THREAD

**Issue by bhargavAtDF** [Noovolari/leapp#545]
### Description:
> I've entered right login details but login doesn't work.

### Details:
| Leapp Version | 0.24.1 |
| --- | --- |
| SsmPluginVersion | 1.2.339.0 |
| Platform | darwin |
| Awscli | aws-cli/2.8.0 Python/3.9.11 Darwin/23.2.0 exe/x86_64 prompt/off

**Comment by JeffreyCanisius04** [comment]
Running into this as well

**Comment by mupi2k** [comment]
I know at least a couple dozen folks affected by this. Fortunately the workaround is simple (switch your Auth method), but it's still annoying.

**Comment by cellsignal-m** [comment]
Same, the issue shows that it successfully logs in, but the final page for the login has changed and it seems that is throwing the app off.
![Screenshot 2024-03-19 14 07 43](https://github.com/Noovolari/leapp/assets/103438525/b5a032e7-939e-4b34-b79c-b840fcad8207)

**Comment by cdelcastillo** [comment]
Same, the issue shows that it successfully logs in, but the final page for the login has changed and it seems that is throwing the app off.
![Screenshot 2024-03-19 14 07 43](https://github.com/Noovolari/leapp/assets/103438525/b5a032e7-939e-4b34-b79c-b840fcad8207)
Leapp Version: 0.25.2
Platform: debian

**Comment by NickLeone** [comment]
FWIW, after editing my integration's auth method and choosing the "in-browser" option, it works.
<img width="510" alt="Screenshot 2024-03-19 at 3 25 42 PM" src="https://github.com/Noovolari/leapp/assets/17744922/a8b1818f-8ea0-4b0c-ba33-e0ffefb832b0">

**Comment by pethron** [comment]
We've confirmed it's a change in the auth redirects from AWS that aren't catched by the filter. For now you can work-around it by choosing "in-browser". I'm going to rename the issue and description to make it more easy to find it for others.

**Comment by bhargavAtDF** [comment]
Yes, In-browser login method is working.

**Comment by ericvilla** [comment]
https://github.com/Noovolari/leapp/issues/540#issuecomment-2020883613
