### ISSUE TITLE
R3InjectorError after upgrading to 0.25.3

### ISSUE THREAD

**Issue by gabrieleCutowl** [Noovolari/leapp#549]
**Describe the bug**
After upgrading to 0.25.3 the app is not working

**Leapp Version**
0.25.3

**To Reproduce**
Install the version 0.25.3

**Screenshots**
![image](https://github.com/Noovolari/leapp/assets/95495843/b5401179-0a74-430d-8e2a-b504f4c1527f)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: 13.6
 - Leapp Version: 0.25.3

**Comment by ericvilla** [comment]
There was a problem during the release phase. Just released a new [working build](https://www.leapp.cloud/releases)
