### ISSUE TITLE
Find an account by account id

### ISSUE THREAD

**Issue by e-moshaya** [Noovolari/leapp#55]
It would be really nice to be able to find an account by account id instead of name.

![image](https://user-images.githubusercontent.com/44640934/104473179-9a87d700-55b4-11eb-9bcf-57861fee391b.png)

**Comment by ericvilla** [comment]
Interesting point @e-moshaya. It sounds easy to implement, providing a real improvement to the user experience. Thanks for your feedback, we will add it to the v1.0.0 roadmap.

**Comment by AMMullan** [comment]
Second this - for some reason I know the first 4 digits of our 128 accounts more than I know the names so filtering by IP would be super useful :)

**Comment by urz9999** [comment]
No problem, i'll add it for the next release among other things. Let's review the goals:

## Goals
be able to search by **account number** (and maybe other common properties as well)

## Procedure
We already have a session card that contains all the property of the session. for that just add a condition for the filter including the properties we want to search.

## Properties would like to add
- account number (AWS)
- SAML 2.0 URL (AWS)
- Username (AWS PLAIN)
- Tenant id (AZURE)

**Comment by andreacavagna01** [comment]
Added all these abilities in the v0.4.5 version
