### ISSUE TITLE
 Unable to open version 0.25.3

### ISSUE THREAD

**Issue by cunymatthieu** [Noovolari/leapp#550]
**Describe the bug**
Unable to open version 0.25.3
https://github.com/Noovolari/leapp/releases/tag/v0.25.3

**To Reproduce**
Open Application

**Expected behavior**
the application should open normally

**Screenshots**
<img width="608" alt="Capture d’écran 2024-03-29 à 11 23 17" src="https://github.com/Noovolari/leapp/assets/16045974/c027261f-416b-4af1-8d6a-69a462b30ace">

**Desktop (please complete the following information):**
Apple M1 Pro
MacOS : 14.4 (23E214)

**Additional context**
I was in version 0.25.2 before.

**Comment by derehveronika** [comment]
The same issue for me. The application window is blank after the upgrade to the newest version.

**Comment by ericvilla** [comment]
There was a problem during the release phase. Just released a new [working build](https://www.leapp.cloud/releases)
