### ISSUE TITLE
Unable to download Leapp-0.25.3-win.zip file

### ISSUE THREAD

**Issue by vigneshgurusamy** [Noovolari/leapp#551]
**Describe the bug**
Access denied error from S3

**Leapp Version**
0.25.3

**To Reproduce**
1. Go to https://asset.noovolari.com/latest/Leapp-0.25.3-win.zip

**Expected behavior**
Link should be open for download

**Screenshots**
![image](https://github.com/Noovolari/leapp/assets/6076800/6d73ea96-06a0-4c00-b6cc-43716414feb6)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - OS Version [e.g. 22] 11
 - Leapp Version [e.g. 0.2.5] 0.25.3

**Additional context**

**Comment by ericvilla** [comment]
Thank you @vigneshgurusamy! Fixed; now it is possible to download the Windows 0.25.3 version

**Comment by vigneshgurusamy** [comment]
@ericvilla Thank you...
