### ISSUE TITLE
Not All AWS Accounts are showing for AWS SSO

### ISSUE THREAD

**Issue by e-moshaya** [Noovolari/leapp#57]
We have 32 AWS SSO accounts, but on Leapp, only 20 are showing and not alphabetically sorted. Also, when I use the find an account search box for the missing accounts, they still don't show in the result.

**Leapp Version**
Version 0.4.0 (0.4.0)

**To Reproduce**
1. Go to Leapp Homepage for AWS SSO provider

**Desktop (please complete the following information):**
MacOS Catalina 10.15.7

**Comment by ericvilla** [comment]
Thanks for the bug report @e-moshaya. Please, may you share a screenshot of the issue? Moreover, have you already checked if your AWS SSO User has actually access to all the 32 accounts, or only to 20 of them?

**Comment by e-moshaya** [comment]
Hi,

Yes, I have Admin access to all 32 accounts. Please screenshot below:

![image](https://user-images.githubusercontent.com/44640934/104475563-2864c180-55b7-11eb-9c0b-fbb9b782a509.png)

Leapp does not support resizing the window for me to show you the full list of accounts. Also, our account names are sensitive. So, I've redacted the names:

![image](https://user-images.githubusercontent.com/44640934/104475781-63ff8b80-55b7-11eb-907a-79f6393b1091.png)

**Comment by ericvilla** [comment]
Ok, we're going to investigate this issue as soon; it's very critical to us. I will add it to the roadmap!

**Comment by ericvilla** [comment]
Hi @e-moshaya, we solved this problem in the new [v0.4.1 release](https://github.com/Noovolari/leapp/projects/5)

**Comment by e-moshaya** [comment]
Hi,

I've just managed to test out this latest 0.4.1 version and this issue has not been fixed. I still only see 20 out of 32 accounts.

**Comment by e-moshaya** [comment]
@ericvilla could you please reopen this issue as it has not been resolved with 0.4.1 or 0.4.2

**Comment by ericvilla** [comment]
Hi @e-moshaya! If you are still experiencing this problem, I will re-open the issue. We've tested it by mocking AWS SSO's API response. We will investigate it more in-depth, and ask you for more details to better define the context. Thank you!

**Comment by AMMullan** [comment]
Heya - I'm also seeing the same issue. We've got 128 accounts (and I've got multiple permission sets in these) and I only see 28 permission sets in all in Leapp. It's a fantastic tool but this kind of makes it unusable :(

**Comment by andreacavagna01** [comment]
I'm having some difficulties in testing it because I have fewer accounts in my organization, @AMMullan I want to fix it as soon as possible, let me know if you can help me in troubleshooting it

**Comment by AMMullan** [comment]
> I'm having some difficulties in testing it because I have fewer accounts in my organization, @AMMullan I want to fix it as soon as possible, let me know if you can help me in troubleshooting it

Yep, more than happy to help.

**Comment by andreacavagna01** [comment]
Probably we have found the issue, but need to test it, what about if I fork the project and you will try if it fixes the problem? 

I think it's a problem with the nextToken request in the listAccount API of AWS SSO Portal APIs.

https://docs.aws.amazon.com/singlesignon/latest/PortalAPIReference/API_ListAccounts.html

**Comment by andreacavagna01** [comment]
Released the new version, should be fixed now! test it and let me know @AMMullan

**Comment by AMMullan** [comment]
That's better :) Had to log out and then it came up with all the accounts / permission sets. Nicely done @andreacavagna01 !

**Comment by andreacavagna01** [comment]
Awesome! I'm really interested in knowing more about how Leapp can help you, join our Discord if you want to chat more on the App :) 

https://discord.gg/4mAa2EHAsc

**Comment by andreacavagna01** [comment]
added the same problem if there are more than 100 roles available for each account in v0.4.5
