### ISSUE TITLE
Alphabetically Sort Accounts in Leapp

### ISSUE THREAD

**Issue by e-moshaya** [Noovolari/leapp#58]
On AWS SSO Portal, all accounts are alphabetically sorted. It would be nice to get the same with Leapp.

**Comment by andreacavagna01** [comment]
We can add an Alphabetically import to AWS SSO account, whenever they are in the list. they are sorted by the most recently used, which I think is a more useful method to retrieve quickly the account you need

**Comment by jgrumboe** [comment]
Hi, I would also agree for alphabetically sort or some kind of choosing a sort order.
The Web-UI from AWS is now sorting the accounts alphabetically.
When you write that Leapp is sorting by recently used, is it that the most recently used account is at the bottom of the list? If yes, that's also not useful when you have 30+ accounts in the list.

**Comment by andreacavagna01** [comment]
The idea behind this kind of sort is to have the most recent account used at the top of the list, this is something we are achieving in a better way in the next release.

Do you think that alphabetic sorting is the best way to represent the list?

**Comment by jgrumboe** [comment]
The best option would be to let the user select how to order the list.
Strangly my account list is now sorted alphabetically but reverse, don't know why.

**Comment by andreacavagna01** [comment]
Good idea! Sorting options can be a great way to accomplish most use cases
