### ISSUE TITLE
SSM Session start command is not using the region selected in the dialog

### ISSUE THREAD

**Issue by h-svab** [Noovolari/leapp#61]
**Describe the bug**
Starting a SSM Session from Leapp results in an error:
```
$ aws ssm start-session --target 'i-0**************4'
You must specify a region. You can also configure your region by running "aws configure".

```
**Leapp Version**
0.4.0

**To Reproduce**
1. Go to 'SSM session'
2. Select a region
3. Click on one of the listed instances
4. Terminal window opens
4. See command and error

**Expected behavior**
I expect the ssm session successfully started like using
```
aws --region eu-west-1 ssm start-session --target 'i-0**************4'
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version 10.15.7 (19H114)
 - Leapp Version 0.4.0

**Additional context**
This only happens when using the SSO account. Then there is no default region set in the .aws/credentials file. This would be anyhow problematic in case I would want to connect to an ec2 instance in a different region (region selection in the SSM session dialog) then the one the account was configured with.

**Comment by ericvilla** [comment]
Thanks @h-svab for the report! We could get this information - i.e. the region - and use it as you suggested. We will support this soon. As a temporary workaround, just run `aws configure` to configure the region.

**Comment by ericvilla** [comment]
Hi @h-svab, we solved this problem in the new [v0.4.1 version](https://github.com/Noovolari/leapp/projects/5)

**Comment by h-svab** [comment]
Thank you @ericvilla! I tested it today with the new version and it works like charm.

**Comment by ericvilla** [comment]
Nice to hear that! Thank you for your feedback.
