### ISSUE TITLE
Configuration for using alternative terminal apps for SSM session (iTerm as terminal on MacOS)

### ISSUE THREAD

**Issue by h-svab** [Noovolari/leapp#62]
**Is your feature request related to a problem? Please describe.**
I usually use iTerm as terminal which is superior to the Terminal app included in MacOS. It would be nice to be able to configure the terminal app that is being used for SSM session.  

**Describe the solution you'd like**
Provide a configuration option which terminal should be used for starting a SSM session.

**Describe alternatives you've considered**
I don't use this feature at the moment but start the ssm session in the terminal of my choice.

**Comment by pethron** [comment]
We could provide a field for the user to select the path to the terminal executable

**Comment by h-svab** [comment]
That sounds good, I was looking at the code that executes the command and on MaxOS Leapp uses Applescript commands with [`osascript`](https://github.com/Noovolari/leapp/blob/master/src/app/services-system/execute-service.service.ts#L57)
I'm still experimenting what the proper osascipt command would look like for [iTerm2](https://iterm2.com/documentation-scripting.html)

**Comment by h-svab** [comment]
Ok once again Google won: https://apple.stackexchange.com/a/360827
```
osascript \
    -e 'tell application "iTerm2" to tell current window to set newWindow to (create tab with default profile)'\
    -e 'tell application "iTerm2" to tell current session of newWindow to write text "aws --region eu-west-1 ssm start-session --target i-0***************4"'
```

**Comment by pethron** [comment]
Thanks @h-svab for the suggestion. We still need a way to let the user select the preferred executable and verify that it's installed. I think we could use a dialog to let the user select the path to the executable. I'd like to know what @urz9999 and @ericvilla think about this.

**Comment by jgrumboe** [comment]
Are there any updates on this?
I'm also using iTerm2 on MacOS. Since this change is coupled to a specific osascript you could probably just make it a MacOS select box to choose between standard terminal or iTerm2.

**Comment by andreacavagna01** [comment]
This feature was not in the roadmap, but we are adding it to match the System Preferences.
In order to make the thing work cross-platform we need to implement an AppleScript specific for ITerm in Mac like this:
```
tell application "iTerm"
	set newWindow to (create window with default profile)
	tell current session of newWindow
		write text "ssm command to run"
	end tell
end tell
```

But I still need to look for other Operating Systems (Linux and Windows).

Definitely is a feature I want to add soon after this coming release.

Any other ideas on how to implement this solution?

https://github.com/Noovolari/leapp/blob/74ba2d10338da83b3182e798d551f6651d1af010/src/app/services-system/execute-service.service.ts#L55

As seen here, in the executeService, we are already using osascript to open external terminal windows.

I'm an iTerm user too 👍

**Comment by MaartenUreel** [comment]
I would also like to see this feature; I prefer the new "Windows Terminal" from Microsoft (https://github.com/microsoft/terminal) but Leapp opens cmd.exe by default.

Having this configurable would be convenient! :)

**Comment by ericvilla** [comment]
In Leapp v0.10.0 you can start an AWS SSM session through iTerm2 by selecting it in the options menu!

Referenced by [#176](https://github.com/Noovolari/leapp/issues/176)
