### ISSUE TITLE
Multiple AWS SSO Support

### ISSUE THREAD

**Issue by rianbk** [Noovolari/leapp#63]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for multiple SSO accounts. Hi, I work across alot of AWS SSO environments, being able to have all of them in leap would be great

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ericvilla** [comment]
Hi @rianbk, I think this is already described in bug #57. Please, give it a look and confirm here. Thanks

**Comment by rianbk** [comment]
Hey @ericvilla , no with this i'm talking about multiple AWS SSO "root" accounts. Not child accounts under a SSO setup

**Comment by ericvilla** [comment]
Ok, now I understood what you meant! It is an interesting enhancement, given that a single person may access different AWS Organizations at the same time, for example when working with customers. At this moment it is not in the roadmap, but we could consider adding it for the next releases.

**Comment by infsy** [comment]
I've got the same need than @rianbk . Using Leapp is addictive, and so be able to switch between client organizations would be awesome !

**Comment by andreacavagna01** [comment]
This is a thing we are trying to achieve for the next release, I'll add it in the[ v1.0 roadmap](https://github.com/Noovolari/leapp/projects/4)

**Comment by andreacavagna01** [comment]
@infsy and @rianbk, how do you expect a UI for multiple AWS SSO account management?

**Comment by infsy** [comment]
I guess @andreacavagna01 we should first have the option to fill multiple AWS SSO identity providers in the Integrations. Then, in the Home menu I could use the AWS icon to select the right SSO IDP to work with. Does it make sense ?
![Capture_d_écran_2021-03-03_12_34](https://user-images.githubusercontent.com/1073400/109847404-25806780-7c1d-11eb-8e32-da09d772a362.jpg)

**Comment by rianbk** [comment]
> @infsy and @rianbk, how do you expect a UI for multiple AWS SSO account management?

For me I’d be happy with the same format (everything just in one big list - that’s why search exists?) maybe some prefixing or something to show what account it’s from

**Comment by marshallamey** [comment]
I thought that I would be able to select SSO as an Access Strategy for adding multiple accounts in different organizations.  This was the main reason I was drawn to Leapp. As an MSP, it would make life a lot easier.

**Comment by andreacavagna01** [comment]
Great Idea, it's something I think could be implemented in the [Daemon](https://github.com/Noovolari/leapp-daemon) and then added from the core logic to the Client

**Comment by james-kontralto** [comment]
I have a need for this, to fill in another use case: having a second org(and thus another IDP) to test out infrastructure before rolling it out to prod. I've consulted for 2 different enterprises who follow this pattern, and being able to switch between orgs/IDPs seamlessly would be huge.

**Comment by james-kontralto** [comment]
I think ideally I'd like to be signed into both - I can envision firing out the infra to the test org, validating, then immediately rolling it out to prod. On the flipside, I think there's a safety aspect to being authed to only one org at a time. I can do all of the testing required, then switch over to prod, without the worry that I was actually in prod the whole time. Minor, but it came to mind. :)

**Comment by andreacavagna01** [comment]
I think it will be a great thing to add the ability to group Sessions by AWS Single Sign-On to find them better.
But at least have the ability to have more than one [integration](https://docs.leapp.cloud/concepts/#integrations) at the same time. :)

**Comment by james-kontralto** [comment]
Agreed! Can't wait to see this in the app, I love using it so far!

**Comment by hoegertn** [comment]
Is there any ETA for this feature? Currently, I can only use Leapp for one client instead of all my clients.

**Comment by hoegertn** [comment]
@andreacavagna01 Anything new on this? I need to decide if I can keep using Leapp or look somewhere else in the near future. So any ETA would be great to plan.

**Comment by pethron** [comment]
The current ETA for this is ~3 months. The current issue is that we perceive configuring multiple AWS SSO as a collaboration feature to be introduced in the Leapp paid tier. We are trying to gather as much feedback as possible on this to take a direction as we would prefer to leave this on the open-source project since it benefits everyone. Sill, we also need to make a choice that doesn't hinder the project's sustainability. We can talk here or open a dedicated discussion. Currently, you can see at #178 the features division in tiers.

**Comment by m-radzikowski** [comment]
I think this is done in just released v0.8.0.

**Comment by pethron** [comment]
Closing due to release v0.8.0
