### ISSUE TITLE
SSO Account as source for truster account

### ISSUE THREAD

**Issue by m-radzikowski** [Noovolari/leapp#66]
**Is your feature request related to a problem? Please describe.**

I have Identity Provider integration with AWS SSO. Setting it up gives me a list of accounts I have access to through my company SSO with G Suite.

Now one of those accounts has a trust relationship with the client account. Unfortunately, I cannot choose it in "Truster Setting" when adding a new account with "truster" access strategy.

SSO -> JumpBox Account -> Client Account

**Describe the solution you'd like**

Use accounts from SSO login as a source for "truster" access.

**Describe alternatives you've considered**

It doesn't look like there is any workaround for this or another option.

**Additional context**

This is similar to #46.

**Comment by andreacavagna01** [comment]
We will add it in the v1.0 we are working on. Need some changes to be applied and it will work with the Deamon I think

**Comment by andreacavagna01** [comment]
Will be added in the v0.4.3 version, in the early next week

**Comment by andreacavagna01** [comment]
Added in release v0.4.3
