### ISSUE TITLE
Ability to switch region for a single running session

### ISSUE THREAD

**Issue by urz9999** [Noovolari/leapp#69]
## Goal

- Ability to show immediately the current region for a session.
- Ability to switch regions inside the Leapp application, specifically in a session card for a session.

## Feasibility analysis

- Add region inside credential profile and Azure account.
    - Plain pipeline
    - Federated pipeline
    - Truster pipeline
    - SSO pipeline
    - Azure pipeline

### Show Current Region

- the UI must show immediately to the user, the region for every session.
- If a session has not a region selected by the user, a default one is used as described in the provider documentation.

**Acceptance:**

- the user is able to distinguish the region clearly.

<img width="786" alt="Schermata_2020-12-22_alle_11 38 16" src="https://user-images.githubusercontent.com/9497292/106482240-8ea17d80-64ad-11eb-875a-43e1d0581bf7.png">

### Switch Region

- The user select a region from a dropdown inside a modal
- The modal closes and the session is refreshed adding the region value to the credential profile or azure config file.
- No more action from the user are required.
- Minimal UI presented.

![switch_region](https://user-images.githubusercontent.com/9497292/106482389-b1cc2d00-64ad-11eb-834e-6de2809a6c60.png)

- When the user select another session from a specific provider, the old region is replaced by the selected one.

**Acceptance:**

- user is able to access resources and services in that specific region.

# AWS Pipeline

It is possible to add **region=<region>** to the profile [default] when creating the temporary credential set.

This is valid according to the official AWS reference: 

- [https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_temporary.html](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_temporary.html)
- [https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html)
- [https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html)

For retrocompatibility: we need to verify if a session as a region defined, if not us-east-1 is used as default, according to official documentation: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html

- We also need to change the default region selector to specifically ask for a region that becomes a **required parameter**.

# **Azure Pipeline**

By forcing the required region parameter to AWS, to ensure that the region is always used and displayed, we can now **add a region selector** in the create azure account form. This way is possible to alter the **azure config file** by also adding a default region under the [defaults] property tag.

```jsx
az configure --default location=${locationName}
```

This command **must be run after** the set subscription command to add the property.

Reference about default region and the current technical choice is here:

[https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration)

**Comment by andreacavagna01** [comment]
This feature is mentioned in #16

**Comment by andreacavagna01** [comment]
Also the same request of #23

**Comment by urz9999** [comment]
In addition we will add a default Region and Location selector for each Cloud Provider. 
The default configuration for both selector will be manageable from the "Options" menu.

**Comment by andreacavagna01** [comment]
Added in version 0.4.3
