### ISSUE TITLE
AWS SSO: Open Login in default browser

### ISSUE THREAD

**Issue by hoegertn** [Noovolari/leapp#71]
**Is your feature request related to a problem? Please describe.**
If I need to login to AWS SSO the in-app webview prevents my password manager to work.

**Describe the solution you'd like**
I would love to be able to open the login in a normal browser window where 1Password could auto-fill the login form.

**Comment by andreacavagna01** [comment]
Nice idea, we were thinking to open multiple consoles directly from the App.

We were thinking of it for the ability to open multiple consoles for different accounts simultaneously. Also need to check if we can inject the login info so from the session you will be automatically logged in.

Thanks for the suggestion!

**Comment by rverma-nsl** [comment]
This is somewhat convenient too since our aws sso is integrated with gsuite. Now everytime session expire this need to login through gsuite credentials in leapp app, which can be avoided since browser is already logged in with gsuite.

**Comment by andreacavagna01** [comment]
We will do a release in the next few days with this feature 👍  thanks to @hoegertn for working on it

**Comment by sheldonhull** [comment]
Bump. Any update on if this is going to be something released soon?
I'm planning on a blog post on this tool soon, as it's been incredible. Would love to know about the browser launching as well. Thanks for the hard work!

**Comment by andreacavagna01** [comment]
Hey, we are just testing the feature and then merging the branch with the login opened in browser and the support to named profile of AWS.
We will do a pre release on tomorrow I hope on our [slack workspace](https://join.slack.com/t/noovolari/shared_invite/zt-odkr73j9-0SDg2uGs3rEeKYJqXaEXJw) , for testing purposes. 
Then in the next week we will release it officially. 
Join our workspace if you wanna try this version early. 

Also I would love to talk with you about our other repository linked to this project, that is written in Go!

**Comment by pkuykendall** [comment]
I would also like to see this feature it would solve an issue for us where AWS redirects to O365 for SSO. O365 gives options to remember the device and require logins less frequently. They do not work in the in-app webview but would work in the default browser.

I could also open up another Issue if you think it's worth exploring for the in-app webview.

Thanks!

**Comment by andreacavagna01** [comment]
We are testing the feature and in the next week we will push it to the [workspace of Slack](https://join.slack.com/t/noovolari/shared_invite/zt-odkr73j9-0SDg2uGs3rEeKYJqXaEXJw) 
Later on, an official release will be made. Thanks to the attention on that issue
