### ISSUE TITLE
Copy credentials from ~/.aws/cli/cache/ to .aws/credentials file

### ISSUE THREAD

**Issue by arvindkgs** [Noovolari/leapp#72]
**Is your feature request related to a problem? Please describe.**
Older versions of terraform does not support AWS CLI v2 (that uses .aws/cli/cache), rather uses .aws/credentials file. However AWS SSO login through Leapp only updates the .aws/cli/cache file with temporary credentials.

**Describe the solution you'd like**
Copy credentials from .aws/cli/cache into .aws/credentials file

**Describe alternatives you've considered**
Manually copy paste credentials from .aws/cli/cache file to .aws/credentials

**Additional context**
While newer terraform AWS provider works with .aws/cli/cache, older versions do not work - https://github.com/hashicorp/terraform-provider-aws/issues/10851 . Many companies still use older terraform, so this would help all of us!

**Comment by andreacavagna01** [comment]
This is how Leapp actually [works](https://github.com/Noovolari/leapp/wiki/aws-sso-how-it-works).

Leapp store the access token of AWS Single Sign-On in an [encrypted file](https://github.com/Noovolari/leapp/wiki/vault-strategy) and then generate only temporary credentials in the ~/.aws/credentials file, which is automatically rotated by the App.

By doing so, every short-lived credential generated by Leapp is fully compatible with every version of Terraform, and every other tool
