### ISSUE TITLE
Multi IdP url support

### ISSUE THREAD

**Issue by urz9999** [Noovolari/leapp#77]
**Is your feature request related to a problem? Please describe.**
Add the ability to support more than one IdP to let users connect to different ones for each session saved.

**Describe the solution you'd like**
## Goal

- Using more than one IdP in Leap by moving the IdP url inside the federated account model.

## Feasibility analysis

**Add and manage more than one**

maybe is better to still keep all the managing of IdP URL in options, as it will concetrate all the operation in a less clumpsy place. Also by keeping a list in option we could manage the list in workspace as SAMLUrls: [], and then just have a selected SAML URL in the federated account.

Is true that we have to return to option everytime we make a mistake BUT being centralized, means that once you have all the correct ones creating new  federated is more easy.

**Editing**

To edit the most simple possibility is to remove and re-enter the value in the list. BUT doing this will make problem with accounts, so another way is to actually EDIT the value and to associate an ID to it so the account would still work the same.

**Remove**

Removing Federated and/or SAML url is more easy this way because:

- if we remove a federated accunt, no check s must be made on SAML urls
- if we remove a saml url because it is no more valid the selected SAML url will prevent the session to be inconsistent and a reasonable error will popup when trying to connect. **WE NEED to allow for editing of Federated,** or you'll need to delete and recreate the federated.

**Migrate from old workspace**

The old workspace keep a single value for the option, so what can we do is transform the variable to a list and make it possible to read the only one that is used there as it was one of the new list. To all the previous federated account we add a "selected IdP" which automatically points to the only one value. This way:

a) we don't lose the original variable/don't add unnecessary values in workspace/don't leave unused variable in workspace

b) we still keep things compatible.

Probably the best course of action would it be to have a separate tab for the Idps as the current option page can't handle more than one Idp at the moment.

Following are some suggestion of UI

<img width="432" alt="2" src="https://user-images.githubusercontent.com/9497292/108040401-887ad780-703d-11eb-90f3-d91dd340db37.png">
<img width="432" alt="1" src="https://user-images.githubusercontent.com/9497292/108040404-89136e00-703d-11eb-8884-7d184a7c1e06.png">

If we click add we add a new one when clicking on a edit button we can edit an existing one which will appear in the textbox. The edit button will transform in edit

with delete we can remove the element from the list.

Sessions will access this array and use it.

In addition to this, we will use a special select from angular to allow selecting and **creating** URLs on the fly on the session form.

[https://ng-select.github.io/ng-select#/search](https://ng-select.github.io/ng-select#/search)

**Federated form**

In the federated form where we define the new federated strategy we need to add a selector which points to the array we created in the option page. This selector has also the ability to create new urls on the fly. In case we save a new url, that string is also saved in the IdP array.

Here are some screenshot to show how we can define the UI adding the IdP selector

![proposal_2](https://user-images.githubusercontent.com/9497292/108040393-8749aa80-703d-11eb-8c09-3dcbe0780721.png)
![proposal](https://user-images.githubusercontent.com/9497292/108040399-87e24100-703d-11eb-88f1-637013258825.png)

The second one keeps the same space as before but reduces the space for both IdP URL and IdP ARN.

### Use the correct IdP for every Federated Strategy

**Acceptance:**

- the session must become active and the sts-get-caller-identity call must show the correct role assumed.
- When we do logout we must verify that we are logging out from the correct IdP.
- When the user select another session from a specific provider, the old region is replaced by the selected one.

**Comment by urz9999** [comment]
For managing multiple Idp Safely we added different partitions for every different URL (encoded in base 64) with a "leapp-" suffix and we use rimraf to delete only those partitions ensuring that we are independent about what kind of IdP is registered. Also, this allows saving more than one account with the same IdP URL but also a different URL from the same Provider (thus using the same cookies)

**Comment by andreacavagna01** [comment]
closed in v0.4.5
