### ISSUE TITLE
Application is not web proxy aware, not functional inside corporate networks

### ISSUE THREAD

**Issue by ashishdesaifmr** [Noovolari/leapp#8]
For large enterprise, our corporate networks are not internet routable, so all egress traffic from a desktop must exit out via a web proxy (example Squid).
Application needs to either use the proxy definition that the OS automatically get via GPO policy or needs to allow end user to setup a variable to define the proxy settings.
Typically setup info needed
http.proxyhost   http.proxyhostport
https.proxy        https.proxyhostport
proxy auth username/password

As an example see how VS code or other Electron apps are setup, you can leverage same code/config setup.

**Comment by andreacavagna01** [comment]
Hi @ashishdesaifmr, thanks for the issue report, we are working on a solution that will implement your needs. 
Is in the refactoring point of our [Roadmap](https://github.com/Noovolari/leapp/projects/1).

I have a question for you, which Cloud Providers are you using in your company?

**Comment by ashishdesaifmr** [comment]
We current use aws and azure

________________________________

**Comment by andreacavagna01** [comment]
Hi @ashishdesaifmr, Today we are releasing the support to Azure as Cloud Provider, than The proxy feature is the next :)

**Comment by ericvilla** [comment]
Hi @ashishdesaifmr, we're working on the HTTP Proxy Configuration support. We've already implemented the in-app HTTP Proxy Pass, i.e. make HTTP calls issued by Leapp pass through the Proxy specified in the HTTP Proxy Configuration. Moreover, we are on the way to add support for Proxy authentication, adding username and password to the HTTP Proxy Configuration.

I've just a question for you: what's your opinion about the possibility to make Leapp inherit Proxy OS Configuration? We're trying to understand if it is a critical feature that we should ship with the release v0.3.0, and external feedback would be useful.

Thank you!

**Comment by ashishdesaifmr** [comment]
Hi Eric,

Inheriting the OS level configs is not important.
In fact at times we really like the ability to override the OS level proxy configs as corporate environments have complex configs and at time we need to route via a specific proxy vs using what the OS level config has.

Hope this helps,
Ashish

**Comment by pethron** [comment]
I think that right now we can settle with the custom proxy as it only needs to be configured to work for everyone.
We can add at a later time the inheritance from OS configuration.

**Comment by ericvilla** [comment]
Hi @ashishdesaifmr,

thank you for your feedback! I agree with @pethron; we can rely on in-app proxy configuration and focus on os's proxy configuration at a later time.

Just to be clear, I will highlight the fact that we're covering only HTTP/HTTPS requests made my Leapp, i.e. logins and logouts against G Suite. Those are the only HTTP/HTTPS requests made by the client.

I will give you updates regarding the Proxy Authentication feature development.

Thank you!

**Comment by urz9999** [comment]
added in 0.3.0. Please check the option page for configuration parameters.
