### ISSUE TITLE
Proxy not set

### ISSUE THREAD

**Issue by jacobneroth** [Noovolari/leapp#80]
**Describe the bug**
The proxy settings in Leapp is not getting saved

**Leapp Version**
Version 0.4.5

**To Reproduce**
1. Go to Options
2. Select General Tab
3. Click on Proxy Settings
4. Update the Proxy URL
5. CLick on Save
6. Go back to the same screen, it still shows undefined.

**Expected behavior**
Proxy setting is saved

**Screenshots**
![image](https://user-images.githubusercontent.com/1866864/109129542-0a12e980-7751-11eb-9893-b5ae20ba19e7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version 10
 - Leapp Version 0.4.5

**Additional context**

**Comment by andreacavagna01** [comment]
Thanks for reporting, @urz9999 could you check it out and do a hotfix to this?

**Comment by urz9999** [comment]
Uhm, I did what you said and It worked, did a modal confirming to restart the app showed to you @jacobneroth ?

<img width="407" alt="Screenshot 2021-02-25 at 10 57 55" src="https://user-images.githubusercontent.com/9497292/109136397-5d3c6a80-7758-11eb-89cb-60e3edb1a01d.png">

**Comment by urz9999** [comment]
Maybe restart the app and also please check your logs for any error in this location:

%USERPROFILE%\\AppData\\Roaming\\Leapp\\log.log

**Comment by jacobneroth** [comment]
This is the log entries.

[2021-02-25 14:52:21.664] [info] Setupping workspace for the first time
[2021-02-25 14:52:21.667] [warn] directory leapp or aws already exist
[2021-02-25 14:52:22.209] [info] feedURL https://update.electronjs.org/Noovolari/leapp/win32-x64/0.4.5
[2021-02-25 14:52:22.211] [info] requestHeaders { 'User-Agent': 'Leapp/latest (win32: x64)' }
[2021-02-25 14:52:22.211] [info] checking-for-update
[2021-02-25 14:52:23.325] [info] update-not-available

Also noticed there was no region setup like you have above
![image](https://user-images.githubusercontent.com/1866864/109163337-86212780-7779-11eb-9a36-56a12a4149a9.png)

**Comment by andreacavagna01** [comment]
Looks like a JS problem, I'm gonna investigating it, thanks for reporting it!

**Comment by urz9999** [comment]
Ok, I've managed to reproduce your problem, much probably you've started fresh and didn't create any kind of session, then you'll found yourself on the main page and then go to the options page but the workspace object is not initialized already thus generating undefined objects which prevent save function to work. I'm working on a hotfix to prevent this kind of situation, in the meantime, you can avoid the problem like this:

1) Clean the config file: go to <user>/AppData/Roaming/.Leapp and remove the leapp-lock.json file.
2) Restart the application and be sure to add at least one kind of session: being it federated, plain or so.
3) Check if the options page work as expected now.

This bug can only verify on new installation

**Comment by jacobneroth** [comment]
Thanks guys for the quick turnaround
