### ISSUE TITLE
Filter functionality not working in 0.4.5

### ISSUE THREAD

**Issue by AMMullan** [Noovolari/leapp#82]
**Describe the bug**
After upgrading to 0.4.5 the filter functionality does not work at all. I have tried entering an account ID, and a name, but nothing happens. Downgrading to 0.4.4 works as expected.

**Leapp Version**
0.4.5

**To Reproduce**
1. Open Leapp
2. Enter in a search term

**Expected behavior**
List of accounts containing/matching what is entered (account ID or name) should be listed, instead all accounts are still listed.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version 10
 - Leapp Version 0.4.5

**Comment by urz9999** [comment]
Managed to replicate the issue on windows ONLY, so now I'm investigating why there are differences, please stay tuned

**Comment by urz9999** [comment]
Found the problem, correcting it asap, missing an undefined condition in the filter
