### ISSUE TITLE
AWS Sso doesnt list application / accounts

### ISSUE THREAD

**Issue by jacobneroth** [Noovolari/leapp#86]
**Describe the bug**
Leapp doesnt indicate the List of Accounts when trying to integrate with AWS SSO.

**Leapp Version**
Leapp Version 0.46

**To Reproduce**
1. On the Startup Page , Click on AWS 
2. Click on + sign
3. Choose AWS SSO
4. Enter the Region, the SSO URL 
5. Leapp opens up the AWS Screen with automatically filled in CLI keys
**Expected behavior**
After Step 5 , it is expected to see all the accounts under the SSO but the following was seen below.

**Screenshots**
![image](https://user-images.githubusercontent.com/1866864/109606558-1fa85a80-7b27-11eb-8695-65f7850b6a6f.png)

**Desktop (please complete the following information):**
 - OS: WIndows 10
  - Leapp Version 0.4.6

**Additional context**

**Comment by andreacavagna01** [comment]
It looks like a problem with AWS Single Sign-On Auth Flow.
Leapp, if the login flow with the AWS SSO service is not corrected, can't retrieve all the information in order to retrieve the list of available accounts.


Also, I'm trying to find the error online, but it looks like an uncommon error. 

I Will look more into it late this week,

Thanks for reporting @jacobneroth

**Comment by ericvilla** [comment]
Hi @jacobneroth, may I ask you to provide the logs which location is specified [here](https://github.com/Noovolari/leapp/#logs)?

Thank you for your patience

**Comment by ericvilla** [comment]
@jacobneroth please double check if you can find AWS_SSO_PORTAL_URL, AWS_SSO_REGION, AWS_SSO_ACCESS_TOKEN, and AWS_SSO_EXPIRATION_TIME in your system keychain; perhaps there was a problem storing this information. 

Thank you!

**Comment by jacobneroth** [comment]
[log.log](https://github.com/Noovolari/leapp/files/6076324/log.log)
Here you go.

**Comment by jacobneroth** [comment]
I tried to debug the issue but when i tried to run this from command line
aws sso-oidc register-client --client-name leapp --client-type public
it basically hung and now looks like normal
aws configure sso stopped working :(

Only way to get it working now is using containerized aws cli

**Comment by ericvilla** [comment]
Hi @jacobneroth, thank you for the logs. Unfortunately, they don't tell me the cause of the issue.
What is `aws configure sso` output?

**Comment by andreacavagna01** [comment]
> I tried to debug the issue but when i tried to run this from command line
> aws sso-oidc register-client --client-name leapp --client-type public
> it basically hung and now looks like normal
> aws configure sso stopped working :(
> 
> Only way to get it working now is using containerized aws cli

Looks like AWS isn't grating you the ability of creating a client for AWS SSO. Wired.. 

Are you using a proxy or there is a network redirect that can be the problem of this issue?

**Comment by jacobneroth** [comment]
We do use proxy

**Comment by jacobneroth** [comment]
Container based Aws cli is the only thing which works , I have raised a ticket aws cli on that topic

**Comment by andreacavagna01** [comment]
I think it's an AWS cli related problem, please link the issue with this one and we will check if there is a problem in registering a client with a Proxy configuration

**Comment by jacobneroth** [comment]
https://github.com/aws/aws-cli/issues/5978

**Comment by andreacavagna01** [comment]
closed due to inactivity
