### ISSUE TITLE
Add a search option in the SSM session panel

### ISSUE THREAD

**Issue by infsy** [Noovolari/leapp#87]
When I use the SSM session panel to start a new connection with one of my instances, I'm limited by the fact that the panel can only show 10 instances. If I've got more than 10 instances in my account and my region, then I can't see them neither specify one of them. I can just hope than the instance I want to connect to is in this list of 10 instances.

Having at a minimum the limit expanded with a way to scroll could be useful. But it can be complicated to navigate within account with hundred of instances. So, the limit of 10 in the panel can be ok if we have a way to search and filter the list. That would be the perfect solution to actually be able to deal with largest AWS accounts.

Adding just a field to filter and search in the SSM session panel would be enough from a graphical perspective.

**Comment by andreacavagna01** [comment]
We have to integrate infinite scrolling in the SSM feature, I will work on it this week

**Comment by andreacavagna01** [comment]
Also, a search filter could be a great idea. Nice enhancement

**Comment by andreacavagna01** [comment]
We've added the fix and it will be in the next release, please in the next release let me know if it is solved

**Comment by infsy** [comment]
Great news @andreacavagna01  ! I will give you the feedback as soon as it will be tested ! Thanks for the quick fix !

**Comment by ericvilla** [comment]
This enhancement issue is covered in the last [release](https://www.leapp.cloud/releases)! I'm going to close it
