### ISSUE TITLE
There was a problem generating credentials

### ISSUE THREAD

**Issue by suspiration** [Noovolari/leapp#88]
**Describe the bug**
I've entered in multiple AWS account using Plain Access Strategy.  The app works for account which I'm an admin of, however, for accounts which I'm not an admin, it is giving me an error saying "There was a problem generating credentials.".

Checking log, I see the below error:

> [error] [renderer] [t] Error in Aws Credential process IncompleteSignature: '/20210316/us-east-1/sts/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=<OMITTED FOR SECURITY REASON> /20210316/us-east-1/sts/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-user-agent, Signature=<OMITTED FOR SECURITY REASON>'.

What are the access requirements on my AWS account in order to use Leapp?

**Leapp Version**
Version 0.4.6 (0.4.6)

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.15.7
 - Leapp Version 0.4.6 (0.4.6)

**Comment by andreacavagna01** [comment]
Thanks for reporting

Looks like the keypair "ACCESS KEY" and "SECRET KEY" aren't provided in the correct way, I will check if it is a problem in the saving method, please check if the IAM User added in Leapp correspond with the one in the AWS console.
A possible problem can be just a white space, let me know

**Comment by alancape** [comment]
Thanks @andreacavagna01 that was it, there is an extra whitespace at the end of my "ACCESS KEY".  

Might be useful to trim the values before saving.

**Comment by suspiration** [comment]
Thanks @andreacavagna01 that was it.  There is an extra whitespace at the end of my "ACCESS KEY". 

Might be useful to trim the values before saving.

**Comment by andreacavagna01** [comment]
I'll add it in the next release! Nice idea

**Comment by andreacavagna01** [comment]
fixed in v.0.6.0
