### ISSUE TITLE
AWS SSO requires to login every day

### ISSUE THREAD

**Issue by m-radzikowski** [Noovolari/leapp#92]
**Describe the bug**

With AWS Single Sign-On Identity Provider, I have to log in to Google GSuite (my SSO provider) every day (as the session lasts for 8 or 12 hours). This is quite annoying and was reported as a problem by my colleagues as well.

**Leapp Version**

0.4.6

**To Reproduce**

1. Set up an AWS SSO
2. Add AWS account with strategy Truster
3. Select this account to connect - requires signing in through the GSuite
    - "Stay signed in" is checked
4. Next day, repeat step 3 - I need to sign in (providing email and password) again

**Expected behavior**

If during GSuite login I have "Stay signed in" selected, the next day I should be authorized to the GSuite automatically, and have to only confirm signing in with AWS button "Sign in to AWS CLI".

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: 10.15.6 (Catalina)
 - Leapp Version: 0.4.6

**Comment by andreacavagna01** [comment]
Hi, @m-radzikowski. Sadly, this is an AWS Single Sign-On Limitation:
https://docs.aws.amazon.com/singlesignon/latest/userguide/sso-ug.pdf
On page 78 of the Service guide:
"Note
Once you have been signed-in, your user portal session will be valid for 8 hours."
Sadly, this is the maximum time eligible duration of the token, and the token period still can't be overridden.

**Comment by m-radzikowski** [comment]
The problem is not with SSO token timeout (that I know), but with being "logged out" of the GSuite every time. Maybe I didn't describe this correctly.

With the same flow in CLI, I need to authorize to GSuite with my email+password once, for the first time. Then every 8 hours I only need to login through SSO. The login procedure does OAuth flow (or similar) with GSuite. Every next time, after running `aws sso login`, the OAuth flow goes with few redirects automatically and at the end I only need to click "Sign in to AWS CLI" AWS button to confirm authorization.

This is basically like with every other SSO on the web - you authorize with Google / whatever once to get long-lived token for given page, that is used to obtain short-lived token every next time you enter page (after session times out).

In Leapp, I need to log in to GSuite every time, providing email+password.

**Comment by andreacavagna01** [comment]
Oh, that's gonna be fixed with #90 that will solve this problem, In next week we will release it I think

**Comment by PatrykMilewski** [comment]
Hey @andreacavagna01 any plans to release a new version?

**Comment by andreacavagna01** [comment]
Early next week! Testing the bundle in this days

**Comment by andreacavagna01** [comment]
Closed after the release of v0.4.7

**Comment by PatrykMilewski** [comment]
Can we reopen this one? After last rollbacks, it's still the issue

**Comment by andreacavagna01** [comment]
absolutely! we will reintroduce methods to resolve this issue in future releases

**Comment by m-radzikowski** [comment]
No longer a problem since the in-browser SSO handling option in v0.7.4.

**Comment by shankara-n** [comment]
Still an issue for users who login with email and password.
