### ISSUE TITLE
Support for Azure AD Service Principals

### ISSUE THREAD

**Issue by andreacavagna01** [Noovolari/leapp#93]
Add plain support for Azure AD Service Principals like we've done for AWS Plain Account

**Comment by ericvilla** [comment]
It is an interesting feature. I would spend my two cents on it, as I've taken some time to understand how SPs work.
So, basically, they're thought to be used for automation script and application development, but I've already found two different use case in which support to Service Principal could come in handy.

- First one: you can log into Azure with Service Principals credentials using the password or certificate-based authentication.
- Second option: you can use `az ad sp create-for-rbac — sdk-auth` command to obtain a JSON representation of the Service Principal, that can be used by applications based on Azure SDK.

Let me know if it makes sense to you.

References:
- https://docs.microsoft.com/en-us/dotnet/azure/authentication
- https://docs.microsoft.com/it-it/cli/azure/ad/sp?view=azure-cli-latest#az_ad_sp_create_for_rbac
