### ISSUE TITLE
Support for URL referrals

### ISSUE THREAD

**Issue by tbugfinder** [Noovolari/leapp#95]
**Is your feature request related to a problem? Please describe.**

In case the initial URL is using referrals it doesn't work. It shouldn't redirect to the actual login page.

**Describe the solution you'd like**

The tool should support referrals when opening AWS SSO.

**Describe alternatives you've considered**

**Additional context**

**Comment by andreacavagna01** [comment]
Thanks for the report, we will see how integrate this particular feature

**Comment by andreacavagna01** [comment]
Added in release v.0.5.0, let me know if it works in the new release
