### ISSUE TITLE
AWS SSO Unable to login using Okta IdP

### ISSUE THREAD

**Issue by Gavin89** [Noovolari/leapp#99]
**Describe the bug**
When setting up AWS SSO, I enter my SSO details, which redirects me to my 2mfa (duo), and as it goes to allow me to push code, it closes and i get [2021-04-05 14:01:12.094] [error] [renderer] [e] net::ERR_CONNECTION_REFUSED

So I am unable to proceed. 

**Leapp Version**
v0.4.6

**To Reproduce**
1. Go to 'My Integration is AWS SSO'
2. Enter SSO Url and Region and click  AWS SSO button
3. Redirects me to my IdP (Okta), and asks me to login
4. You can see it then redirects to Duo Mobile, but then pops up with ERR_CONNECTION_REFUSED

**Expected behavior**
I'd expect it to pop up asking me to enter duo code, or push. Then log me in, and show all my available accounts I can login with.

**Screenshots**
Can't catch screenshot as it closes instantly

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - OS Version 10.14.6
 - Leapp Version v0.4.6

**Additional context**
I have tried to login to slack, but can't

**Comment by andreacavagna01** [comment]
The AWS SSO login flow is going to change in the next release, will work with the default browser

**Comment by Gavin89** [comment]
Hi @andreacavagna01 is there anyway around it for now, or do I have to wait for the next release? Also, how can I get in the leapp slack?

**Comment by andreacavagna01** [comment]
It's a network problem I've already faced but I've never reproduced it to fix it, for now, you can try log out from your Web Browser and try to log into aws sso. remember to check the correctness of aws sso URL (it must finish with `/start`)
If you want to join Slack click [here](https://join.slack.com/t/noovolari/shared_invite/zt-opn8q98k-HDZfpJ2_2U3RdTnN~u_B~Q)

**Comment by andreacavagna01** [comment]
Closing this issue after the release
